// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store (unknown)
// 	protoc (unknown)
//
// database: v1
// package:  repox
//
// Shared runtime for the generated proto-facing repositories.
// annotations: protokit.v1 (unknown), store.v1 (unknown)
//
// store — https://github.com/the-protobuf-project/store

// Package repox is the shared runtime of the generated repositories: the error
// vocabulary adapters map their backend errors onto, the connection bundle the
// per-schema factories pick an adapter from, the list-request shape every
// repository List takes, and the small helpers (resource-name splitting, ULID
// minting, mask matching) the generated method bodies share.
package repox

import (
	"crypto/rand"
	"errors"
	"fmt"
	"strings"
	"time"

	"gorm.io/gorm"

	genql "example.com/test/genql"
	"example.com/test/gormdb/filterx"
)

// Error sentinels the repository interfaces speak. Callers translate them to
// their transport's codes (e.g. gRPC NotFound / AlreadyExists / Aborted /
// InvalidArgument) with errors.Is.
var (
	ErrNotFound        = errors.New("not found")
	ErrAlreadyExists   = errors.New("already exists")
	ErrConflict        = errors.New("conflict")
	ErrInvalidArgument = errors.New("invalid argument")
)

// Conn bundles the live backend handles a repository factory can adapt.
type Conn struct {
	Gorm    *gorm.DB
	GraphQL *genql.Service
}

// ListInput is the request shape every repository List takes: AIP page
// controls, an order_by string, and a raw AIP-160 filter expression.
type ListInput struct {
	PageSize  int32
	PageToken string
	OrderBy   string
	Filter    string
}

// MapGormErr translates GORM's storage errors onto the repox sentinels,
// passing everything else (including sentinels already mapped inside a
// transaction) through unchanged.
func MapGormErr(err error) error {
	switch {
	case err == nil:
		return nil
	case errors.Is(err, gorm.ErrRecordNotFound):
		return ErrNotFound
	case errors.Is(err, gorm.ErrDuplicatedKey):
		return ErrAlreadyExists
	default:
		return err
	}
}

// MapFilterxErr translates the filter/order engines' rejection onto
// ErrInvalidArgument, keeping the descriptive message.
func MapFilterxErr(err error) error {
	if err == nil {
		return nil
	}
	if errors.Is(err, filterx.ErrInvalid) {
		return fmt.Errorf("%w: %s", ErrInvalidArgument, err.Error())
	}
	return err
}

// SplitName splits an AIP resource name into its bare ids, validating the
// collection segments: SplitName("organisations/o1/members/m1",
// "organisations", "members") → ["o1", "m1"]. Any other shape is rejected
// with ErrInvalidArgument.
func SplitName(name string, collections ...string) ([]string, error) {
	parts := strings.Split(name, "/")
	if len(parts) != 2*len(collections) {
		return nil, fmt.Errorf("%w: malformed resource name %q", ErrInvalidArgument, name)
	}
	ids := make([]string, 0, len(collections))
	for i, c := range collections {
		if parts[2*i] != c || parts[2*i+1] == "" {
			return nil, fmt.Errorf("%w: malformed resource name %q", ErrInvalidArgument, name)
		}
		ids = append(ids, parts[2*i+1])
	}
	return ids, nil
}

// LastSegment returns the final path component of a resource name — the bare
// id a reference column stores ("users/7" → "7").
func LastSegment(name string) string {
	if i := strings.LastIndex(name, "/"); i >= 0 {
		return name[i+1:]
	}
	return name
}

// InMask reports whether the mask selects field: an empty mask selects
// everything (full replace), otherwise an exact path match.
func InMask(paths []string, field string) bool {
	if len(paths) == 0 {
		return true
	}
	for _, p := range paths {
		if p == field {
			return true
		}
	}
	return false
}

// GroupTouched reports whether the mask touches field or any of its subpaths —
// message-typed fields are replaced wholesale when any part is selected.
func GroupTouched(paths []string, field string) bool {
	if len(paths) == 0 {
		return true
	}
	for _, p := range paths {
		if p == field || strings.HasPrefix(p, field+".") {
			return true
		}
	}
	return false
}

// Ptr returns a pointer to v, for optional model columns.
func Ptr[T any](v T) *T { return &v }

// Deref returns *p, or T's zero value when p is nil.
func Deref[T any](p *T) T {
	if p == nil {
		var zero T
		return zero
	}
	return *p
}

// crockford is the ULID alphabet (Crockford base32, no I/L/O/U).
const crockford = "0123456789ABCDEFGHJKMNPQRSTVWXYZ"

// NewULID mints a 26-character ULID: 48 bits of millisecond timestamp and 80
// bits of crypto randomness, Crockford-base32 encoded — the same shape and
// ordering guarantees as the canonical spec, with no external dependency.
func NewULID() string {
	var b [16]byte
	ms := uint64(time.Now().UnixMilli())
	b[0], b[1], b[2], b[3], b[4], b[5] = byte(ms>>40), byte(ms>>32), byte(ms>>24), byte(ms>>16), byte(ms>>8), byte(ms)
	if _, err := rand.Read(b[6:]); err != nil {
		panic(fmt.Sprintf("repox: reading crypto/rand: %v", err))
	}
	// Encode the 128 bits as 26 base32 chars, most significant first: char c
	// covers bits [5c, 5c+5) of a virtual 130-bit value whose top two bits are
	// zero (so the first char is always 0-7, per the canonical spec).
	bitAt := func(i int) byte { // i in [0,130), 0 = most significant
		if i < 2 {
			return 0
		}
		i -= 2
		return (b[i/8] >> (7 - i%8)) & 1
	}
	var out [26]byte
	for c := 0; c < 26; c++ {
		var v byte
		for j := 0; j < 5; j++ {
			v = v<<1 | bitAt(c*5+j)
		}
		out[c] = crockford[v]
	}
	return string(out[:])
}
