// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store (unknown)
// 	protoc (unknown)
// source: filters.proto
//
// database: v1
// schema:   venue_v1
//
// AIP-160 filter / AIP-132 order_by specs — data for the shared filterx engines.
// annotations: entity.v1 (unknown), store.v1 (unknown)
// engine:      protokit (unknown)
//
// store — https://github.com/the-protobuf-project/store

package venuev1

import (
	"example.com/test/gen/filterx"
)

// VenueFilterSpec is Venue's AIP-160 filter / AIP-132 order_by surface,
// consumed by the filterx.Gorm and filterx.Hasura engines.
var VenueFilterSpec = filterx.Spec{
	Table: `"venue_v1"."venues"`,
	Fields: map[string]filterx.FieldSpec{
		"capacity":       {Column: "capacity", Kind: filterx.KindInt},
		"create_time":    {Column: "create_time", Kind: filterx.KindTimestamp},
		"display_name":   {Column: "display_name", Kind: filterx.KindText},
		"kind":           {Column: "kind", Kind: filterx.KindEnum, EnumPrefix: "VENUE_KIND_"},
		"licence_expiry": {Column: "licence_expiry", Kind: filterx.KindDate},
		"name":           {Column: "name", Kind: filterx.KindText},
		"nonce":          {Column: "nonce", Kind: filterx.KindText},
		"open_air":       {Column: "open_air", Kind: filterx.KindBool},
		"operator":       {Column: "operator", Kind: filterx.KindRef},
		"tags":           {Column: "tags", Kind: filterx.KindTags},
	},
	Search: []string{"display_name"},
	Sort: map[string]filterx.SortSpec{
		"capacity":       {Column: "capacity", Kind: filterx.KindInt},
		"create_time":    {Column: "create_time", Kind: filterx.KindTimestamp, NotNull: true},
		"display_name":   {Column: "display_name", Kind: filterx.KindText, NotNull: true},
		"internal_code":  {Column: "internal_code", Kind: filterx.KindText},
		"kind":           {Column: "kind", Kind: filterx.KindEnum, NotNull: true},
		"licence_expiry": {Column: "licence_expiry", Kind: filterx.KindDate},
		"name":           {Column: "name", Kind: filterx.KindText, NotNull: true},
		"open_air":       {Column: "open_air", Kind: filterx.KindBool},
	},
	PK: []filterx.SortSpec{{Column: "id", Kind: filterx.KindText, NotNull: true}},
}

// OperatorFilterSpec is Operator's AIP-160 filter / AIP-132 order_by surface,
// consumed by the filterx.Gorm and filterx.Hasura engines.
var OperatorFilterSpec = filterx.Spec{
	Table: `"venue_v1"."operators"`,
	Fields: map[string]filterx.FieldSpec{
		"display_name": {Column: "display_name", Kind: filterx.KindText},
		"name":         {Column: "name", Kind: filterx.KindText},
	},
	Search: []string{"display_name"},
	Sort: map[string]filterx.SortSpec{
		"display_name": {Column: "display_name", Kind: filterx.KindText, NotNull: true},
		"name":         {Column: "name", Kind: filterx.KindText, NotNull: true},
	},
	PK: []filterx.SortSpec{{Column: "id", Kind: filterx.KindText, NotNull: true}},
}
