// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store (unknown)
// 	protoc (unknown)
// source: filters.proto
//
// database: v1
// schema:   venue_v1
//
// annotations: protokit.v1 (unknown), store.v1 (unknown)
// runtime:     gorm.io/gorm
//
// store — https://github.com/the-protobuf-project/store

package venuev1

import (
	"context"
	"time"

	"example.com/test/gen/gormx"
	"gorm.io/gorm"
)

// VenueStoreIface is the full data-access surface of Venue: everything
// VenueStore does, as an interface.
//
// It exists so a decorator — caching, tracing, retries, a test double — can be
// written in its own package against this contract, without that package needing
// to edit anything in this tree. Embed it, override the methods you care about,
// and delegate the rest:
//
//	type cachedVenueStore struct {
//		VenueStoreIface
//		cache Cache
//	}
//
// Construction is deliberately absent. NewVenueStore returns the concrete
// *VenueStore, and WithTelemetry is a chainable setter that also returns it, so
// a caller keeps the full type at the point of wiring and narrows to this
// interface at the point of use — which is the direction that stays useful when
// a decorator is added later.
type VenueStoreIface interface {
	Create(ctx context.Context, m *Venue) error
	List(ctx context.Context, opts gormx.ListOptions) ([]Venue, error)
	Count(ctx context.Context, opts gormx.ListOptions) (int64, error)
	Update(ctx context.Context, m *Venue) error
	GetByID(ctx context.Context, id string) (*Venue, error)
	DeleteByID(ctx context.Context, id string) error
	GetByName(ctx context.Context, v string) (*Venue, error)
	ListByOperatorID(ctx context.Context, id string, opts gormx.ListOptions) ([]Venue, error)
}

// VenueStore provides typed CRUD access to Venue records.
// Venue exercises the filters emitter: type-derived kinds for every scalar shape (text, enum, date, timestamp, int, bool, tags), the search opt-in, the filterable/sortable opt-outs, a resource reference (equality-only Ref kind), and shapes that are always excluded (JSONB attributes, the synthesized key).
type VenueStore struct {
	DB *gorm.DB
	// Telemetry observes every operation; nil is a no-op. Wire the generated
	// adapter: NewVenueStore(db).WithTelemetry(telemetry.New(o)).
	Telemetry gormx.Telemetry
}

// Compile-time proof that VenueStore implements its own interface. Without it a
// signature could drift from VenueStoreIface and only break in whichever downstream
// package decorates it.
var _ VenueStoreIface = (*VenueStore)(nil)

// Compile-time proof that VenueStore satisfies the generic gormx.Store, so the
// generic engine can drive it alongside the typed finders below.
var _ gormx.Store[Venue] = (*VenueStore)(nil)

// NewVenueStore returns a VenueStore backed by db.
func NewVenueStore(db *gorm.DB) *VenueStore { return &VenueStore{DB: db} }

// WithTelemetry sets the store's Telemetry and returns the store for chaining.
func (s *VenueStore) WithTelemetry(t gormx.Telemetry) *VenueStore {
	s.Telemetry = t
	return s
}

// Create inserts m.
func (s *VenueStore) Create(ctx context.Context, m *Venue) error {
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "venue_v1.Venue/Create", m, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).Create(m).Error
	})
	tel.RecordOp(ctx, "venue_v1.venues", "create", time.Since(start), err)
	return err
}

// List returns the Venue records matching opts.
func (s *VenueStore) List(ctx context.Context, opts gormx.ListOptions) ([]Venue, error) {
	var out []Venue
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "venue_v1.Venue/List", nil, func(ctx context.Context) error {
		return opts.Apply(s.DB.WithContext(ctx)).Find(&out).Error
	})
	tel.RecordOp(ctx, "venue_v1.venues", "list", time.Since(start), err)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Count returns the number of Venue records matching opts.Where
// (pagination and ordering are ignored).
func (s *VenueStore) Count(ctx context.Context, opts gormx.ListOptions) (int64, error) {
	var n int64
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "venue_v1.Venue/Count", nil, func(ctx context.Context) error {
		db := s.DB.WithContext(ctx).Model(&Venue{})
		if opts.Where != nil {
			db = db.Where(opts.Where, opts.Args...)
		}
		return db.Count(&n).Error
	})
	tel.RecordOp(ctx, "venue_v1.venues", "count", time.Since(start), err)
	if err != nil {
		return 0, err
	}
	return n, nil
}

// Update persists every field of m, which must carry its primary key.
func (s *VenueStore) Update(ctx context.Context, m *Venue) error {
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "venue_v1.Venue/Update", m, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).Save(m).Error
	})
	tel.RecordOp(ctx, "venue_v1.venues", "update", time.Since(start), err)
	return err
}

// GetByID fetches the Venue with the given primary key.
func (s *VenueStore) GetByID(ctx context.Context, id string) (*Venue, error) {
	var m Venue
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "venue_v1.Venue/GetByID", nil, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).First(&m, "id = ?", id).Error
	})
	tel.RecordOp(ctx, "venue_v1.venues", "get", time.Since(start), err)
	if err != nil {
		return nil, err
	}
	return &m, nil
}

// DeleteByID removes the Venue with the given primary key.
func (s *VenueStore) DeleteByID(ctx context.Context, id string) error {
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "venue_v1.Venue/DeleteByID", nil, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).Delete(&Venue{}, "id = ?", id).Error
	})
	tel.RecordOp(ctx, "venue_v1.venues", "delete", time.Since(start), err)
	return err
}

// GetByName fetches the Venue with the given name (a unique column).
func (s *VenueStore) GetByName(ctx context.Context, v string) (*Venue, error) {
	var m Venue
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "venue_v1.Venue/GetByName", nil, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).First(&m, "name = ?", v).Error
	})
	tel.RecordOp(ctx, "venue_v1.venues", "get_by_name", time.Since(start), err)
	if err != nil {
		return nil, err
	}
	return &m, nil
}

// ListByOperatorID returns the Venue records whose operator matches id, with opts applied.
func (s *VenueStore) ListByOperatorID(ctx context.Context, id string, opts gormx.ListOptions) ([]Venue, error) {
	var out []Venue
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "venue_v1.Venue/ListByOperatorID", nil, func(ctx context.Context) error {
		return opts.Apply(s.DB.WithContext(ctx).Where("operator = ?", id)).Find(&out).Error
	})
	tel.RecordOp(ctx, "venue_v1.venues", "list_by_operator", time.Since(start), err)
	if err != nil {
		return nil, err
	}
	return out, nil
}
