// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store (unknown)
// 	protoc (unknown)
// source: b_promo.proto
//
// database: shop_db
// schema:   promo
//
// annotations: protokit.v1 (unknown), store.v1 (unknown)
//
// store — https://github.com/the-protobuf-project/store

package promo

import (
	"example.com/test/gen/shop_db/ordering"
)

// Coupon is a resource in the promo schema referencing Money cross-schema.
type Coupon struct {
	// Unique identifier for the record.
	ID string `gorm:"column:id;primaryKey;not null" json:"id"`
	// name: AIP resource name → UNIQUE lookup column (id is the synthesized PK).
	Name string `gorm:"column:name;not null;uniqueIndex" json:"name" validate:"required"`
	// Foreign key to Money.
	AmountOffID *string         `gorm:"column:amount_off_id;index:idx_coupons_amount_off_id" json:"amount_off_id,omitempty"`
	AmountOff   *ordering.Money `gorm:"foreignKey:AmountOffID;constraint:OnDelete:SET NULL" json:"amountoff,omitempty"`
}

func (*Coupon) TableName() string { return "promo.coupons" }
