// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm (unknown)
// 	protoc (unknown)
//
// database: hotel_db
// package:  cache
//
// Cache keys and a Redis client, generated from each resource's (orm.v1.cache) policy.
//
// orm — https://github.com/the-protobuf-project/orm

package cache

import "strings"

// The key builders below are generated from each resource's (orm.v1.cache)
// policy. Keys read as the resources they hold — "hotel.bookings/id:01ARZ3…" —
// so a keyspace dump is legible, and every key for a resource sits under its
// collection prefix, which is what lets one call invalidate it.

// --- hotel.bookings ---

// BookingCollection is the prefix every cached entry for a Booking
// sits under. Deleting it invalidates the resource entirely.
const BookingCollection = "hotel.bookings/"

// BookingListPrefix is where cached Booking list results live. The
// "$" segment cannot occur in a resource id, so a list key can never collide
// with a resource key while still sitting under the collection prefix.
const BookingListPrefix = "hotel.bookings/$list/"

// BookingTTL is the default lifetime of a cached Booking, in seconds;
// 0 means no expiry.
const BookingTTL = 300

// BookingIDKey is the key for a Booking looked up by
// id.
func BookingIDKey(vals ...any) string { return Key("hotel.bookings/id", vals...) }

// BookingByHotelDatesListKey is the key for the "by_hotel_dates" list, filtered
// by hotel_id, check_in, check_out. Its entries expire after 60s.
func BookingByHotelDatesListKey(parts ...any) string {
	return ListKey("hotel.bookings/$list/by_hotel_dates/", parts...)
}

// BookingByHotelDatesListTTL is the lifetime of that list, in seconds.
const BookingByHotelDatesListTTL = 60

// BookingAvailabilityListKey is the key for the "availability" list, filtered
// by hotel_id, check_in. Its entries expire after 15s.
func BookingAvailabilityListKey(parts ...any) string {
	return ListKey("hotel.bookings/$list/availability/", parts...)
}

// BookingAvailabilityListTTL is the lifetime of that list, in seconds.
const BookingAvailabilityListTTL = 15

// Resources names every cached resource by its collection prefix, so an operator
// tool can enumerate what this schema caches without reading the annotations.
var Resources = []string{
	BookingCollection,
}

// CollectionOf returns the collection prefix a key belongs to, or "" when the key
// belongs to none — useful when reasoning about a keyspace dump.
func CollectionOf(key string) string {
	for _, c := range Resources {
		if strings.HasPrefix(key, c) {
			return c
		}
	}
	return ""
}
