-- Code generated by protoc-gen-store. DO NOT EDIT.
-- versions:
-- 	protoc-gen-store (unknown)
-- 	protoc (unknown)
--
-- database: reserved_db
-- schemas:  public
--
-- Single-file migration: every schema in one transaction. Idempotent — safe to re-apply.
-- annotations: protokit.v1 (unknown), store.v1 (unknown)
--
-- store — https://github.com/the-protobuf-project/store

BEGIN;

-- Schemas
CREATE SCHEMA IF NOT EXISTS "public";

-- Enum types
-- State is the account lifecycle state.
DO $$ BEGIN
    CREATE TYPE "public"."state" AS ENUM ('ACTIVE', 'CLOSED');
EXCEPTION WHEN duplicate_object THEN null;
END $$;

-- Tables (foreign keys are added after every table exists, so creation order
-- never matters — even across schemas or reference cycles).

-- Account is forced onto the reserved table name "user" via a table override, with reserved-word columns and a composite UNIQUE index over them.
CREATE TABLE IF NOT EXISTS "public"."user" (
    -- Unique identifier for the record.
    "id"  CHAR(26)  NOT NULL  PRIMARY KEY,
    -- name: IDENTIFIER → PRIMARY KEY.
    "name"  VARCHAR(255)  NOT NULL  UNIQUE,
    -- order is a reserved word; also carries a single-column index.
    "order"  VARCHAR(255),
    -- select is a reserved word.
    "select"  VARCHAR(255),
    -- state exercises a quoted, schema-qualified enum type reference.
    "state"  "public"."state"
);

-- Indexes
CREATE UNIQUE INDEX IF NOT EXISTS "idx_user_order_select" ON "public"."user" ("order", "select");

-- Documentation
COMMENT ON TABLE "public"."user" IS 'Account is forced onto the reserved table name "user" via a table override, with reserved-word columns and a composite UNIQUE index over them.';
COMMENT ON COLUMN "public"."user"."id" IS 'Unique identifier for the record.';
COMMENT ON COLUMN "public"."user"."name" IS 'name: IDENTIFIER → PRIMARY KEY.';
COMMENT ON COLUMN "public"."user"."order" IS 'order is a reserved word; also carries a single-column index.';
COMMENT ON COLUMN "public"."user"."select" IS 'select is a reserved word.';
COMMENT ON COLUMN "public"."user"."state" IS 'state exercises a quoted, schema-qualified enum type reference.';

COMMIT;
