# store dev tasks — run `just` (or `just --list`) to see recipes.
#
# Common flows:
#   just dev        # build+install the dev plugin, test, regen examples with it
#   just ci         # what CI verifies: lint, build, test (mutates nothing)
#   just regen      # rewrite every committed artifact: stubs, goldens, examples
#
# Requires: go, buf, protoc-gen-go (for `stubs`). Install buf via
# `brew install bufbuild/buf/buf`.
#
# Note: a Homebrew-installed protoc-gen-store can sit earlier on PATH and
# shadow `just install`'s build. The recipes that run the plugin (examples) use
# ./bin via a PATH override so the build under test always wins; `just which`
# shows the resolution order.

# The dev plugin is built into ./bin and that dir is prepended to PATH for buf,
# so a brew/global protoc-gen-store never shadows the build under test.
bin := justfile_directory() / "bin"

# -buildvcs=false stamps the generated-file version banner as "dev" (matching the
# committed goldens/examples) instead of the git tag + "+dirty" working-tree
# version, so regeneration doesn't churn every banner line.
_flags := "-buildvcs=false"

# List recipes (default when you run bare `just`).
_default:
    @just --list

# Build the dev plugin into ./bin (version banner: "dev").
build:
    mkdir -p {{bin}}
    go build {{_flags}} -o {{bin}}/protoc-gen-store ./plugin/cmd/protoc-gen-store

# Install the dev plugin onto your Go bin (GOBIN) for use in other projects.
install:
    go install {{_flags}} ./plugin/cmd/protoc-gen-store

# Show every protoc-gen-store on PATH, in resolution order, with versions.
which:
    @for p in $(which -a protoc-gen-store 2>/dev/null); do printf '%s\t' "$p"; "$p" --version; done || echo "none on PATH (run: just install)"

# Regenerate the option Go stubs for both vocabularies:
#   plugin/pb/storepbv1/*.pb.go            store.v1, this module
#   plugin/entity/pb/entitypbv1/*.pb.go    entity.v1, the neutral vocabulary
stubs:
    buf generate

# Format Go sources in place.
fmt:
    gofmt -w plugin

# Only hand-written sources are touched. Generated output carries the same block
# by its own route and is skipped here: protoc-gen-go copies it from the .proto's
# leading comment into the *.pb.go stubs, and protoc-gen-store renders it from the
# license_header opt (see buf.gen.example.yaml) in each target's comment syntax.
# TestSourceFilesCarryLicenseHeader checks every file either way — `just` shows
# only the last of these lines, so the summary goes last:
#
# Prepend LICENSE.header to any tracked Go/proto source missing it.
headers:
    #!/usr/bin/env bash
    set -euo pipefail
    hdr=$(sed 's|^|// |' LICENSE.header)
    n=0
    for f in $(git ls-files '*.go' '*.proto'); do
        case "$f" in
            */testdata/*|*.pb.go|examples/generated/*) continue ;;
        esac
        head -1 "$f" | grep -q '^// Copyright' && continue
        # cat, not "$(cat)": command substitution eats the trailing newline.
        { printf '%s\n\n' "$hdr"; cat "$f"; } > "$f.tmp" && mv "$f.tmp" "$f"
        n=$((n+1))
    done
    echo "added the licence header to $n file(s)"

# Static checks: gofmt diff, go vet, licence headers, buf lint (mutates nothing).
lint:
    @test -z "$(gofmt -l plugin)" || { echo "unformatted files (run: just fmt):"; gofmt -l plugin; exit 1; }
    go vet ./...
    go test ./plugin/factory/provenance -run TestSourceFilesCarryLicenseHeader
    buf lint

# Run unit + golden tests.
test:
    go test ./...

# Rewrite golden fixtures after an intentional output change, then re-test.
update-goldens:
    go test ./plugin/factory/wire -run TestGolden -update
    go test ./...

# Regenerate examples/ with the freshly-built ./bin plugin (not a global one).
examples: build
    PATH="{{bin}}:$PATH" buf generate --template buf.gen.example.yaml
    @echo "examples regenerated with $(./bin/protoc-gen-store --version)"

# Build the examples module to confirm the generated GORM structs compile.
build-examples:
    cd examples && go build ./...

# Regenerate every committed artifact: stubs, goldens, examples.
regen: stubs update-goldens examples

# Mirror CI's stub gate: regenerate stubs, fail if they differ from committed.
#
# Both output trees are checked. entity's stubs are generated by the same `buf
# generate` but land under plugin/entity/pb/, so gating only plugin/pb/ would let a
# stale entity.v1 stub through — the vocabulary every other plugin agrees on.
verify-stubs:
    buf generate
    @git diff --exit-code -- plugin/pb/ plugin/entity/pb/ || { echo "stubs are stale — commit the regenerated stubs"; exit 1; }

# Verify everything CI checks: lint, stubs current, build, race tests.
ci: lint verify-stubs build
    go test -race ./...

# Regen stubs, install+build the dev plugin, test, regen+compile examples with it.
dev: stubs install build test examples build-examples
    @echo "dev plugin installed, stubs + examples regenerated with the dev build, tests passed"

# Remove build artifacts.
clean:
    rm -rf {{bin}}
