-- Code generated by protoc-gen-store. DO NOT EDIT.
-- versions:
-- 	protoc-gen-store (unknown)
-- 	protoc (unknown)
-- source: outbox.proto
--
-- database: shop_db
-- schema:   shop
--
-- annotations: protokit.v1 (unknown), store.v1 (unknown)
--
-- store — https://github.com/the-protobuf-project/store

CREATE SCHEMA IF NOT EXISTS "shop";

-- Order opts into an outbox. Its ULID primary key is what aggregate_id is typed against, so the companion's foreign reference matches the key strategy rather than assuming a string.
CREATE TABLE "shop"."orders" (
    -- Unique identifier for the record.
    "id"  CHAR(26)  NOT NULL  PRIMARY KEY,
    -- name is the AIP resource name; demoted to a UNIQUE lookup key by the ULID id.
    "name"  VARCHAR(255)  NOT NULL  UNIQUE,
    -- total is the order value.
    "total"  BIGINT  NOT NULL,
    -- Timestamp when the record was created.
    "created_at"  TIMESTAMPTZ  NOT NULL  DEFAULT now(),
    -- Timestamp when the record was last updated.
    "updated_at"  TIMESTAMPTZ  NOT NULL  DEFAULT now()
);

-- Receipt does not opt in, so no receipts_outbox table is generated.
CREATE TABLE "shop"."receipts" (
    -- Unique identifier for the record.
    "id"  CHAR(26)  NOT NULL  PRIMARY KEY,
    -- name: IDENTIFIER → PRIMARY KEY, VARCHAR(255).
    "name"  VARCHAR(255)  NOT NULL  UNIQUE
);

-- Transactional outbox for Order: change events written in the same transaction as the row they describe.
CREATE TABLE "shop"."orders_outbox" (
    -- Surrogate key; ULID so rows sort by insertion order.
    "id"  CHAR(26)  NOT NULL  PRIMARY KEY,
    -- Primary key of the Order row this event describes.
    "aggregate_id"  CHAR(26)  NOT NULL,
    -- What happened, e.g. "Order.created".
    "event_type"  VARCHAR(255)  NOT NULL,
    -- The event body.
    "payload"  JSONB  NOT NULL,
    -- When the event was written.
    "created_at"  TIMESTAMPTZ  NOT NULL  DEFAULT now(),
    -- When a publisher claimed the event; NULL while outstanding.
    "published_at"  TIMESTAMPTZ
);
CREATE INDEX "idx_orders_outbox_unpublished" ON "shop"."orders_outbox" ("published_at", "created_at");
CREATE INDEX "idx_orders_outbox_aggregate" ON "shop"."orders_outbox" ("aggregate_id");


-- Column and table documentation, persisted to the catalog.
COMMENT ON TABLE "shop"."orders" IS 'Order opts into an outbox. Its ULID primary key is what aggregate_id is typed against, so the companion''s foreign reference matches the key strategy rather than assuming a string.';
COMMENT ON COLUMN "shop"."orders"."id" IS 'Unique identifier for the record.';
COMMENT ON COLUMN "shop"."orders"."name" IS 'name is the AIP resource name; demoted to a UNIQUE lookup key by the ULID id.';
COMMENT ON COLUMN "shop"."orders"."total" IS 'total is the order value.';
COMMENT ON COLUMN "shop"."orders"."created_at" IS 'Timestamp when the record was created.';
COMMENT ON COLUMN "shop"."orders"."updated_at" IS 'Timestamp when the record was last updated.';
COMMENT ON TABLE "shop"."receipts" IS 'Receipt does not opt in, so no receipts_outbox table is generated.';
COMMENT ON COLUMN "shop"."receipts"."id" IS 'Unique identifier for the record.';
COMMENT ON COLUMN "shop"."receipts"."name" IS 'name: IDENTIFIER → PRIMARY KEY, VARCHAR(255).';
COMMENT ON TABLE "shop"."orders_outbox" IS 'Transactional outbox for Order: change events written in the same transaction as the row they describe.';
COMMENT ON COLUMN "shop"."orders_outbox"."id" IS 'Surrogate key; ULID so rows sort by insertion order.';
COMMENT ON COLUMN "shop"."orders_outbox"."aggregate_id" IS 'Primary key of the Order row this event describes.';
COMMENT ON COLUMN "shop"."orders_outbox"."event_type" IS 'What happened, e.g. "Order.created".';
COMMENT ON COLUMN "shop"."orders_outbox"."payload" IS 'The event body.';
COMMENT ON COLUMN "shop"."orders_outbox"."created_at" IS 'When the event was written.';
COMMENT ON COLUMN "shop"."orders_outbox"."published_at" IS 'When a publisher claimed the event; NULL while outstanding.';


-- Auto-update triggers keep updated-at columns current on every UPDATE.
CREATE OR REPLACE FUNCTION "shop"."set_updated_at"() RETURNS trigger AS $$
BEGIN
    NEW."updated_at" = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "trg_orders_updated_at" BEFORE UPDATE ON "shop"."orders"
    FOR EACH ROW EXECUTE FUNCTION "shop"."set_updated_at"();
