// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store (unknown)
// 	protoc (unknown)
// source: oneof.proto
//
// database: v1
// schema:   oneof_v1
//
// annotations: entity.v1 (unknown), store.v1 (unknown)
// engine:      protokit (unknown)
//
// store — https://github.com/the-protobuf-project/store

package oneofv1

import (
	"time"
)

// Discriminator for the input oneof of Audio.
type AudioInputCase string

// AudioInputCase values as stored in the database.
const (
	// The audio_data member is set.
	AudioInputCaseAudioData AudioInputCase = "AUDIO_DATA"
	// The upload_path member is set.
	AudioInputCaseUploadPath AudioInputCase = "UPLOAD_PATH"
	// The live_pipeline_file_path member is set.
	AudioInputCaseLivePipelineFilePath AudioInputCase = "LIVE_PIPELINE_FILE_PATH"
)

// Discriminator for the end_form oneof of Booking.
type BookingEndFormCase string

// BookingEndFormCase values as stored in the database.
const (
	// The end member is set.
	BookingEndFormCaseEnd BookingEndFormCase = "END"
	// The duration member is set.
	BookingEndFormCaseDuration BookingEndFormCase = "DURATION"
)

// Audio exercises oneof integrity: the `input` oneof flattens to independent nullable columns, and store adds a generated input_case discriminator enum recording which member is set so the lost exclusivity invariant is observable.
type Audio struct {
	// Unique identifier for the record.
	ID string `gorm:"column:id;primaryKey;not null" json:"id"`
	// Resource name; the AIP identifier.
	Name string `gorm:"column:name;not null;uniqueIndex" json:"name" validate:"required"`
	// Inline audio bytes.
	AudioData []byte `gorm:"column:audio_data" json:"audio_data,omitempty"`
	// Path to a previously uploaded file.
	UploadPath *string `gorm:"column:upload_path" json:"upload_path,omitempty"`
	// Path to a file produced by a live pipeline.
	LivePipelineFilePath *string `gorm:"column:live_pipeline_file_path" json:"live_pipeline_file_path,omitempty"`
	// sample_rate is a plain scalar outside the oneof.
	SampleRate *int32 `gorm:"column:sample_rate" json:"sample_rate,omitempty"`
	// Discriminator: which input oneof member is set (null = none).
	InputCase *AudioInputCase `gorm:"column:input_case;check:chk_audios_input_case,input_case IN ('AUDIO_DATA','UPLOAD_PATH','LIVE_PIPELINE_FILE_PATH')" json:"input_case,omitempty"`
}

func (*Audio) TableName() string { return "oneof_v1.audios" }

// Booking pins the RFC 7953 shape: well-known types as oneof members. These have no struct field of their own — protoc-gen-go puts each behind a wrapper on the oneof's interface field — so the converters must emit `out.EndForm = &Booking_Duration{Duration: …}`, not `out.Duration = …`. The enum arm is here for the same reason: it is a value type, so it guards on the zero rather than on nil. Without converters emitted for this message the flat form compiles here and fails only in a consumer's tree.
type Booking struct {
	// Unique identifier for the record.
	ID string `gorm:"column:id;primaryKey;not null" json:"id"`
	// Resource name; the AIP identifier.
	Name     string     `gorm:"column:name;not null;uniqueIndex" json:"name" validate:"required"`
	End      *time.Time `gorm:"column:end;type:timestamptz" json:"end,omitempty"`
	Duration *string    `gorm:"column:duration" json:"duration,omitempty"`
	// Discriminator: which end_form oneof member is set (null = none).
	EndFormCase *BookingEndFormCase `gorm:"column:end_form_case;check:chk_bookings_end_form_case,end_form_case IN ('END','DURATION')" json:"end_form_case,omitempty"`
}

func (*Booking) TableName() string { return "oneof_v1.bookings" }
