// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store (unknown)
// 	protoc (unknown)
// source: oneof.proto
//
// database: v1
// schema:   oneof_v1
//
// annotations: entity.v1 (unknown), store.v1 (unknown)
// engine:      protokit (unknown)
//
// store — https://github.com/the-protobuf-project/store

package oneofv1

import (
	"time"

	oneofv1 "example.com/test/gen"
	"google.golang.org/protobuf/types/known/durationpb"
	"google.golang.org/protobuf/types/known/timestamppb"
)

// AudioToProto converts the stored row (with its belongs-to associations,
// when preloaded) to its proto message. Nil in, nil out.
func AudioToProto(m *Audio) *oneofv1.Audio {
	if m == nil {
		return nil
	}
	out := &oneofv1.Audio{}
	// not mapped here: audio_data (oneof)
	out.Name = m.Name
	if v := fromPtr(m.UploadPath); v != "" {
		out.Input = &oneofv1.Audio_UploadPath{UploadPath: v}
	}
	if v := fromPtr(m.LivePipelineFilePath); v != "" {
		out.Input = &oneofv1.Audio_LivePipelineFilePath{LivePipelineFilePath: v}
	}
	out.SampleRate = fromPtr(m.SampleRate)
	return out
}

// AudioFromProto maps the proto message's data fields onto a fresh row.
// It never invents keys or relations: primary keys, resource references, and
// sub-row graph wiring stay with the caller. Nil in, nil out.
func AudioFromProto(pb *oneofv1.Audio) *Audio {
	if pb == nil {
		return nil
	}
	m := &Audio{}
	m.Name = pb.GetName()
	m.AudioData = pb.GetAudioData()
	m.UploadPath = toPtr(pb.GetUploadPath())
	m.LivePipelineFilePath = toPtr(pb.GetLivePipelineFilePath())
	m.SampleRate = toPtr(pb.GetSampleRate())
	return m
}

// BookingToProto converts the stored row (with its belongs-to associations,
// when preloaded) to its proto message. Nil in, nil out.
func BookingToProto(m *Booking) *oneofv1.Booking {
	if m == nil {
		return nil
	}
	out := &oneofv1.Booking{}
	out.Name = m.Name
	if v := goToTs(m.End); v != nil {
		out.EndForm = &oneofv1.Booking_End{End: v}
	}
	if v := goToDur(m.Duration); v != nil {
		out.EndForm = &oneofv1.Booking_Duration{Duration: v}
	}
	return out
}

// BookingFromProto maps the proto message's data fields onto a fresh row.
// It never invents keys or relations: primary keys, resource references, and
// sub-row graph wiring stay with the caller. Nil in, nil out.
func BookingFromProto(pb *oneofv1.Booking) *Booking {
	if pb == nil {
		return nil
	}
	m := &Booking{}
	m.Name = pb.GetName()
	m.End = tsToGo(pb.GetEnd())
	m.Duration = durToGo(pb.GetDuration())
	return m
}

// toPtr returns a pointer to v, or nil for the zero value — a nullable column
// stores absence, not the proto zero.
func toPtr[T comparable](v T) *T {
	var zero T
	if v == zero {
		return nil
	}
	return &v
}

// fromPtr dereferences p, returning the zero value for nil.
func fromPtr[T any](p *T) T {
	if p == nil {
		var zero T
		return zero
	}
	return *p
}

// tsToGo maps a proto timestamp onto a nullable TIMESTAMPTZ value.
func tsToGo(ts *timestamppb.Timestamp) *time.Time {
	if ts == nil {
		return nil
	}
	t := ts.AsTime()
	return &t
}

// tsToGoVal maps a proto timestamp onto a NOT NULL TIMESTAMPTZ value.
func tsToGoVal(ts *timestamppb.Timestamp) time.Time {
	if ts == nil {
		return time.Time{}
	}
	return ts.AsTime()
}

// goToTs maps a nullable TIMESTAMPTZ value back onto a proto timestamp.
func goToTs(t *time.Time) *timestamppb.Timestamp {
	if t == nil || t.IsZero() {
		return nil
	}
	return timestamppb.New(*t)
}

// goValToTs maps a NOT NULL TIMESTAMPTZ value back onto a proto timestamp.
func goValToTs(t time.Time) *timestamppb.Timestamp {
	if t.IsZero() {
		return nil
	}
	return timestamppb.New(t)
}

// durToGo maps a proto duration onto a nullable INTERVAL-as-text value
// (Go duration syntax, e.g. "1h30m0s").
func durToGo(d *durationpb.Duration) *string {
	if d == nil {
		return nil
	}
	s := d.AsDuration().String()
	return &s
}

// goToDur parses a stored Go duration string back onto a proto duration.
func goToDur(s *string) *durationpb.Duration {
	if s == nil || *s == "" {
		return nil
	}
	d, err := time.ParseDuration(*s)
	if err != nil {
		return nil
	}
	return durationpb.New(d)
}
