// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm (unknown)
// 	protoc (unknown)
// source: order.proto
//
// database: commerce
// schema:   shop_order_v1
//
// orm — https://github.com/the-protobuf-project/orm

package shoporderv1

// Status enumerates order fulfillment states.
type Status string

// Status values as stored in the database.
const (
	StatusShipped   Status = "SHIPPED"
	StatusDelivered Status = "DELIVERED"
)

// Money is the order-side resource sharing the simple name "Money" with the cart-side one. See cart.proto for how each target renders the collision.
type Money struct {
	// Unique identifier for the record.
	ID string `gorm:"column:id;type:char(26);primaryKey;not null" json:"id"`
	// Resource name; the AIP identifier.
	Name string `gorm:"column:name;type:varchar(255);not null;uniqueIndex" json:"name" validate:"required"`
	// Amount in minor units.
	Amount int64 `gorm:"column:amount;not null" json:"amount" validate:"required"`
	// Status is an order-side enum whose simple name collides with cart.Status.
	Status Status `gorm:"column:status;not null;default:'SHIPPED';check:chk_moneys_status,status IN ('SHIPPED','DELIVERED')" json:"status" validate:"required"`
}

func (*Money) TableName() string { return "shop_order_v1.moneys" }
