// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store (unknown)
// 	protoc (unknown)
// source: versionedpkg.proto
//
// database: v1
// schema:   resource_v1
//
// GORM adapters composing the generated models, stores, converters, and filterx specs.
// annotations: entity.v1 (unknown), store.v1 (unknown)
// engine:      protokit (unknown)
//
// store — https://github.com/the-protobuf-project/store

package resourcev1

import (
	"context"
	resourcev1 "example.com/test/gen"
	"example.com/test/gen/repox"
	"example.com/test/gormdb/filterx"
	resourcev1gorm "example.com/test/gormdb/v1/resourcev1"
	"google.golang.org/protobuf/proto"
	"gorm.io/gorm"
)

// GormEventRepository is the GORM adapter of EventRepository: flat
// CRUD over the generated model, store, converters, and filterx spec. Exported
// fields and helpers are the Tier-2 seam — embed it and override whole methods
// for behavior the schema cannot express; generated methods only call private
// helpers, never the public interface, so overrides never re-enter generated
// code.
type GormEventRepository struct {
	DB    *gorm.DB
	Hooks EventHooks
	// ListOverrides substitute the generated dispatch for single filter fields
	// (e.g. a derived state computed via subqueries).
	ListOverrides map[string]filterx.SQLHandler
}

// NewGormEventRepository returns the GORM adapter bound to db.
func NewGormEventRepository(db *gorm.DB) *GormEventRepository {
	return &GormEventRepository{DB: db}
}

// Create persists in and returns the stored record.
func (r *GormEventRepository) Create(ctx context.Context, in *resourcev1.Event) (*resourcev1.Event, error) {
	id := repox.NewULID()
	if in.GetName() != "" {
		ids, err := repox.SplitName(in.GetName(), "events")
		if err != nil {
			return nil, err
		}
		id = ids[len(ids)-1]
	}
	in = proto.Clone(in).(*resourcev1.Event)
	in.Name = FormatEventName(id)
	if h := r.Hooks.BeforeCreate; h != nil {
		if err := h(ctx, in); err != nil {
			return nil, err
		}
	}
	m := resourcev1gorm.EventFromProto(in)
	m.ID = id
	m.Name = in.GetName()
	if err := r.DB.Transaction(func(tx *gorm.DB) error {
		if v := in.GetWindow(); v != nil {
			vo := resourcev1gorm.WindowFromProto(v)
			vo.ID = repox.NewULID()
			if err := tx.WithContext(ctx).Create(vo).Error; err != nil {
				return err
			}
			m.WindowID = repox.Ptr(vo.ID)
		}
		return resourcev1gorm.NewEventStore(tx).Create(ctx, m)
	}); err != nil {
		return nil, repox.MapGormErr(err)
	}
	return r.get(ctx, id)
}

// Get returns the record addressed by its resource name.
func (r *GormEventRepository) Get(ctx context.Context, name string) (*resourcev1.Event, error) {
	ids, err := repox.SplitName(name, "events")
	if err != nil {
		return nil, err
	}
	return r.get(ctx, ids[len(ids)-1])
}

// get loads by surrogate key — the private read every generated method re-reads
// through, so Tier-2 overrides of Get never re-enter generated writes.
func (r *GormEventRepository) get(ctx context.Context, id string) (*resourcev1.Event, error) {
	var m resourcev1gorm.Event
	if err := r.DB.WithContext(ctx).Preload("Window").First(&m, "id = ?", id).Error; err != nil {
		return nil, repox.MapGormErr(err)
	}
	return r.toProto(ctx, &m)
}

// toProto converts a loaded row, decorating reference names and running the
// AfterRead hook.
func (r *GormEventRepository) toProto(ctx context.Context, m *resourcev1gorm.Event) (*resourcev1.Event, error) {
	out := resourcev1gorm.EventToProto(m)
	if h := r.Hooks.AfterRead; h != nil {
		if err := h(ctx, out); err != nil {
			return nil, err
		}
	}
	return out, nil
}

// List returns one page of records.
func (r *GormEventRepository) List(ctx context.Context, in repox.ListInput) ([]*resourcev1.Event, string, error) {
	return r.list(ctx, r.DB, in)
}

func (r *GormEventRepository) list(ctx context.Context, scope *gorm.DB, in repox.ListInput) ([]*resourcev1.Event, string, error) {
	conds, err := filterx.Parse(in.Filter)
	if err != nil {
		return nil, "", repox.MapFilterxErr(err)
	}
	eng := filterx.Gorm[resourcev1gorm.Event](resourcev1gorm.EventFilterSpec)
	for f, h := range r.ListOverrides {
		eng.Override(f, h)
	}
	rows, next, err := eng.List(ctx, scope.Preload("Window"), filterx.ListInput{
		PageSize:  in.PageSize,
		PageToken: in.PageToken,
		OrderBy:   in.OrderBy,
		Filter:    conds,
	})
	if err != nil {
		return nil, "", repox.MapFilterxErr(err)
	}
	items := make([]*resourcev1.Event, 0, len(rows))
	for i := range rows {
		out, err := r.toProto(ctx, &rows[i])
		if err != nil {
			return nil, "", err
		}
		items = append(items, out)
	}
	return items, next, nil
}

// Update persists the masked fields of in; an empty mask replaces every
// mutable field. The write happens in one transaction guarded by in.Etag.
func (r *GormEventRepository) Update(ctx context.Context, in *resourcev1.Event, paths []string) (*resourcev1.Event, error) {
	ids, err := repox.SplitName(in.GetName(), "events")
	if err != nil {
		return nil, err
	}
	id := ids[len(ids)-1]
	err = r.DB.Transaction(func(tx *gorm.DB) error {
		var existing resourcev1gorm.Event
		if err := tx.WithContext(ctx).Preload("Window").First(&existing, "id = ?", id).Error; err != nil {
			return err
		}
		var staleWindow string
		existingPB := resourcev1gorm.EventToProto(&existing)
		merged := proto.Clone(existingPB).(*resourcev1.Event)
		applyEventMask(merged, in, paths)
		if h := r.Hooks.BeforeUpdate; h != nil {
			if err := h(ctx, existingPB, merged, paths); err != nil {
				return err
			}
		}
		next := resourcev1gorm.EventFromProto(merged)
		_ = next
		existing.Name = next.Name
		existing.DisplayName = next.DisplayName
		existing.State = next.State
		if repox.GroupTouched(paths, "window") {
			if existing.WindowID != nil {
				staleWindow = *existing.WindowID
			}
			existing.WindowID = nil
			if v := merged.GetWindow(); v != nil {
				vo := resourcev1gorm.WindowFromProto(v)
				vo.ID = repox.NewULID()
				if err := tx.WithContext(ctx).Create(vo).Error; err != nil {
					return err
				}
				existing.WindowID = repox.Ptr(vo.ID)
			}
		}
		if err := resourcev1gorm.NewEventStore(tx).Update(ctx, &existing); err != nil {
			return err
		}
		if staleWindow != "" {
			if err := tx.WithContext(ctx).Delete(&resourcev1gorm.Window{}, "id = ?", staleWindow).Error; err != nil {
				return err
			}
		}
		return nil
	})
	if err != nil {
		return nil, repox.MapGormErr(err)
	}
	return r.get(ctx, id)
}

// Delete removes the record addressed by its resource name.
func (r *GormEventRepository) Delete(ctx context.Context, name string) error {
	ids, err := repox.SplitName(name, "events")
	if err != nil {
		return err
	}
	if h := r.Hooks.BeforeDelete; h != nil {
		if err := h(ctx, name); err != nil {
			return err
		}
	}
	id := ids[len(ids)-1]
	var existing resourcev1gorm.Event
	if err := r.DB.WithContext(ctx).First(&existing, "id = ?", id).Error; err != nil {
		return repox.MapGormErr(err)
	}
	return repox.MapGormErr(r.DB.Transaction(func(tx *gorm.DB) error {
		if err := resourcev1gorm.NewEventStore(tx).DeleteByID(ctx, id); err != nil {
			return err
		}
		if existing.WindowID != nil {
			if err := tx.WithContext(ctx).Delete(&resourcev1gorm.Window{}, "id = ?", *existing.WindowID).Error; err != nil {
				return err
			}
		}
		return nil
	}))
}

// Compile-time proof the adapter satisfies the interface.
var _ EventRepository = (*GormEventRepository)(nil)
