// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store (unknown)
// 	protoc (unknown)
// source: versionedpkg.proto
//
// database: v1
// schema:   resource_v1
//
// Proto-facing repository interfaces; adapters compose the generated gorm and GraphQL outputs.
// annotations: entity.v1 (unknown), store.v1 (unknown)
// engine:      protokit (unknown)
//
// store — https://github.com/the-protobuf-project/store

package resourcev1

import (
	"context"
	resourcev1 "example.com/test/gen"
	"example.com/test/gen/repox"
	"example.com/test/gormdb/filterx"
	"gorm.io/gorm"
)

// EventRepository is the provider-agnostic persistence surface for
// Event (events/{event}): full-message writes, AIP-160/AIP-132 lists with
// opaque page tokens, field-mask updates, and etag optimistic concurrency.
type EventRepository interface {
	// Create persists m and returns the stored record.
	Create(ctx context.Context, m *resourcev1.Event) (*resourcev1.Event, error)
	// Get returns the record addressed by its resource name, or
	// repox.ErrNotFound.
	Get(ctx context.Context, name string) (*resourcev1.Event, error)
	// List returns one page of records.
	List(ctx context.Context, in repox.ListInput) ([]*resourcev1.Event, string, error)
	// Update persists the masked fields of m; an empty mask replaces every
	// mutable field. m.Etag, when set, guards against concurrent writes
	// (repox.ErrConflict).
	Update(ctx context.Context, m *resourcev1.Event, paths []string) (*resourcev1.Event, error)
	// Delete removes the record addressed by its resource name.
	Delete(ctx context.Context, name string) error
}

// EventHooks lets custom logic run inside the generated Event
// adapters without editing them: normalization/derivation before writes,
// derived fields after reads, and guards before deletes. Nil funcs are skipped.
type EventHooks struct {
	// BeforeCreate runs after name/id resolution, before the row is written.
	BeforeCreate func(ctx context.Context, m *resourcev1.Event) error
	// AfterRead runs on every record a read returns (Get, List, and the
	// re-reads writes return).
	AfterRead func(ctx context.Context, m *resourcev1.Event) error
	// BeforeUpdate runs after the mask is applied to the merged record,
	// before it is written.
	BeforeUpdate func(ctx context.Context, existing, merged *resourcev1.Event, paths []string) error
	// BeforeDelete runs before the row is removed; returning an error vetoes.
	BeforeDelete func(ctx context.Context, name string) error
}

// Repositories bundles this schema's repository surfaces behind one factory.
type Repositories struct {
	Events EventRepository
}

// options collects the per-resource customizations the factories thread into
// the adapters they build.
type options struct {
	eventHooks     EventHooks
	eventOverrides map[string]filterx.SQLHandler
}

// Option customizes the adapters a factory builds.
type Option func(*options)

// WithEventHooks installs h on the Event adapters.
func WithEventHooks(h EventHooks) Option {
	return func(o *options) { o.eventHooks = h }
}

// WithEventListOverride substitutes the generated filter dispatch for one
// Event filter field (e.g. a derived state computed via subqueries).
func WithEventListOverride(field string, h filterx.SQLHandler) Option {
	return func(o *options) {
		if o.eventOverrides == nil {
			o.eventOverrides = map[string]filterx.SQLHandler{}
		}
		o.eventOverrides[field] = h
	}
}

// New picks the adapter set for the live handle in conn.
func New(conn repox.Conn, opts ...Option) Repositories {
	return NewGorm(conn.Gorm, opts...)
}

// NewGorm builds the GORM adapter set over db.
func NewGorm(db *gorm.DB, opts ...Option) Repositories {
	var o options
	for _, opt := range opts {
		opt(&o)
	}
	return Repositories{
		Events: &GormEventRepository{DB: db, Hooks: o.eventHooks, ListOverrides: o.eventOverrides},
	}
}
