// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store (unknown)
// 	protoc (unknown)
// source: inventory.proto
//
// database: bookstore_db
// schema:   inventory
//
// store — https://github.com/the-protobuf-project/store

package inventory

import (
	"context"

	"example.com/test/gen/gormx"
	"gorm.io/gorm"
)

// ShelfStore provides typed CRUD access to Shelf records.
// Shelf groups books physically. The resource's `plural` fixes the irregular plural ("shelfs" → "shelves") — no table name override needed.
type ShelfStore struct {
	DB *gorm.DB
	// Telemetry observes every operation; nil is a no-op. Wire the generated
	// adapter: NewShelfStore(db).WithTelemetry(telemetry.New(o)).
	Telemetry gormx.Telemetry
}

// Compile-time proof that ShelfStore satisfies the generic gormx.Store, so the
// generic engine can drive it alongside the typed finders below.
var _ gormx.Store[Shelf] = (*ShelfStore)(nil)

// NewShelfStore returns a ShelfStore backed by db.
func NewShelfStore(db *gorm.DB) *ShelfStore { return &ShelfStore{DB: db} }

// WithTelemetry sets the store's Telemetry and returns the store for chaining.
func (s *ShelfStore) WithTelemetry(t gormx.Telemetry) *ShelfStore {
	s.Telemetry = t
	return s
}

// Create inserts m.
func (s *ShelfStore) Create(ctx context.Context, m *Shelf) error {
	return s.DB.WithContext(ctx).Create(m).Error
}

// List returns the Shelf records matching opts.
func (s *ShelfStore) List(ctx context.Context, opts gormx.ListOptions) ([]Shelf, error) {
	var out []Shelf
	if err := opts.Apply(s.DB.WithContext(ctx)).Find(&out).Error; err != nil {
		return nil, err
	}
	return out, nil
}

// Count returns the number of Shelf records matching opts.Where
// (pagination and ordering are ignored).
func (s *ShelfStore) Count(ctx context.Context, opts gormx.ListOptions) (int64, error) {
	var n int64
	db := s.DB.WithContext(ctx).Model(&Shelf{})
	if opts.Where != nil {
		db = db.Where(opts.Where, opts.Args...)
	}
	if err := db.Count(&n).Error; err != nil {
		return 0, err
	}
	return n, nil
}

// Update persists every field of m, which must carry its primary key.
func (s *ShelfStore) Update(ctx context.Context, m *Shelf) error {
	return s.DB.WithContext(ctx).Save(m).Error
}

// GetByID fetches the Shelf with the given primary key.
func (s *ShelfStore) GetByID(ctx context.Context, id string) (*Shelf, error) {
	var m Shelf
	if err := s.DB.WithContext(ctx).First(&m, "id = ?", id).Error; err != nil {
		return nil, err
	}
	return &m, nil
}

// DeleteByID removes the Shelf with the given primary key.
func (s *ShelfStore) DeleteByID(ctx context.Context, id string) error {
	return s.DB.WithContext(ctx).Delete(&Shelf{}, "id = ?", id).Error
}

// GetByName fetches the Shelf with the given name (a unique column).
func (s *ShelfStore) GetByName(ctx context.Context, v string) (*Shelf, error) {
	var m Shelf
	if err := s.DB.WithContext(ctx).First(&m, "name = ?", v).Error; err != nil {
		return nil, err
	}
	return &m, nil
}
