// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store (unknown)
// 	protoc (unknown)
// source: inventory.proto
//
// database: bookstore_db
// schema:   inventory
//
// annotations: protokit.v1 (unknown), store.v1 (unknown)
// runtime:     gorm.io/gorm
//
// store — https://github.com/the-protobuf-project/store

package inventory

import (
	"context"

	"example.com/test/gen/gormx"
	"gorm.io/gorm"
)

// ShelfStoreIface is the full data-access surface of Shelf: everything
// ShelfStore does, as an interface.
//
// It exists so a decorator — caching, tracing, retries, a test double — can be
// written in its own package against this contract, without that package needing
// to edit anything in this tree. Embed it, override the methods you care about,
// and delegate the rest:
//
//	type cachedShelfStore struct {
//		ShelfStoreIface
//		cache Cache
//	}
//
// Construction is deliberately absent. NewShelfStore returns the concrete
// *ShelfStore, and WithTelemetry is a chainable setter that also returns it, so
// a caller keeps the full type at the point of wiring and narrows to this
// interface at the point of use — which is the direction that stays useful when
// a decorator is added later.
type ShelfStoreIface interface {
	Create(ctx context.Context, m *Shelf) error
	List(ctx context.Context, opts gormx.ListOptions) ([]Shelf, error)
	Count(ctx context.Context, opts gormx.ListOptions) (int64, error)
	Update(ctx context.Context, m *Shelf) error
	GetByID(ctx context.Context, id string) (*Shelf, error)
	DeleteByID(ctx context.Context, id string) error
	GetByName(ctx context.Context, v string) (*Shelf, error)
}

// ShelfStore provides typed CRUD access to Shelf records.
// Shelf groups books physically. The resource's `plural` fixes the irregular plural ("shelfs" → "shelves") — no table name override needed.
type ShelfStore struct {
	DB *gorm.DB
	// Telemetry observes every operation; nil is a no-op. Wire the generated
	// adapter: NewShelfStore(db).WithTelemetry(telemetry.New(o)).
	Telemetry gormx.Telemetry
}

// Compile-time proof that ShelfStore implements its own interface. Without it a
// signature could drift from ShelfStoreIface and only break in whichever downstream
// package decorates it.
var _ ShelfStoreIface = (*ShelfStore)(nil)

// Compile-time proof that ShelfStore satisfies the generic gormx.Store, so the
// generic engine can drive it alongside the typed finders below.
var _ gormx.Store[Shelf] = (*ShelfStore)(nil)

// NewShelfStore returns a ShelfStore backed by db.
func NewShelfStore(db *gorm.DB) *ShelfStore { return &ShelfStore{DB: db} }

// WithTelemetry sets the store's Telemetry and returns the store for chaining.
func (s *ShelfStore) WithTelemetry(t gormx.Telemetry) *ShelfStore {
	s.Telemetry = t
	return s
}

// Create inserts m.
func (s *ShelfStore) Create(ctx context.Context, m *Shelf) error {
	return s.DB.WithContext(ctx).Create(m).Error
}

// List returns the Shelf records matching opts.
func (s *ShelfStore) List(ctx context.Context, opts gormx.ListOptions) ([]Shelf, error) {
	var out []Shelf
	if err := opts.Apply(s.DB.WithContext(ctx)).Find(&out).Error; err != nil {
		return nil, err
	}
	return out, nil
}

// Count returns the number of Shelf records matching opts.Where
// (pagination and ordering are ignored).
func (s *ShelfStore) Count(ctx context.Context, opts gormx.ListOptions) (int64, error) {
	var n int64
	db := s.DB.WithContext(ctx).Model(&Shelf{})
	if opts.Where != nil {
		db = db.Where(opts.Where, opts.Args...)
	}
	if err := db.Count(&n).Error; err != nil {
		return 0, err
	}
	return n, nil
}

// Update persists every field of m, which must carry its primary key.
func (s *ShelfStore) Update(ctx context.Context, m *Shelf) error {
	return s.DB.WithContext(ctx).Save(m).Error
}

// GetByID fetches the Shelf with the given primary key.
func (s *ShelfStore) GetByID(ctx context.Context, id string) (*Shelf, error) {
	var m Shelf
	if err := s.DB.WithContext(ctx).First(&m, "id = ?", id).Error; err != nil {
		return nil, err
	}
	return &m, nil
}

// DeleteByID removes the Shelf with the given primary key.
func (s *ShelfStore) DeleteByID(ctx context.Context, id string) error {
	return s.DB.WithContext(ctx).Delete(&Shelf{}, "id = ?", id).Error
}

// GetByName fetches the Shelf with the given name (a unique column).
func (s *ShelfStore) GetByName(ctx context.Context, v string) (*Shelf, error) {
	var m Shelf
	if err := s.DB.WithContext(ctx).First(&m, "name = ?", v).Error; err != nil {
		return nil, err
	}
	return &m, nil
}
