-- Code generated by protoc-gen-store. DO NOT EDIT.
-- versions:
-- 	protoc-gen-store (unknown)
-- 	protoc (unknown)
-- source: vocabularies.proto
--
-- database: vocab_db
-- schema:   store
--
-- annotations: protokit.v1 (unknown), store.v1 (unknown)
--
-- store — https://github.com/the-protobuf-project/store

CREATE SCHEMA IF NOT EXISTS "store";

-- Widget takes its table name and timestamps from protokit.v1.
CREATE TABLE "store"."widgets" (
    -- Unique identifier for the record.
    "id"  CHAR(26)  NOT NULL  PRIMARY KEY,
    -- name: IDENTIFIER → PRIMARY KEY.
    "name"  VARCHAR(255)  NOT NULL  UNIQUE,
    -- label is renamed by protokit.v1 and sized by store.v1 — the two modules annotating one field without either reaching into the other's half.
    "display_label"  VARCHAR(120),
    -- note carries storage options only; its column name is the proto field name.
    "note"  TEXT,
    -- Timestamp when the record was created.
    "created_at"  TIMESTAMPTZ  NOT NULL  DEFAULT now(),
    -- Timestamp when the record was last updated.
    "updated_at"  TIMESTAMPTZ  NOT NULL  DEFAULT now()
);


-- Column and table documentation, persisted to the catalog.
COMMENT ON TABLE "store"."widgets" IS 'Widget takes its table name and timestamps from protokit.v1.';
COMMENT ON COLUMN "store"."widgets"."id" IS 'Unique identifier for the record.';
COMMENT ON COLUMN "store"."widgets"."name" IS 'name: IDENTIFIER → PRIMARY KEY.';
COMMENT ON COLUMN "store"."widgets"."display_label" IS 'label is renamed by protokit.v1 and sized by store.v1 — the two modules annotating one field without either reaching into the other''s half.';
COMMENT ON COLUMN "store"."widgets"."note" IS 'note carries storage options only; its column name is the proto field name.';
COMMENT ON COLUMN "store"."widgets"."created_at" IS 'Timestamp when the record was created.';
COMMENT ON COLUMN "store"."widgets"."updated_at" IS 'Timestamp when the record was last updated.';


-- Auto-update triggers keep updated-at columns current on every UPDATE.
CREATE OR REPLACE FUNCTION "store"."set_updated_at"() RETURNS trigger AS $$
BEGIN
    NEW."updated_at" = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "trg_widgets_updated_at" BEFORE UPDATE ON "store"."widgets"
    FOR EACH ROW EXECUTE FUNCTION "store"."set_updated_at"();
