// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store (unknown)
// 	protoc (unknown)
// source: repository.proto
//
// database: v1
// schema:   org_v1
//
// Field-mask merge functions shared by every adapter of this schema.
// annotations: entity.v1 (unknown), store.v1 (unknown)
// engine:      protokit (unknown)
//
// store — https://github.com/the-protobuf-project/store

package orgv1

import (
	orgv1 "example.com/test/gen"
	"example.com/test/gen/repox"
)

// applyMemberMask merges the masked fields of in onto merged. An empty
// mask replaces every mutable field; identity, parentage, timestamps, and etag
// are repository-managed and never masked. Message-typed fields are replaced
// wholesale when the mask touches them or any of their subpaths, and a oneof is
// replaced whole when the mask touches any of its arms — it holds at most one.
func applyMemberMask(merged, in *orgv1.Member, paths []string) {
	if repox.InMask(paths, "name") {
		merged.Name = in.GetName()
	}
	if repox.InMask(paths, "email") {
		merged.Email = in.GetEmail()
	}
	if repox.InMask(paths, "user") {
		merged.User = in.GetUser()
	}
	if repox.InMask(paths, "inviter") {
		merged.Inviter = in.GetInviter()
	}
	if repox.InMask(paths, "role") {
		merged.Role = in.GetRole()
	}
	if repox.GroupTouched(paths, "duration") || repox.GroupTouched(paths, "window") || repox.GroupTouched(paths, "date_range") {
		merged.Span = in.Span
	}
}

// applyOrganisationMask merges the masked fields of in onto merged. An empty
// mask replaces every mutable field; identity, parentage, timestamps, and etag
// are repository-managed and never masked. Message-typed fields are replaced
// wholesale when the mask touches them or any of their subpaths, and a oneof is
// replaced whole when the mask touches any of its arms — it holds at most one.
func applyOrganisationMask(merged, in *orgv1.Organisation, paths []string) {
	if repox.InMask(paths, "name") {
		merged.Name = in.GetName()
	}
	if repox.InMask(paths, "display_name") {
		merged.DisplayName = in.GetDisplayName()
	}
	if repox.InMask(paths, "slug") {
		merged.Slug = in.GetSlug()
	}
	if repox.GroupTouched(paths, "settings") {
		merged.Settings = in.GetSettings()
	}
	if repox.GroupTouched(paths, "hq") {
		merged.Hq = in.GetHq()
	}
}

// applyUserMask merges the masked fields of in onto merged. An empty
// mask replaces every mutable field; identity, parentage, timestamps, and etag
// are repository-managed and never masked. Message-typed fields are replaced
// wholesale when the mask touches them or any of their subpaths, and a oneof is
// replaced whole when the mask touches any of its arms — it holds at most one.
func applyUserMask(merged, in *orgv1.User, paths []string) {
	if repox.InMask(paths, "name") {
		merged.Name = in.GetName()
	}
	if repox.InMask(paths, "display_name") {
		merged.DisplayName = in.GetDisplayName()
	}
}
