// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store (unknown)
// 	protoc (unknown)
// source: repository.proto
//
// database: v1
// schema:   org_v1
//
// AIP resource-name codecs for this schema's repositories.
//
// store — https://github.com/the-protobuf-project/store

package orgv1

import (
	"example.com/test/gen/repox"
)

// FormatMemberName builds "organisations/{organisation}/members/{member}" from bare ids.
func FormatMemberName(organisation, member string) string {
	return "organisations" + "/" + organisation + "/" + "members" + "/" + member
}

// ParseMemberName splits a "organisations/{organisation}/members/{member}" resource name into its bare ids,
// rejecting other shapes with repox.ErrInvalidArgument.
func ParseMemberName(name string) (organisation, member string, err error) {
	ids, err := repox.SplitName(name, "organisations", "members")
	if err != nil {
		return
	}
	organisation = ids[0]
	member = ids[1]
	return
}

// FormatOrganisationName builds "organisations/{organisation}" from bare ids.
func FormatOrganisationName(organisation string) string {
	return "organisations" + "/" + organisation
}

// ParseOrganisationName splits a "organisations/{organisation}" resource name into its bare ids,
// rejecting other shapes with repox.ErrInvalidArgument.
func ParseOrganisationName(name string) (organisation string, err error) {
	ids, err := repox.SplitName(name, "organisations")
	if err != nil {
		return
	}
	organisation = ids[0]
	return
}

// FormatUserName builds "users/{user}" from bare ids.
func FormatUserName(user string) string {
	return "users" + "/" + user
}

// ParseUserName splits a "users/{user}" resource name into its bare ids,
// rejecting other shapes with repox.ErrInvalidArgument.
func ParseUserName(name string) (user string, err error) {
	ids, err := repox.SplitName(name, "users")
	if err != nil {
		return
	}
	user = ids[0]
	return
}
