// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store (unknown)
// 	protoc (unknown)
// source: repository.proto
//
// database: v1
// schema:   org_v1
//
// Proto-facing repository interfaces; adapters compose the generated gorm and GraphQL outputs.
// annotations: protokit.v1 (unknown), store.v1 (unknown)
//
// store — https://github.com/the-protobuf-project/store

package orgv1

import (
	"context"
	"example.com/test/gen"
	"example.com/test/gen/repox"
	"example.com/test/genql"
	"example.com/test/gormdb/filterx"
	"gorm.io/gorm"
)

// MemberRepository is the provider-agnostic persistence surface for
// Member (organisations/{organisation}/members/{member}): full-message writes, AIP-160/AIP-132 lists with
// opaque page tokens, field-mask updates, and etag optimistic concurrency.
type MemberRepository interface {
	// Create persists m under parent and returns the stored record.
	Create(ctx context.Context, parent string, m *gen.Member) (*gen.Member, error)
	// Get returns the record addressed by its resource name, or
	// repox.ErrNotFound.
	Get(ctx context.Context, name string) (*gen.Member, error)
	// List returns one page of records under parent.
	List(ctx context.Context, parent string, in repox.ListInput) ([]*gen.Member, string, error)
	// Update persists the masked fields of m; an empty mask replaces every
	// mutable field. m.Etag, when set, guards against concurrent writes
	// (repox.ErrConflict).
	Update(ctx context.Context, m *gen.Member, paths []string) (*gen.Member, error)
	// Delete removes the record addressed by its resource name.
	Delete(ctx context.Context, name string) error
}

// MemberHooks lets custom logic run inside the generated Member
// adapters without editing them: normalization/derivation before writes,
// derived fields after reads, and guards before deletes. Nil funcs are skipped.
type MemberHooks struct {
	// BeforeCreate runs after name/id resolution, before the row is written.
	BeforeCreate func(ctx context.Context, m *gen.Member) error
	// AfterRead runs on every record a read returns (Get, List, and the
	// re-reads writes return).
	AfterRead func(ctx context.Context, m *gen.Member) error
	// BeforeUpdate runs after the mask is applied to the merged record,
	// before it is written.
	BeforeUpdate func(ctx context.Context, existing, merged *gen.Member, paths []string) error
	// BeforeDelete runs before the row is removed; returning an error vetoes.
	BeforeDelete func(ctx context.Context, name string) error
}

// OrganisationRepository is the provider-agnostic persistence surface for
// Organisation (organisations/{organisation}): full-message writes, AIP-160/AIP-132 lists with
// opaque page tokens, field-mask updates, and etag optimistic concurrency.
type OrganisationRepository interface {
	// Create persists m and returns the stored record.
	Create(ctx context.Context, m *gen.Organisation) (*gen.Organisation, error)
	// Get returns the record addressed by its resource name, or
	// repox.ErrNotFound.
	Get(ctx context.Context, name string) (*gen.Organisation, error)
	// List returns one page of records.
	List(ctx context.Context, in repox.ListInput) ([]*gen.Organisation, string, error)
	// Update persists the masked fields of m; an empty mask replaces every
	// mutable field. m.Etag, when set, guards against concurrent writes
	// (repox.ErrConflict).
	Update(ctx context.Context, m *gen.Organisation, paths []string) (*gen.Organisation, error)
	// Delete removes the record addressed by its resource name.
	Delete(ctx context.Context, name string) error
}

// OrganisationHooks lets custom logic run inside the generated Organisation
// adapters without editing them: normalization/derivation before writes,
// derived fields after reads, and guards before deletes. Nil funcs are skipped.
type OrganisationHooks struct {
	// BeforeCreate runs after name/id resolution, before the row is written.
	BeforeCreate func(ctx context.Context, m *gen.Organisation) error
	// AfterRead runs on every record a read returns (Get, List, and the
	// re-reads writes return).
	AfterRead func(ctx context.Context, m *gen.Organisation) error
	// BeforeUpdate runs after the mask is applied to the merged record,
	// before it is written.
	BeforeUpdate func(ctx context.Context, existing, merged *gen.Organisation, paths []string) error
	// BeforeDelete runs before the row is removed; returning an error vetoes.
	BeforeDelete func(ctx context.Context, name string) error
}

// UserRepository is the provider-agnostic persistence surface for
// User (users/{user}): full-message writes, AIP-160/AIP-132 lists with
// opaque page tokens, field-mask updates, and etag optimistic concurrency.
type UserRepository interface {
	// Create persists m and returns the stored record.
	Create(ctx context.Context, m *gen.User) (*gen.User, error)
	// Get returns the record addressed by its resource name, or
	// repox.ErrNotFound.
	Get(ctx context.Context, name string) (*gen.User, error)
	// List returns one page of records.
	List(ctx context.Context, in repox.ListInput) ([]*gen.User, string, error)
	// Update persists the masked fields of m; an empty mask replaces every
	// mutable field. m.Etag, when set, guards against concurrent writes
	// (repox.ErrConflict).
	Update(ctx context.Context, m *gen.User, paths []string) (*gen.User, error)
	// Delete removes the record addressed by its resource name.
	Delete(ctx context.Context, name string) error
}

// UserHooks lets custom logic run inside the generated User
// adapters without editing them: normalization/derivation before writes,
// derived fields after reads, and guards before deletes. Nil funcs are skipped.
type UserHooks struct {
	// BeforeCreate runs after name/id resolution, before the row is written.
	BeforeCreate func(ctx context.Context, m *gen.User) error
	// AfterRead runs on every record a read returns (Get, List, and the
	// re-reads writes return).
	AfterRead func(ctx context.Context, m *gen.User) error
	// BeforeUpdate runs after the mask is applied to the merged record,
	// before it is written.
	BeforeUpdate func(ctx context.Context, existing, merged *gen.User, paths []string) error
	// BeforeDelete runs before the row is removed; returning an error vetoes.
	BeforeDelete func(ctx context.Context, name string) error
}

// Repositories bundles this schema's repository surfaces behind one factory.
type Repositories struct {
	Members       MemberRepository
	Organisations OrganisationRepository
	Users         UserRepository
}

// options collects the per-resource customizations the factories thread into
// the adapters they build.
type options struct {
	memberHooks              MemberHooks
	memberOverrides          map[string]filterx.SQLHandler
	organisationHooks        OrganisationHooks
	organisationOverrides    map[string]filterx.SQLHandler
	userHooks                UserHooks
	userOverrides            map[string]filterx.SQLHandler
	memberGQLOverrides       map[string]filterx.GraphQLHandler
	organisationGQLOverrides map[string]filterx.GraphQLHandler
	userGQLOverrides         map[string]filterx.GraphQLHandler
}

// Option customizes the adapters a factory builds.
type Option func(*options)

// WithMemberHooks installs h on the Member adapters.
func WithMemberHooks(h MemberHooks) Option {
	return func(o *options) { o.memberHooks = h }
}

// WithMemberListOverride substitutes the generated filter dispatch for one
// Member filter field (e.g. a derived state computed via subqueries).
func WithMemberListOverride(field string, h filterx.SQLHandler) Option {
	return func(o *options) {
		if o.memberOverrides == nil {
			o.memberOverrides = map[string]filterx.SQLHandler{}
		}
		o.memberOverrides[field] = h
	}
}

// WithOrganisationHooks installs h on the Organisation adapters.
func WithOrganisationHooks(h OrganisationHooks) Option {
	return func(o *options) { o.organisationHooks = h }
}

// WithOrganisationListOverride substitutes the generated filter dispatch for one
// Organisation filter field (e.g. a derived state computed via subqueries).
func WithOrganisationListOverride(field string, h filterx.SQLHandler) Option {
	return func(o *options) {
		if o.organisationOverrides == nil {
			o.organisationOverrides = map[string]filterx.SQLHandler{}
		}
		o.organisationOverrides[field] = h
	}
}

// WithUserHooks installs h on the User adapters.
func WithUserHooks(h UserHooks) Option {
	return func(o *options) { o.userHooks = h }
}

// WithUserListOverride substitutes the generated filter dispatch for one
// User filter field (e.g. a derived state computed via subqueries).
func WithUserListOverride(field string, h filterx.SQLHandler) Option {
	return func(o *options) {
		if o.userOverrides == nil {
			o.userOverrides = map[string]filterx.SQLHandler{}
		}
		o.userOverrides[field] = h
	}
}

// WithMemberGraphQLListOverride substitutes the generated filter dispatch
// for one Member filter field on the GraphQL adapters.
func WithMemberGraphQLListOverride(field string, h filterx.GraphQLHandler) Option {
	return func(o *options) {
		if o.memberGQLOverrides == nil {
			o.memberGQLOverrides = map[string]filterx.GraphQLHandler{}
		}
		o.memberGQLOverrides[field] = h
	}
}

// WithOrganisationGraphQLListOverride substitutes the generated filter dispatch
// for one Organisation filter field on the GraphQL adapters.
func WithOrganisationGraphQLListOverride(field string, h filterx.GraphQLHandler) Option {
	return func(o *options) {
		if o.organisationGQLOverrides == nil {
			o.organisationGQLOverrides = map[string]filterx.GraphQLHandler{}
		}
		o.organisationGQLOverrides[field] = h
	}
}

// WithUserGraphQLListOverride substitutes the generated filter dispatch
// for one User filter field on the GraphQL adapters.
func WithUserGraphQLListOverride(field string, h filterx.GraphQLHandler) Option {
	return func(o *options) {
		if o.userGQLOverrides == nil {
			o.userGQLOverrides = map[string]filterx.GraphQLHandler{}
		}
		o.userGQLOverrides[field] = h
	}
}

// New picks the adapter set for the live handle in conn: GraphQL when a
// client connection is present, otherwise GORM.
func New(conn repox.Conn, opts ...Option) Repositories {
	if conn.GraphQL != nil {
		return NewGraphQL(conn.GraphQL, opts...)
	}
	return NewGorm(conn.Gorm, opts...)
}

// NewGraphQL builds the GraphQL adapter set over svc.
func NewGraphQL(svc *genql.Service, opts ...Option) Repositories {
	var o options
	for _, opt := range opts {
		opt(&o)
	}
	return Repositories{
		Members:       &GraphQLMemberRepository{Svc: svc, Hooks: o.memberHooks, ListOverrides: o.memberGQLOverrides},
		Organisations: &GraphQLOrganisationRepository{Svc: svc, Hooks: o.organisationHooks, ListOverrides: o.organisationGQLOverrides},
		Users:         &GraphQLUserRepository{Svc: svc, Hooks: o.userHooks, ListOverrides: o.userGQLOverrides},
	}
}

// NewGorm builds the GORM adapter set over db.
func NewGorm(db *gorm.DB, opts ...Option) Repositories {
	var o options
	for _, opt := range opts {
		opt(&o)
	}
	return Repositories{
		Members:       &GormMemberRepository{DB: db, Hooks: o.memberHooks, ListOverrides: o.memberOverrides},
		Organisations: &GormOrganisationRepository{DB: db, Hooks: o.organisationHooks, ListOverrides: o.organisationOverrides},
		Users:         &GormUserRepository{DB: db, Hooks: o.userHooks, ListOverrides: o.userOverrides},
	}
}
