// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
//
//	protoc-gen-store (unknown)
//	protoc (unknown)
//
// database: reserved_db
// package:  grpcx
//
// Backend-agnostic resource descriptors: one store.Resource per proto resource.
// Register them with store.NewRegistry(Resources...) and pass any driver.
// annotations: entity.v1 (unknown), store.v1 (unknown)
// engine:      protokit (unknown)
// runtime:     github.com/the-protobuf-project/runtime-go/database/store
//
// store — https://github.com/the-protobuf-project/store
package grpcx

import (
	"example.com/test/gen"
	"github.com/the-protobuf-project/runtime-go/database/store"
	"google.golang.org/protobuf/proto"
)

// Resources are this database's runtime descriptors, one per proto resource.
//
// They carry no storage engine of their own: a descriptor says which table a
// message maps to, what each column is called and how it is typed, and which
// columns reference other resources. The driver decides what that means.
//
//	reg := store.NewRegistry(Resources...)
//	svc := adapter.New(orm.New(db), reg) // or evm.New(cfg), fabric.New(), ...
//
// Columns whose Generated, AutoCreate or AutoUpdate is set report Managed() at
// runtime: the bridge skips them and the driver supplies the value.
var Resources = []store.Resource{
	{
		// Account is forced onto the reserved table name "user" via a table override, with reserved-word columns and a composite UNIQUE index over them.
		Name:     "Account",
		Schema:   "public",
		Table:    "user",
		PKColumn: "id",
		New:      func() proto.Message { return &gen.Account{} },
		Columns: []store.Column{
			{Name: "id", Field: "", Kind: store.KindString, SQLType: "CHAR(26)", PrimaryKey: true, NotNull: true, Generated: "ulid"},
			{Name: "name", Field: "name", Kind: store.KindString, SQLType: "VARCHAR(255)", NotNull: true, Unique: true},
			{Name: "order", Field: "order", Kind: store.KindString, SQLType: "VARCHAR(255)"},
			{Name: "select", Field: "select", Kind: store.KindString, SQLType: "VARCHAR(255)"},
			{Name: "state", Field: "state", Kind: store.KindEnum, SQLType: "\"public\".\"state\""},
		},
	},
}
