// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: entity/v1/annotations.proto

package entitypbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_entity_v1_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*DatasourceOptions)(nil),
		Field:         51000,
		Name:          "entity.v1.datasource",
		Tag:           "bytes,51000,opt,name=datasource",
		Filename:      "entity/v1/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*TableOptions)(nil),
		Field:         51001,
		Name:          "entity.v1.table",
		Tag:           "bytes,51001,opt,name=table",
		Filename:      "entity/v1/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*ColumnOptions)(nil),
		Field:         51002,
		Name:          "entity.v1.column",
		Tag:           "bytes,51002,opt,name=column",
		Filename:      "entity/v1/annotations.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// datasource groups the file's messages into a database and names its schema.
	//
	// optional entity.v1.DatasourceOptions datasource = 51000;
	E_Datasource = &file_entity_v1_annotations_proto_extTypes[0]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// table overrides table-level structure: name, skip, id strategy, timestamps,
	// indexes.
	//
	// optional entity.v1.TableOptions table = 51001;
	E_Table = &file_entity_v1_annotations_proto_extTypes[1]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// column overrides column-level structure: name and skip.
	//
	// optional entity.v1.ColumnOptions column = 51002;
	E_Column = &file_entity_v1_annotations_proto_extTypes[2]
)

var File_entity_v1_annotations_proto protoreflect.FileDescriptor

const file_entity_v1_annotations_proto_rawDesc = "" +
	"\n" +
	"\x1bentity/v1/annotations.proto\x12\tentity.v1\x1a\x16entity/v1/column.proto\x1a\x1aentity/v1/datasource.proto\x1a\x15entity/v1/table.proto\x1a google/protobuf/descriptor.proto:\\\n" +
	"\n" +
	"datasource\x12\x1c.google.protobuf.FileOptions\x18\xb8\x8e\x03 \x01(\v2\x1c.entity.v1.DatasourceOptionsR\n" +
	"datasource:P\n" +
	"\x05table\x12\x1f.google.protobuf.MessageOptions\x18\xb9\x8e\x03 \x01(\v2\x17.entity.v1.TableOptionsR\x05table:Q\n" +
	"\x06column\x12\x1d.google.protobuf.FieldOptions\x18\xba\x8e\x03 \x01(\v2\x18.entity.v1.ColumnOptionsR\x06columnB\xb4\x01\n" +
	"\rcom.entity.v1B\x10AnnotationsProtoP\x01ZLgithub.com/the-protobuf-project/store/plugin/entity/pb/entitypbv1;entitypbv1\xa2\x02\x03EXX\xaa\x02\tEntity.V1\xca\x02\tEntity\\V1\xe2\x02\x15Entity\\V1\\GPBMetadata\xea\x02\n" +
	"Entity::V1b\x06proto3"

var file_entity_v1_annotations_proto_goTypes = []any{
	(*descriptorpb.FileOptions)(nil),    // 0: google.protobuf.FileOptions
	(*descriptorpb.MessageOptions)(nil), // 1: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 2: google.protobuf.FieldOptions
	(*DatasourceOptions)(nil),           // 3: entity.v1.DatasourceOptions
	(*TableOptions)(nil),                // 4: entity.v1.TableOptions
	(*ColumnOptions)(nil),               // 5: entity.v1.ColumnOptions
}
var file_entity_v1_annotations_proto_depIdxs = []int32{
	0, // 0: entity.v1.datasource:extendee -> google.protobuf.FileOptions
	1, // 1: entity.v1.table:extendee -> google.protobuf.MessageOptions
	2, // 2: entity.v1.column:extendee -> google.protobuf.FieldOptions
	3, // 3: entity.v1.datasource:type_name -> entity.v1.DatasourceOptions
	4, // 4: entity.v1.table:type_name -> entity.v1.TableOptions
	5, // 5: entity.v1.column:type_name -> entity.v1.ColumnOptions
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	3, // [3:6] is the sub-list for extension type_name
	0, // [0:3] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_entity_v1_annotations_proto_init() }
func file_entity_v1_annotations_proto_init() {
	if File_entity_v1_annotations_proto != nil {
		return
	}
	file_entity_v1_column_proto_init()
	file_entity_v1_datasource_proto_init()
	file_entity_v1_table_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_entity_v1_annotations_proto_rawDesc), len(file_entity_v1_annotations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 3,
			NumServices:   0,
		},
		GoTypes:           file_entity_v1_annotations_proto_goTypes,
		DependencyIndexes: file_entity_v1_annotations_proto_depIdxs,
		ExtensionInfos:    file_entity_v1_annotations_proto_extTypes,
	}.Build()
	File_entity_v1_annotations_proto = out.File
	file_entity_v1_annotations_proto_goTypes = nil
	file_entity_v1_annotations_proto_depIdxs = nil
}
