// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: entity/v1/datasource.proto

package entitypbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DatasourceOptions groups the messages of a .proto file into one database and
// names the schema they live in. Files that share the same database name merge
// into a single generated schema tree.
//
// This is neutral structure: it decides what things are *named*, not how any
// particular generator renders them. Every generator that runs entity.Reader()
// reads the same values from here, which is what makes two plugins over the same
// protos agree on database, schema, and table names.
//
// Applied via:
//
//	option (entity.v1.datasource) = {
//	  database: "bookstore_db"
//	  schema: "bookstore"
//	  provider: "postgres"
//	  url: "postgresql://localhost:5432/bookstore_db"
//	};
type DatasourceOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// database is the explicit database identifier.
	// Defaults to the last segment of the proto package name.
	Database string `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	// schema overrides the schema namespace for every table in this file.
	// When unset, the schema is inferred from the google.api.resource.type prefix
	// ("bookstore.v1/Book" → "bookstore_v1").
	//
	// An explicit value here is authoritative: it is never version-stripped, even
	// when the plugin's layout config asks for stripping elsewhere.
	Schema string `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema,omitempty"`
	// url is the database connection URL documented in generated config and DDL
	// headers.
	Url string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	// provider selects the datasource's type system.
	// Accepted values: "postgres" (default), "mongodb", "evm", "solana", "fabric".
	Provider      string `protobuf:"bytes,4,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatasourceOptions) Reset() {
	*x = DatasourceOptions{}
	mi := &file_entity_v1_datasource_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatasourceOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatasourceOptions) ProtoMessage() {}

func (x *DatasourceOptions) ProtoReflect() protoreflect.Message {
	mi := &file_entity_v1_datasource_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatasourceOptions.ProtoReflect.Descriptor instead.
func (*DatasourceOptions) Descriptor() ([]byte, []int) {
	return file_entity_v1_datasource_proto_rawDescGZIP(), []int{0}
}

func (x *DatasourceOptions) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *DatasourceOptions) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *DatasourceOptions) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *DatasourceOptions) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

var File_entity_v1_datasource_proto protoreflect.FileDescriptor

const file_entity_v1_datasource_proto_rawDesc = "" +
	"\n" +
	"\x1aentity/v1/datasource.proto\x12\tentity.v1\"u\n" +
	"\x11DatasourceOptions\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x16\n" +
	"\x06schema\x18\x02 \x01(\tR\x06schema\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x1a\n" +
	"\bprovider\x18\x04 \x01(\tR\bproviderB\xb3\x01\n" +
	"\rcom.entity.v1B\x0fDatasourceProtoP\x01ZLgithub.com/the-protobuf-project/store/plugin/entity/pb/entitypbv1;entitypbv1\xa2\x02\x03EXX\xaa\x02\tEntity.V1\xca\x02\tEntity\\V1\xe2\x02\x15Entity\\V1\\GPBMetadata\xea\x02\n" +
	"Entity::V1b\x06proto3"

var (
	file_entity_v1_datasource_proto_rawDescOnce sync.Once
	file_entity_v1_datasource_proto_rawDescData []byte
)

func file_entity_v1_datasource_proto_rawDescGZIP() []byte {
	file_entity_v1_datasource_proto_rawDescOnce.Do(func() {
		file_entity_v1_datasource_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_entity_v1_datasource_proto_rawDesc), len(file_entity_v1_datasource_proto_rawDesc)))
	})
	return file_entity_v1_datasource_proto_rawDescData
}

var file_entity_v1_datasource_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_entity_v1_datasource_proto_goTypes = []any{
	(*DatasourceOptions)(nil), // 0: entity.v1.DatasourceOptions
}
var file_entity_v1_datasource_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_entity_v1_datasource_proto_init() }
func file_entity_v1_datasource_proto_init() {
	if File_entity_v1_datasource_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_entity_v1_datasource_proto_rawDesc), len(file_entity_v1_datasource_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entity_v1_datasource_proto_goTypes,
		DependencyIndexes: file_entity_v1_datasource_proto_depIdxs,
		MessageInfos:      file_entity_v1_datasource_proto_msgTypes,
	}.Build()
	File_entity_v1_datasource_proto = out.File
	file_entity_v1_datasource_proto_goTypes = nil
	file_entity_v1_datasource_proto_depIdxs = nil
}
