-- Code generated by protoc-gen-orm. DO NOT EDIT.
-- versions:
-- 	protoc-gen-orm (unknown)
-- 	protoc (unknown)
--
-- database: profile_db
-- schemas:  profile
--
-- Single-file migration: every schema in one transaction. Idempotent — safe to re-apply.
--
-- orm — https://github.com/the-protobuf-project/orm

BEGIN;

-- Schemas
CREATE SCHEMA IF NOT EXISTS "profile";

-- Tables (foreign keys are added after every table exists, so creation order
-- never matters — even across schemas or reference cycles).

-- Account exercises every projection the validation presets have: stacked presets on one field, the nil-guard an optional column needs, numeric and temporal and repeated presets, a preset whose SQL form repeats the column reference, and a preset with no SQL form at all.
CREATE TABLE IF NOT EXISTS "profile"."accounts" (
    -- Unique identifier for the record.
    "id"  CHAR(26)  NOT NULL  PRIMARY KEY,
    "name"  VARCHAR(255)  NOT NULL  UNIQUE,
    -- Two presets stacked on one required column: both project to an app check and to a CHECK constraint.
    "email"  VARCHAR(255)  NOT NULL  CONSTRAINT "chk_accounts_email" CHECK ("email" ~ '^[^@[:space:]]+@[^@[:space:]]+[.][^@[:space:]]+$' AND "email" = lower("email")),
    -- Optional, so the Go field is a pointer and the generated check must guard against nil before dereferencing — absence is field_behavior's business.
    "website"  VARCHAR(255)  CONSTRAINT "chk_accounts_website" CHECK ("website" ~ '^[a-zA-Z][a-zA-Z0-9+.-]*://[^[:space:]]+$'),
    -- A preset and a parameterized constraint on one column: the two surfaces compose into a single Validate method and a single CHECK constraint.
    "credits"  INTEGER  NOT NULL  CONSTRAINT "chk_accounts_credits" CHECK ("credits" >= 0 AND "credits" <= 1000),
    -- A pattern carrying a backslash, which must survive into the GORM struct tag escaped — an unescaped one voids the whole tag, taking NOT NULL with it.
    "sku"  VARCHAR(255)  CONSTRAINT "chk_accounts_sku" CHECK ("sku" ~ '^[A-Z]{3}-\d{4}$'),
    -- A closed value set, and below it the same min/max fields reading as a length rather than a value because the column is a string.
    "tier"  VARCHAR(255)  NOT NULL  CONSTRAINT "chk_accounts_tier" CHECK ("tier" IN ('free', 'pro', 'enterprise')),
    "bio"  VARCHAR(255)  CONSTRAINT "chk_accounts_bio" CHECK (length("bio") >= 10 AND length("bio") <= 200),
    -- VALIDATE_TRIMMED's SQL form names the column twice, covering placeholder substitution; VALIDATE_SLUG covers a preset with no go-playground builtin.
    "handle"  VARCHAR(255)  NOT NULL  CONSTRAINT "chk_accounts_handle" CHECK ("handle" ~ '^[a-z0-9]+(-[a-z0-9]+)*$' AND "handle" = btrim("handle")),
    -- Application-only: a CHECK referencing wall-clock time would not be immutable, so no constraint is emitted for this column.
    "born_at"  TIMESTAMPTZ,
    -- Repeated presets judge the list itself rather than its elements.
    "tags"  VARCHAR(255)[]  CONSTRAINT "chk_accounts_tags" CHECK (cardinality("tags") > 0)
);

-- Device carries no presets at all, proving a table in a validated tree emits no Validate method and no store write-path call when nothing is annotated.
CREATE TABLE IF NOT EXISTS "profile"."devices" (
    -- Unique identifier for the record.
    "id"  CHAR(26)  NOT NULL  PRIMARY KEY,
    "name"  VARCHAR(255)  NOT NULL  UNIQUE,
    "label"  VARCHAR(255)
);

-- Documentation
COMMENT ON TABLE "profile"."accounts" IS 'Account exercises every projection the validation presets have: stacked presets on one field, the nil-guard an optional column needs, numeric and temporal and repeated presets, a preset whose SQL form repeats the column reference, and a preset with no SQL form at all.';
COMMENT ON COLUMN "profile"."accounts"."id" IS 'Unique identifier for the record.';
COMMENT ON COLUMN "profile"."accounts"."email" IS 'Two presets stacked on one required column: both project to an app check and to a CHECK constraint.';
COMMENT ON COLUMN "profile"."accounts"."website" IS 'Optional, so the Go field is a pointer and the generated check must guard against nil before dereferencing — absence is field_behavior''s business.';
COMMENT ON COLUMN "profile"."accounts"."credits" IS 'A preset and a parameterized constraint on one column: the two surfaces compose into a single Validate method and a single CHECK constraint.';
COMMENT ON COLUMN "profile"."accounts"."sku" IS 'A pattern carrying a backslash, which must survive into the GORM struct tag escaped — an unescaped one voids the whole tag, taking NOT NULL with it.';
COMMENT ON COLUMN "profile"."accounts"."tier" IS 'A closed value set, and below it the same min/max fields reading as a length rather than a value because the column is a string.';
COMMENT ON COLUMN "profile"."accounts"."handle" IS 'VALIDATE_TRIMMED''s SQL form names the column twice, covering placeholder substitution; VALIDATE_SLUG covers a preset with no go-playground builtin.';
COMMENT ON COLUMN "profile"."accounts"."born_at" IS 'Application-only: a CHECK referencing wall-clock time would not be immutable, so no constraint is emitted for this column.';
COMMENT ON COLUMN "profile"."accounts"."tags" IS 'Repeated presets judge the list itself rather than its elements.';
COMMENT ON TABLE "profile"."devices" IS 'Device carries no presets at all, proving a table in a validated tree emits no Validate method and no store write-path call when nothing is annotated.';
COMMENT ON COLUMN "profile"."devices"."id" IS 'Unique identifier for the record.';

COMMIT;
