// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: store/v1/annotations.proto

package storepbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_store_v1_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*TableOptions)(nil),
		Field:         50010,
		Name:          "store.v1.table",
		Tag:           "bytes,50010,opt,name=table",
		Filename:      "store/v1/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*ColumnOptions)(nil),
		Field:         50011,
		Name:          "store.v1.column",
		Tag:           "bytes,50011,opt,name=column",
		Filename:      "store/v1/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*QueryOptions)(nil),
		Field:         50012,
		Name:          "store.v1.query",
		Tag:           "bytes,50012,opt,name=query",
		Filename:      "store/v1/annotations.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// table overrides table-level storage: the outbox companion table.
	//
	// optional store.v1.TableOptions table = 50010;
	E_Table = &file_store_v1_annotations_proto_extTypes[0]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// column overrides column-level storage: type, sizing, defaults,
	// constraints, and foreign-key referential actions.
	//
	// optional store.v1.ColumnOptions column = 50011;
	E_Column = &file_store_v1_annotations_proto_extTypes[1]
	// query tunes the field's generated list-query surface: AIP-160 filter,
	// AIP-132 order_by, and free-text search.
	//
	// optional store.v1.QueryOptions query = 50012;
	E_Query = &file_store_v1_annotations_proto_extTypes[2]
)

var File_store_v1_annotations_proto protoreflect.FileDescriptor

const file_store_v1_annotations_proto_rawDesc = "" +
	"\n" +
	"\x1astore/v1/annotations.proto\x12\bstore.v1\x1a google/protobuf/descriptor.proto\x1a\x15store/v1/column.proto\x1a\x14store/v1/query.proto\x1a\x14store/v1/table.proto:O\n" +
	"\x05table\x12\x1f.google.protobuf.MessageOptions\x18چ\x03 \x01(\v2\x16.store.v1.TableOptionsR\x05table:P\n" +
	"\x06column\x12\x1d.google.protobuf.FieldOptions\x18ۆ\x03 \x01(\v2\x17.store.v1.ColumnOptionsR\x06column:M\n" +
	"\x05query\x12\x1d.google.protobuf.FieldOptions\x18܆\x03 \x01(\v2\x16.store.v1.QueryOptionsR\x05queryB\xa6\x01\n" +
	"\fcom.store.v1B\x10AnnotationsProtoP\x01ZCgithub.com/the-protobuf-project/store/plugin/pb/storepbv1;storepbv1\xa2\x02\x03SXX\xaa\x02\bStore.V1\xca\x02\bStore\\V1\xe2\x02\x14Store\\V1\\GPBMetadata\xea\x02\tStore::V1b\x06proto3"

var file_store_v1_annotations_proto_goTypes = []any{
	(*descriptorpb.MessageOptions)(nil), // 0: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 1: google.protobuf.FieldOptions
	(*TableOptions)(nil),                // 2: store.v1.TableOptions
	(*ColumnOptions)(nil),               // 3: store.v1.ColumnOptions
	(*QueryOptions)(nil),                // 4: store.v1.QueryOptions
}
var file_store_v1_annotations_proto_depIdxs = []int32{
	0, // 0: store.v1.table:extendee -> google.protobuf.MessageOptions
	1, // 1: store.v1.column:extendee -> google.protobuf.FieldOptions
	1, // 2: store.v1.query:extendee -> google.protobuf.FieldOptions
	2, // 3: store.v1.table:type_name -> store.v1.TableOptions
	3, // 4: store.v1.column:type_name -> store.v1.ColumnOptions
	4, // 5: store.v1.query:type_name -> store.v1.QueryOptions
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	3, // [3:6] is the sub-list for extension type_name
	0, // [0:3] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_store_v1_annotations_proto_init() }
func file_store_v1_annotations_proto_init() {
	if File_store_v1_annotations_proto != nil {
		return
	}
	file_store_v1_column_proto_init()
	file_store_v1_query_proto_init()
	file_store_v1_table_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_store_v1_annotations_proto_rawDesc), len(file_store_v1_annotations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 3,
			NumServices:   0,
		},
		GoTypes:           file_store_v1_annotations_proto_goTypes,
		DependencyIndexes: file_store_v1_annotations_proto_depIdxs,
		ExtensionInfos:    file_store_v1_annotations_proto_extTypes,
	}.Build()
	File_store_v1_annotations_proto = out.File
	file_store_v1_annotations_proto_goTypes = nil
	file_store_v1_annotations_proto_depIdxs = nil
}
