// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: store/v1/column.proto

package storepbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ReferentialAction is the ON DELETE / ON UPDATE behavior of a foreign key
// inferred from google.api.resource_reference.
//
// This stays in store.v1 rather than moving to entity.v1 because it is a
// storage guarantee, not a name — but protokit still consumes it mid-build: the
// foreign-key column of an embedded child relation is synthesized and carries no
// descriptor of its own, so the action has to reach protokit through a
// StructureReader while the embed is materialized, not after.
type ReferentialAction int32

const (
	// Database default behavior (NO ACTION in PostgreSQL).
	ReferentialAction_REFERENTIAL_ACTION_UNSPECIFIED ReferentialAction = 0
	// Delete/update child rows when the parent row is deleted/updated.
	ReferentialAction_REFERENTIAL_ACTION_CASCADE ReferentialAction = 1
	// Reject the parent delete/update while child rows exist.
	ReferentialAction_REFERENTIAL_ACTION_RESTRICT ReferentialAction = 2
	// Null the FK column when the parent row is deleted/updated.
	ReferentialAction_REFERENTIAL_ACTION_SET_NULL ReferentialAction = 3
	// Reset the FK column to its default value.
	ReferentialAction_REFERENTIAL_ACTION_SET_DEFAULT ReferentialAction = 4
	// Explicit NO ACTION.
	ReferentialAction_REFERENTIAL_ACTION_NO_ACTION ReferentialAction = 5
)

// Enum value maps for ReferentialAction.
var (
	ReferentialAction_name = map[int32]string{
		0: "REFERENTIAL_ACTION_UNSPECIFIED",
		1: "REFERENTIAL_ACTION_CASCADE",
		2: "REFERENTIAL_ACTION_RESTRICT",
		3: "REFERENTIAL_ACTION_SET_NULL",
		4: "REFERENTIAL_ACTION_SET_DEFAULT",
		5: "REFERENTIAL_ACTION_NO_ACTION",
	}
	ReferentialAction_value = map[string]int32{
		"REFERENTIAL_ACTION_UNSPECIFIED": 0,
		"REFERENTIAL_ACTION_CASCADE":     1,
		"REFERENTIAL_ACTION_RESTRICT":    2,
		"REFERENTIAL_ACTION_SET_NULL":    3,
		"REFERENTIAL_ACTION_SET_DEFAULT": 4,
		"REFERENTIAL_ACTION_NO_ACTION":   5,
	}
)

func (x ReferentialAction) Enum() *ReferentialAction {
	p := new(ReferentialAction)
	*p = x
	return p
}

func (x ReferentialAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReferentialAction) Descriptor() protoreflect.EnumDescriptor {
	return file_store_v1_column_proto_enumTypes[0].Descriptor()
}

func (ReferentialAction) Type() protoreflect.EnumType {
	return &file_store_v1_column_proto_enumTypes[0]
}

func (x ReferentialAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReferentialAction.Descriptor instead.
func (ReferentialAction) EnumDescriptor() ([]byte, []int) {
	return file_store_v1_column_proto_rawDescGZIP(), []int{0}
}

// ColumnOptions overrides how a field is *stored*: its database type, its
// sizing, its default, its constraints, and the referential behavior of any
// foreign key it forms.
//
// What the column is *called*, and whether it exists at all, is neutral
// structure and lives in (entity.v1.column), which every plugin reads through the
// same shared reader, so they all agree on the name. Nothing here changes a name.
//
// Applied via:
//
//	string title = 2 [(store.v1.column) = {max_length: 500}];
type ColumnOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// type is an explicit database type, e.g. "VARCHAR(255)", "JSONB", "TIMESTAMPTZ".
	// Provider-specific escape hatch; prefer max_length / precision for
	// provider-neutral sizing. Overrides all inference.
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// default_value is a SQL default expression, e.g. "NOW()", "'active'", "0".
	// Written verbatim into the DEFAULT clause.
	DefaultValue string `protobuf:"bytes,2,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	// unique adds a UNIQUE constraint to this column.
	Unique bool `protobuf:"varint,3,opt,name=unique,proto3" json:"unique,omitempty"`
	// index adds a single-column index on this column.
	// Use (entity.v1.table).indexes for composite indexes.
	Index bool `protobuf:"varint,4,opt,name=index,proto3" json:"index,omitempty"`
	// max_length caps a string field: VARCHAR(max_length) instead of the
	// VARCHAR(255) default. Provider-neutral (Mongo ignores it).
	MaxLength int32 `protobuf:"varint,5,opt,name=max_length,json=maxLength,proto3" json:"max_length,omitempty"`
	// precision sizes the integral digit count of a numeric field:
	// NUMERIC(precision, scale). Applies to double/float fields.
	Precision int32 `protobuf:"varint,6,opt,name=precision,proto3" json:"precision,omitempty"`
	// scale sizes the fractional digit count of a numeric field.
	// Defaults to 0 when only precision is set.
	Scale int32 `protobuf:"varint,7,opt,name=scale,proto3" json:"scale,omitempty"`
	// on_delete sets the FK ON DELETE referential action for a field carrying
	// google.api.resource_reference. Ignored on non-reference fields.
	OnDelete ReferentialAction `protobuf:"varint,8,opt,name=on_delete,json=onDelete,proto3,enum=store.v1.ReferentialAction" json:"on_delete,omitempty"`
	// on_update sets the FK ON UPDATE referential action for a field carrying
	// google.api.resource_reference. Ignored on non-reference fields.
	OnUpdate      ReferentialAction `protobuf:"varint,9,opt,name=on_update,json=onUpdate,proto3,enum=store.v1.ReferentialAction" json:"on_update,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColumnOptions) Reset() {
	*x = ColumnOptions{}
	mi := &file_store_v1_column_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColumnOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnOptions) ProtoMessage() {}

func (x *ColumnOptions) ProtoReflect() protoreflect.Message {
	mi := &file_store_v1_column_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnOptions.ProtoReflect.Descriptor instead.
func (*ColumnOptions) Descriptor() ([]byte, []int) {
	return file_store_v1_column_proto_rawDescGZIP(), []int{0}
}

func (x *ColumnOptions) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ColumnOptions) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

func (x *ColumnOptions) GetUnique() bool {
	if x != nil {
		return x.Unique
	}
	return false
}

func (x *ColumnOptions) GetIndex() bool {
	if x != nil {
		return x.Index
	}
	return false
}

func (x *ColumnOptions) GetMaxLength() int32 {
	if x != nil {
		return x.MaxLength
	}
	return 0
}

func (x *ColumnOptions) GetPrecision() int32 {
	if x != nil {
		return x.Precision
	}
	return 0
}

func (x *ColumnOptions) GetScale() int32 {
	if x != nil {
		return x.Scale
	}
	return 0
}

func (x *ColumnOptions) GetOnDelete() ReferentialAction {
	if x != nil {
		return x.OnDelete
	}
	return ReferentialAction_REFERENTIAL_ACTION_UNSPECIFIED
}

func (x *ColumnOptions) GetOnUpdate() ReferentialAction {
	if x != nil {
		return x.OnUpdate
	}
	return ReferentialAction_REFERENTIAL_ACTION_UNSPECIFIED
}

var File_store_v1_column_proto protoreflect.FileDescriptor

const file_store_v1_column_proto_rawDesc = "" +
	"\n" +
	"\x15store/v1/column.proto\x12\bstore.v1\"\xbd\x02\n" +
	"\rColumnOptions\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12#\n" +
	"\rdefault_value\x18\x02 \x01(\tR\fdefaultValue\x12\x16\n" +
	"\x06unique\x18\x03 \x01(\bR\x06unique\x12\x14\n" +
	"\x05index\x18\x04 \x01(\bR\x05index\x12\x1d\n" +
	"\n" +
	"max_length\x18\x05 \x01(\x05R\tmaxLength\x12\x1c\n" +
	"\tprecision\x18\x06 \x01(\x05R\tprecision\x12\x14\n" +
	"\x05scale\x18\a \x01(\x05R\x05scale\x128\n" +
	"\ton_delete\x18\b \x01(\x0e2\x1b.store.v1.ReferentialActionR\bonDelete\x128\n" +
	"\ton_update\x18\t \x01(\x0e2\x1b.store.v1.ReferentialActionR\bonUpdate*\xdf\x01\n" +
	"\x11ReferentialAction\x12\"\n" +
	"\x1eREFERENTIAL_ACTION_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aREFERENTIAL_ACTION_CASCADE\x10\x01\x12\x1f\n" +
	"\x1bREFERENTIAL_ACTION_RESTRICT\x10\x02\x12\x1f\n" +
	"\x1bREFERENTIAL_ACTION_SET_NULL\x10\x03\x12\"\n" +
	"\x1eREFERENTIAL_ACTION_SET_DEFAULT\x10\x04\x12 \n" +
	"\x1cREFERENTIAL_ACTION_NO_ACTION\x10\x05B\xa1\x01\n" +
	"\fcom.store.v1B\vColumnProtoP\x01ZCgithub.com/the-protobuf-project/store/plugin/pb/storepbv1;storepbv1\xa2\x02\x03SXX\xaa\x02\bStore.V1\xca\x02\bStore\\V1\xe2\x02\x14Store\\V1\\GPBMetadata\xea\x02\tStore::V1b\x06proto3"

var (
	file_store_v1_column_proto_rawDescOnce sync.Once
	file_store_v1_column_proto_rawDescData []byte
)

func file_store_v1_column_proto_rawDescGZIP() []byte {
	file_store_v1_column_proto_rawDescOnce.Do(func() {
		file_store_v1_column_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_store_v1_column_proto_rawDesc), len(file_store_v1_column_proto_rawDesc)))
	})
	return file_store_v1_column_proto_rawDescData
}

var file_store_v1_column_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_store_v1_column_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_store_v1_column_proto_goTypes = []any{
	(ReferentialAction)(0), // 0: store.v1.ReferentialAction
	(*ColumnOptions)(nil),  // 1: store.v1.ColumnOptions
}
var file_store_v1_column_proto_depIdxs = []int32{
	0, // 0: store.v1.ColumnOptions.on_delete:type_name -> store.v1.ReferentialAction
	0, // 1: store.v1.ColumnOptions.on_update:type_name -> store.v1.ReferentialAction
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_store_v1_column_proto_init() }
func file_store_v1_column_proto_init() {
	if File_store_v1_column_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_store_v1_column_proto_rawDesc), len(file_store_v1_column_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_store_v1_column_proto_goTypes,
		DependencyIndexes: file_store_v1_column_proto_depIdxs,
		EnumInfos:         file_store_v1_column_proto_enumTypes,
		MessageInfos:      file_store_v1_column_proto_msgTypes,
	}.Build()
	File_store_v1_column_proto = out.File
	file_store_v1_column_proto_goTypes = nil
	file_store_v1_column_proto_depIdxs = nil
}
