// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: store/v1/query.proto

package storepbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// QueryOptions tunes a field's generated list-query surface — the AIP-160
// filter, AIP-132 order_by, and free-text search specs — separately from the
// physical column options in ColumnOptions.
//
// Applied via:
//
//	string display_name = 2 [(store.v1.query) = {search: true}];
//	string state = 5 [(store.v1.query) = {filterable: false, sortable: false}];
type QueryOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// filterable overrides the type-derived default in generated AIP-160 filter
	// specs (scalar columns are filterable by default, with operators inferred
	// from the column type). Explicit presence matters: `filterable: false`
	// removes the field from the spec; unset keeps the default.
	Filterable *bool `protobuf:"varint,1,opt,name=filterable,proto3,oneof" json:"filterable,omitempty"`
	// sortable overrides the type-derived default in generated AIP-132 order_by
	// allowlists (scalar, date, timestamp, and numeric columns are sortable by
	// default). Explicit presence matters, as with filterable.
	Sortable *bool `protobuf:"varint,2,opt,name=sortable,proto3,oneof" json:"sortable,omitempty"`
	// search includes this column in the bareword free-text search: a filter
	// term with no field (e.g. `beach resort`) matches it with a
	// case-insensitive contains. Off by default.
	Search        bool `protobuf:"varint,3,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryOptions) Reset() {
	*x = QueryOptions{}
	mi := &file_store_v1_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryOptions) ProtoMessage() {}

func (x *QueryOptions) ProtoReflect() protoreflect.Message {
	mi := &file_store_v1_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryOptions.ProtoReflect.Descriptor instead.
func (*QueryOptions) Descriptor() ([]byte, []int) {
	return file_store_v1_query_proto_rawDescGZIP(), []int{0}
}

func (x *QueryOptions) GetFilterable() bool {
	if x != nil && x.Filterable != nil {
		return *x.Filterable
	}
	return false
}

func (x *QueryOptions) GetSortable() bool {
	if x != nil && x.Sortable != nil {
		return *x.Sortable
	}
	return false
}

func (x *QueryOptions) GetSearch() bool {
	if x != nil {
		return x.Search
	}
	return false
}

var File_store_v1_query_proto protoreflect.FileDescriptor

const file_store_v1_query_proto_rawDesc = "" +
	"\n" +
	"\x14store/v1/query.proto\x12\bstore.v1\"\x88\x01\n" +
	"\fQueryOptions\x12#\n" +
	"\n" +
	"filterable\x18\x01 \x01(\bH\x00R\n" +
	"filterable\x88\x01\x01\x12\x1f\n" +
	"\bsortable\x18\x02 \x01(\bH\x01R\bsortable\x88\x01\x01\x12\x16\n" +
	"\x06search\x18\x03 \x01(\bR\x06searchB\r\n" +
	"\v_filterableB\v\n" +
	"\t_sortableB\xa0\x01\n" +
	"\fcom.store.v1B\n" +
	"QueryProtoP\x01ZCgithub.com/the-protobuf-project/store/plugin/pb/storepbv1;storepbv1\xa2\x02\x03SXX\xaa\x02\bStore.V1\xca\x02\bStore\\V1\xe2\x02\x14Store\\V1\\GPBMetadata\xea\x02\tStore::V1b\x06proto3"

var (
	file_store_v1_query_proto_rawDescOnce sync.Once
	file_store_v1_query_proto_rawDescData []byte
)

func file_store_v1_query_proto_rawDescGZIP() []byte {
	file_store_v1_query_proto_rawDescOnce.Do(func() {
		file_store_v1_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_store_v1_query_proto_rawDesc), len(file_store_v1_query_proto_rawDesc)))
	})
	return file_store_v1_query_proto_rawDescData
}

var file_store_v1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_store_v1_query_proto_goTypes = []any{
	(*QueryOptions)(nil), // 0: store.v1.QueryOptions
}
var file_store_v1_query_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_store_v1_query_proto_init() }
func file_store_v1_query_proto_init() {
	if File_store_v1_query_proto != nil {
		return
	}
	file_store_v1_query_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_store_v1_query_proto_rawDesc), len(file_store_v1_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_store_v1_query_proto_goTypes,
		DependencyIndexes: file_store_v1_query_proto_depIdxs,
		MessageInfos:      file_store_v1_query_proto_msgTypes,
	}.Build()
	File_store_v1_query_proto = out.File
	file_store_v1_query_proto_goTypes = nil
	file_store_v1_query_proto_depIdxs = nil
}
