// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: store/v1/table.proto

package storepbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TableOptions overrides how a message's table is *stored*.
//
// The table's name, whether it is emitted, its key strategy, its timestamps, and
// its composite indexes are neutral structure and live in (entity.v1.table),
// which every plugin reads through the same shared reader. What remains here is
// storage a name cannot express.
//
// Applied via:
//
//	option (store.v1.table) = {outbox: true};
type TableOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// outbox emits a companion outbox table beside this resource: the durable
	// hand-off point for change events, written in the same transaction as the
	// row it describes.
	//
	// Only the table is generated — no publisher, no store, no dispatch loop.
	// Owning the table is this plugin's job because an outbox *is* a table; who
	// drains it is not. A streams generator emits the publisher against this
	// schema, and does so without needing to edit anything in this tree.
	//
	// Off by default.
	Outbox        bool `protobuf:"varint,1,opt,name=outbox,proto3" json:"outbox,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableOptions) Reset() {
	*x = TableOptions{}
	mi := &file_store_v1_table_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableOptions) ProtoMessage() {}

func (x *TableOptions) ProtoReflect() protoreflect.Message {
	mi := &file_store_v1_table_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableOptions.ProtoReflect.Descriptor instead.
func (*TableOptions) Descriptor() ([]byte, []int) {
	return file_store_v1_table_proto_rawDescGZIP(), []int{0}
}

func (x *TableOptions) GetOutbox() bool {
	if x != nil {
		return x.Outbox
	}
	return false
}

var File_store_v1_table_proto protoreflect.FileDescriptor

const file_store_v1_table_proto_rawDesc = "" +
	"\n" +
	"\x14store/v1/table.proto\x12\bstore.v1\"&\n" +
	"\fTableOptions\x12\x16\n" +
	"\x06outbox\x18\x01 \x01(\bR\x06outboxB\xa0\x01\n" +
	"\fcom.store.v1B\n" +
	"TableProtoP\x01ZCgithub.com/the-protobuf-project/store/plugin/pb/storepbv1;storepbv1\xa2\x02\x03SXX\xaa\x02\bStore.V1\xca\x02\bStore\\V1\xe2\x02\x14Store\\V1\\GPBMetadata\xea\x02\tStore::V1b\x06proto3"

var (
	file_store_v1_table_proto_rawDescOnce sync.Once
	file_store_v1_table_proto_rawDescData []byte
)

func file_store_v1_table_proto_rawDescGZIP() []byte {
	file_store_v1_table_proto_rawDescOnce.Do(func() {
		file_store_v1_table_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_store_v1_table_proto_rawDesc), len(file_store_v1_table_proto_rawDesc)))
	})
	return file_store_v1_table_proto_rawDescData
}

var file_store_v1_table_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_store_v1_table_proto_goTypes = []any{
	(*TableOptions)(nil), // 0: store.v1.TableOptions
}
var file_store_v1_table_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_store_v1_table_proto_init() }
func file_store_v1_table_proto_init() {
	if File_store_v1_table_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_store_v1_table_proto_rawDesc), len(file_store_v1_table_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_store_v1_table_proto_goTypes,
		DependencyIndexes: file_store_v1_table_proto_depIdxs,
		MessageInfos:      file_store_v1_table_proto_msgTypes,
	}.Build()
	File_store_v1_table_proto = out.File
	file_store_v1_table_proto_goTypes = nil
	file_store_v1_table_proto_depIdxs = nil
}
