-- Copyright 2026 The Protobuf Project authors.
-- SPDX-License-Identifier: Apache-2.0

-- Code generated by protoc-gen-store. DO NOT EDIT.
-- versions:
-- 	protoc-gen-store (unknown)
-- 	protoc (unknown)
--
-- database: licence_db
-- schemas:  public
--
-- Single-file migration: every schema in one transaction. Idempotent — safe to re-apply.
-- annotations: entity.v1 (unknown), store.v1 (unknown)
-- engine:      protokit v1.2.1
--
-- store — https://github.com/the-protobuf-project/store

BEGIN;

-- Schemas
CREATE SCHEMA IF NOT EXISTS "public";

-- Tables (foreign keys are added after every table exists, so creation order
-- never matters — even across schemas or reference cycles).

-- Ledger exists to put one table in front of every renderer, so the goldens show the licence block the case's license_header marker sets: above the banner, separated by a blank line, and carried in each target's own comment syntax — "//" for the gorm models and the Prisma schema, "--" for the DDL.
CREATE TABLE IF NOT EXISTS "public"."ledgers" (
    -- Unique identifier for the record.
    "id"  CHAR(26)  NOT NULL  PRIMARY KEY,
    -- Ledger name.
    "name"  VARCHAR(255)  NOT NULL,
    -- Balance, in minor units.
    "balance"  BIGINT
);

-- Documentation
COMMENT ON TABLE "public"."ledgers" IS 'Ledger exists to put one table in front of every renderer, so the goldens show the licence block the case''s license_header marker sets: above the banner, separated by a blank line, and carried in each target''s own comment syntax — "//" for the gorm models and the Prisma schema, "--" for the DDL.';
COMMENT ON COLUMN "public"."ledgers"."id" IS 'Unique identifier for the record.';
COMMENT ON COLUMN "public"."ledgers"."name" IS 'Ledger name.';
COMMENT ON COLUMN "public"."ledgers"."balance" IS 'Balance, in minor units.';

COMMIT;
