-- Copyright 2026 The Protobuf Project authors.
-- SPDX-License-Identifier: Apache-2.0

-- Code generated by protoc-gen-store. DO NOT EDIT.
-- versions:
-- 	protoc-gen-store (unknown)
-- 	protoc (unknown)
-- source: licenseheader.proto
--
-- database: licence_db
-- schema:   public
--
-- annotations: entity.v1 (unknown), store.v1 (unknown)
-- engine:      protokit (unknown)
--
-- store — https://github.com/the-protobuf-project/store

CREATE SCHEMA IF NOT EXISTS "public";

-- Ledger exists to put one table in front of every renderer, so the goldens show the licence block the case's license_header marker sets: above the banner, separated by a blank line, and carried in each target's own comment syntax — "//" for the gorm models and the Prisma schema, "--" for the DDL.
CREATE TABLE "public"."ledgers" (
    -- Unique identifier for the record.
    "id"  CHAR(26)  NOT NULL  PRIMARY KEY,
    -- Ledger name.
    "name"  VARCHAR(255)  NOT NULL,
    -- Balance, in minor units.
    "balance"  BIGINT
);


-- Column and table documentation, persisted to the catalog.
COMMENT ON TABLE "public"."ledgers" IS 'Ledger exists to put one table in front of every renderer, so the goldens show the licence block the case''s license_header marker sets: above the banner, separated by a blank line, and carried in each target''s own comment syntax — "//" for the gorm models and the Prisma schema, "--" for the DDL.';
COMMENT ON COLUMN "public"."ledgers"."id" IS 'Unique identifier for the record.';
COMMENT ON COLUMN "public"."ledgers"."name" IS 'Ledger name.';
COMMENT ON COLUMN "public"."ledgers"."balance" IS 'Balance, in minor units.';
