package wire_test

// agreement_test.go holds the two protokit harnesses that check properties of a
// build rather than its bytes.
//
// IRAgreement is the one that matters for this plugin's place in the ecosystem.
// The whole reason the vocabulary was split is that a cache, a streams publisher
// and a docs generator over the same protos must derive the same tables and
// columns — otherwise a decorator generated by one plugin cannot address the
// rows persisted by another. Golden files cannot express that: they pin what
// *this* plugin emits, not what any other plugin would agree on.
//
// So the assertion is made against a stub plugin that registers exactly one
// reader: entity.Reader(), the shared neutral vocabulary. If the two disagree
// about a neutral name, something storage-specific has leaked into the structure,
// which is exactly the mistake the split exists to prevent.
//
// That stub is a closer model of a real second plugin than it used to be. protokit
// once read the neutral vocabulary itself, so the comparison could be made against
// a build with *no* readers; now nothing is neutral by default, and a plugin gets
// the shared names by importing the shared reader or not at all. Registering only
// entity.Reader() is what a cache or streams generator's proto source would
// actually look like on its first day.

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/the-protobuf-project/protokit"
	"github.com/the-protobuf-project/protokit/golden"
	"github.com/the-protobuf-project/protokit/schema"
	"github.com/the-protobuf-project/store/plugin/entity"
	"github.com/the-protobuf-project/store/plugin/factory/wire"
)

// TestIRAgreement requires the store plugin and a bare entity.v1 plugin to derive
// identical neutral facts for every case whose protos are written in entity.v1.
//
// Both sides read the same vocabulary through the same reader, so any divergence
// is this plugin's own vocabulary moving a name it should not — which is exactly
// the property under test.
func TestIRAgreement(t *testing.T) {
	for _, dir := range entityV1Cases(t) {
		name := filepath.Base(dir)
		if synthesizesTables[name] {
			continue
		}
		t.Run(name, func(t *testing.T) {
			golden.IRAgreement(t, dir, ormCasePlugin(dir), bareEntityPlugin(dir))
		})
	}
}

// synthesizesTables names the cases where this plugin deliberately adds a table
// that is not in the protos, so a bare protokit build cannot have it and the
// comparison is not meaningful.
//
// The outbox is the only one, and its absence from a bare build is correct
// rather than a leak: the companion table is a storage decision this plugin
// makes from (store.v1.table).outbox. A streams generator that needs to find it
// reads the same annotation and derives the same table — which is composition
// working, not the two disagreeing about what the protos say.
var synthesizesTables = map[string]bool{"outbox": true}

// TestDeterminism requires two builds of the same case to produce byte-identical
// output. Map iteration and unordered facet collection are the usual sources of
// drift, and both would otherwise show up as an intermittently failing golden
// diff that reruns "fix".
func TestDeterminism(t *testing.T) {
	for _, dir := range entityV1Cases(t) {
		t.Run(filepath.Base(dir), func(t *testing.T) {
			golden.Determinism(t, dir, determinismPlugin(dir))
		})
	}
}

// determinismPlugin is the case's plugin with its registry narrowed to the
// database targets.
//
// Determinism runs every target in the registry when a case ships no "targets"
// file, and the repository target refuses to generate without the go_module and
// gorm_module opts that describe the trees it composes. Narrowing here keeps the
// harness testing what it is for — that two builds agree — instead of failing on
// a target the case was never configured for.
func determinismPlugin(dir string) protokit.Plugin {
	pl := ormCasePlugin(dir)
	reg := make(map[string]schema.Target, len(defaultTargets))
	for _, name := range defaultTargets {
		if tgt, ok := pl.Registry[name]; ok {
			reg[name] = tgt
		}
	}
	pl.Registry = reg
	return pl
}

// bareEntityPlugin is a run with this plugin's targets but none of its
// vocabulary: entity.Reader() and nothing else. What it derives is what any other
// protokit plugin would derive from the same protos by importing the same reader.
//
// Note what is deliberately absent: entity.CompatReader(). A case written in the
// deprecated vocabulary would be read by the store plugin and not by this stub, so
// the two would disagree — correctly, because a legacy annotation is not something
// a new plugin should be expected to understand. The cases this harness selects
// are the entity.v1 ones (see entityV1Cases), so the situation does not arise.
//
// It does get the case's layout, and that is not a loophole — it is the
// distinction the LayoutResolver split exists to draw. The same protos generated
// under two different layouts *should* produce different database and schema
// names, because a layout is a deployment's choice; the same protos read by two
// different plugins should not, because an annotation is the schema's. Handing
// both sides the same layout is what leaves only the second difference visible,
// which is the one this test is about.
func bareEntityPlugin(dir string) protokit.Plugin {
	return wire.Plugin([]protokit.FacetReader{entity.Reader()}, ormCasePlugin(dir).Layout)
}

// entityV1Cases lists the golden cases whose protos import entity.v1, which are
// the ones a stub registering only entity.Reader() can read in full.
func entityV1Cases(t *testing.T) []string {
	t.Helper()
	root := filepath.Join("testdata", "cases")
	entries, err := os.ReadDir(root)
	if err != nil {
		t.Fatalf("read cases: %v", err)
	}
	var out []string
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		dir := filepath.Join(root, e.Name())
		if usesEntityV1(t, dir) {
			out = append(out, dir)
		}
	}
	if len(out) == 0 {
		t.Fatal("no entity.v1 cases found; the harness would pass vacuously")
	}
	return out
}

// usesEntityV1 reports whether any .proto the case compiles imports entity.v1,
// following the "source" indirection a case may use to point at the shared
// examples tree.
func usesEntityV1(t *testing.T, dir string) bool {
	t.Helper()
	if b, err := os.ReadFile(filepath.Join(dir, "source")); err == nil {
		dir = filepath.Join(dir, strings.TrimSpace(string(b)))
	}
	entries, err := os.ReadDir(dir)
	if err != nil {
		return false
	}
	for _, e := range entries {
		if e.IsDir() || filepath.Ext(e.Name()) != ".proto" {
			continue
		}
		b, err := os.ReadFile(filepath.Join(dir, e.Name()))
		if err != nil {
			continue
		}
		if containsImport(string(b), "entity/v1/annotations.proto") {
			return true
		}
	}
	return false
}

func containsImport(src, path string) bool {
	return strings.Contains(src, `import "`+path+`"`)
}
