package wire_test

// agreement_test.go holds the two protokit harnesses that check properties of a
// build rather than its bytes.
//
// IRAgreement is the one that matters for this plugin's place in the ecosystem.
// The whole reason the vocabulary was split is that a cache, a streams publisher
// and a docs generator over the same protos must derive the same tables and
// columns — otherwise a decorator generated by one plugin cannot address the
// rows persisted by another. Golden files cannot express that: they pin what
// *this* plugin emits, not what any other plugin would agree on.
//
// So the assertion is made against a plugin that reads no vocabulary at all —
// pure AIP plus protokit.v1. If the two disagree about a neutral name, something
// storage-specific has leaked into the structure, which is exactly the mistake
// the split exists to prevent.

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/the-protobuf-project/protokit"
	"github.com/the-protobuf-project/protokit/golden"
	"github.com/the-protobuf-project/protokit/schema"
	"github.com/the-protobuf-project/store/plugin/factory/wire"
)

// TestIRAgreement requires the store plugin and a bare protokit plugin to derive
// identical neutral facts for every case whose protos are written in
// protokit.v1.
//
// Cases still written in orm.v1 are skipped, and the skip is the point rather
// than an evasion: their structure arrives through the compat reader, so a bare
// protokit build genuinely sees different tables. That is a statement about the
// deprecated vocabulary — it is *not* neutral, which is why it is being retired —
// not a disagreement between plugins about protokit.v1.
func TestIRAgreement(t *testing.T) {
	for _, dir := range protokitV1Cases(t) {
		name := filepath.Base(dir)
		if synthesizesTables[name] {
			continue
		}
		t.Run(name, func(t *testing.T) {
			golden.IRAgreement(t, dir, ormCasePlugin(dir), bareProtokitPlugin(dir))
		})
	}
}

// synthesizesTables names the cases where this plugin deliberately adds a table
// that is not in the protos, so a bare protokit build cannot have it and the
// comparison is not meaningful.
//
// The outbox is the only one, and its absence from a bare build is correct
// rather than a leak: the companion table is a storage decision this plugin
// makes from (store.v1.table).outbox. A streams generator that needs to find it
// reads the same annotation and derives the same table — which is composition
// working, not the two disagreeing about what the protos say.
var synthesizesTables = map[string]bool{"outbox": true}

// TestDeterminism requires two builds of the same case to produce byte-identical
// output. Map iteration and unordered facet collection are the usual sources of
// drift, and both would otherwise show up as an intermittently failing golden
// diff that reruns "fix".
func TestDeterminism(t *testing.T) {
	for _, dir := range protokitV1Cases(t) {
		t.Run(filepath.Base(dir), func(t *testing.T) {
			golden.Determinism(t, dir, determinismPlugin(dir))
		})
	}
}

// determinismPlugin is the case's plugin with its registry narrowed to the
// database targets.
//
// Determinism runs every target in the registry when a case ships no "targets"
// file, and the repository target refuses to generate without the go_module and
// gorm_module opts that describe the trees it composes. Narrowing here keeps the
// harness testing what it is for — that two builds agree — instead of failing on
// a target the case was never configured for.
func determinismPlugin(dir string) protokit.Plugin {
	pl := ormCasePlugin(dir)
	reg := make(map[string]schema.Target, len(defaultTargets))
	for _, name := range defaultTargets {
		if tgt, ok := pl.Registry[name]; ok {
			reg[name] = tgt
		}
	}
	pl.Registry = reg
	return pl
}

// bareProtokitPlugin is a run with this plugin's targets but none of its
// vocabulary: no facet readers at all. What it derives is what any other
// protokit plugin would derive from the same protos.
//
// It does get the case's layout, and that is not a loophole — it is the
// distinction the LayoutResolver split exists to draw. The same protos generated
// under two different layouts *should* produce different database and schema
// names, because a layout is a deployment's choice; the same protos read by two
// different plugins should not, because an annotation is the schema's. Handing
// both sides the same layout is what leaves only the second difference visible,
// which is the one this test is about.
func bareProtokitPlugin(dir string) protokit.Plugin {
	return wire.Plugin(nil, ormCasePlugin(dir).Layout)
}

// protokitV1Cases lists the golden cases whose protos import protokit.v1, which
// are the ones a bare protokit build can read in full.
func protokitV1Cases(t *testing.T) []string {
	t.Helper()
	root := filepath.Join("testdata", "cases")
	entries, err := os.ReadDir(root)
	if err != nil {
		t.Fatalf("read cases: %v", err)
	}
	var out []string
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		dir := filepath.Join(root, e.Name())
		if usesProtokitV1(t, dir) {
			out = append(out, dir)
		}
	}
	if len(out) == 0 {
		t.Fatal("no protokit.v1 cases found; the harness would pass vacuously")
	}
	return out
}

// usesProtokitV1 reports whether any .proto the case compiles imports
// protokit.v1, following the "source" indirection a case may use to point at the
// shared examples tree.
func usesProtokitV1(t *testing.T, dir string) bool {
	t.Helper()
	if b, err := os.ReadFile(filepath.Join(dir, "source")); err == nil {
		dir = filepath.Join(dir, strings.TrimSpace(string(b)))
	}
	entries, err := os.ReadDir(dir)
	if err != nil {
		return false
	}
	for _, e := range entries {
		if e.IsDir() || filepath.Ext(e.Name()) != ".proto" {
			continue
		}
		b, err := os.ReadFile(filepath.Join(dir, e.Name()))
		if err != nil {
			continue
		}
		if containsImport(string(b), "protokit/v1/annotations.proto") {
			return true
		}
	}
	return false
}

func containsImport(src, path string) bool {
	return strings.Contains(src, `import "`+path+`"`)
}
