-- Code generated by protoc-gen-store. DO NOT EDIT.
-- versions:
-- 	protoc-gen-store (unknown)
-- 	protoc (unknown)
--
-- database: freebusy_db
-- schemas:  promocode, billing, common
--
-- Single-file migration: every schema in one transaction. Idempotent — safe to re-apply.
--
-- store — https://github.com/the-protobuf-project/store

BEGIN;

-- Schemas
CREATE SCHEMA IF NOT EXISTS "promocode";
CREATE SCHEMA IF NOT EXISTS "billing";
CREATE SCHEMA IF NOT EXISTS "common";

-- Tables (foreign keys are added after every table exists, so creation order
-- never matters — even across schemas or reference cycles).

-- PromoCode is a redeemable discount with a has-many set of redemptions.
CREATE TABLE IF NOT EXISTS "promocode"."promo_codes" (
    -- Unique identifier for the record.
    "id"  CHAR(26)  NOT NULL  PRIMARY KEY,
    -- Resource name; the AIP identifier.
    "name"  VARCHAR(255)  NOT NULL  UNIQUE,
    -- Foreign key to Money.
    "amount_off_id"  CHAR(26)
);

-- Redemption is one use of a promo code. As a repeated nested message it materializes into promocode.redemptions; its own Money field routes to the shared common.moneys, one schema level down from the parent.
CREATE TABLE IF NOT EXISTS "promocode"."redemptions" (
    -- Unique identifier for the record.
    "id"  CHAR(26)  NOT NULL  PRIMARY KEY,
    -- Customer who redeemed the code (resource name).
    "customer"  VARCHAR(255)  NOT NULL,
    -- When the code was redeemed.
    "redeemed_time"  TIMESTAMPTZ  NOT NULL,
    -- Foreign key to PromoCode.
    "promo_code_id"  CHAR(26)  NOT NULL,
    -- Foreign key to Money.
    "amount_applied_id"  CHAR(26)  NOT NULL
);

-- Invoice carries a total expressed as the shared Money value object.
CREATE TABLE IF NOT EXISTS "billing"."invoices" (
    -- Unique identifier for the record.
    "id"  CHAR(26)  NOT NULL  PRIMARY KEY,
    -- Resource name; the AIP identifier.
    "name"  VARCHAR(255)  NOT NULL  UNIQUE,
    -- Foreign key to Money.
    "total_id"  CHAR(26)  NOT NULL
);

-- Money is an amount of money with its currency type.
CREATE TABLE IF NOT EXISTS "common"."moneys" (
    -- Unique identifier for the record.
    "id"  CHAR(26)  NOT NULL  PRIMARY KEY,
    -- The three-letter ISO 4217 currency code.
    "currency_code"  VARCHAR(255),
    -- Whole units of the amount.
    "units"  BIGINT,
    -- Number of nano (10^-9) units of the amount.
    "nanos"  INTEGER
);

-- Foreign keys
ALTER TABLE "promocode"."promo_codes" DROP CONSTRAINT IF EXISTS "fk_promo_codes_amount_off_id";
ALTER TABLE "promocode"."promo_codes" ADD CONSTRAINT "fk_promo_codes_amount_off_id" FOREIGN KEY ("amount_off_id") REFERENCES "common"."moneys"("id") ON DELETE SET NULL;
ALTER TABLE "promocode"."redemptions" DROP CONSTRAINT IF EXISTS "fk_redemptions_promo_code_id";
ALTER TABLE "promocode"."redemptions" ADD CONSTRAINT "fk_redemptions_promo_code_id" FOREIGN KEY ("promo_code_id") REFERENCES "promocode"."promo_codes"("id") ON DELETE CASCADE;
ALTER TABLE "promocode"."redemptions" DROP CONSTRAINT IF EXISTS "fk_redemptions_amount_applied_id";
ALTER TABLE "promocode"."redemptions" ADD CONSTRAINT "fk_redemptions_amount_applied_id" FOREIGN KEY ("amount_applied_id") REFERENCES "common"."moneys"("id") ON DELETE CASCADE;
ALTER TABLE "billing"."invoices" DROP CONSTRAINT IF EXISTS "fk_invoices_total_id";
ALTER TABLE "billing"."invoices" ADD CONSTRAINT "fk_invoices_total_id" FOREIGN KEY ("total_id") REFERENCES "common"."moneys"("id") ON DELETE CASCADE;

-- Indexes
CREATE INDEX IF NOT EXISTS "idx_promo_codes_amount_off_id" ON "promocode"."promo_codes" ("amount_off_id");
CREATE INDEX IF NOT EXISTS "idx_redemptions_promo_code_id" ON "promocode"."redemptions" ("promo_code_id");
CREATE INDEX IF NOT EXISTS "idx_redemptions_amount_applied_id" ON "promocode"."redemptions" ("amount_applied_id");
CREATE INDEX IF NOT EXISTS "idx_invoices_total_id" ON "billing"."invoices" ("total_id");

-- Documentation
COMMENT ON TABLE "promocode"."promo_codes" IS 'PromoCode is a redeemable discount with a has-many set of redemptions.';
COMMENT ON COLUMN "promocode"."promo_codes"."id" IS 'Unique identifier for the record.';
COMMENT ON COLUMN "promocode"."promo_codes"."name" IS 'Resource name; the AIP identifier.';
COMMENT ON COLUMN "promocode"."promo_codes"."amount_off_id" IS 'Foreign key to Money.';
COMMENT ON TABLE "promocode"."redemptions" IS 'Redemption is one use of a promo code. As a repeated nested message it materializes into promocode.redemptions; its own Money field routes to the shared common.moneys, one schema level down from the parent.';
COMMENT ON COLUMN "promocode"."redemptions"."id" IS 'Unique identifier for the record.';
COMMENT ON COLUMN "promocode"."redemptions"."customer" IS 'Customer who redeemed the code (resource name).';
COMMENT ON COLUMN "promocode"."redemptions"."redeemed_time" IS 'When the code was redeemed.';
COMMENT ON COLUMN "promocode"."redemptions"."promo_code_id" IS 'Foreign key to PromoCode.';
COMMENT ON COLUMN "promocode"."redemptions"."amount_applied_id" IS 'Foreign key to Money.';
COMMENT ON TABLE "billing"."invoices" IS 'Invoice carries a total expressed as the shared Money value object.';
COMMENT ON COLUMN "billing"."invoices"."id" IS 'Unique identifier for the record.';
COMMENT ON COLUMN "billing"."invoices"."name" IS 'Resource name; the AIP identifier.';
COMMENT ON COLUMN "billing"."invoices"."total_id" IS 'Foreign key to Money.';
COMMENT ON TABLE "common"."moneys" IS 'Money is an amount of money with its currency type.';
COMMENT ON COLUMN "common"."moneys"."id" IS 'Unique identifier for the record.';
COMMENT ON COLUMN "common"."moneys"."currency_code" IS 'The three-letter ISO 4217 currency code.';
COMMENT ON COLUMN "common"."moneys"."units" IS 'Whole units of the amount.';
COMMENT ON COLUMN "common"."moneys"."nanos" IS 'Number of nano (10^-9) units of the amount.';

COMMIT;
