-- Code generated by protoc-gen-store. DO NOT EDIT.
-- versions:
-- 	protoc-gen-store (unknown)
-- 	protoc (unknown)
-- source: a_promo.proto
--
-- database: freebusy_db
-- schema:   promocode
--
-- store — https://github.com/the-protobuf-project/store

CREATE SCHEMA IF NOT EXISTS "promocode";

-- PromoCode is a redeemable discount with a has-many set of redemptions.
CREATE TABLE "promocode"."promo_codes" (
    -- Unique identifier for the record.
    "id"  CHAR(26)  NOT NULL  PRIMARY KEY,
    -- Resource name; the AIP identifier.
    "name"  VARCHAR(255)  NOT NULL  UNIQUE,
    -- Foreign key to Money.
    "amount_off_id"  CHAR(26),
    CONSTRAINT "fk_promo_codes_amount_off_id" FOREIGN KEY ("amount_off_id") REFERENCES "common"."moneys"("id") ON DELETE SET NULL
);
CREATE INDEX "idx_promo_codes_amount_off_id" ON "promocode"."promo_codes" ("amount_off_id");

-- Redemption is one use of a promo code. As a repeated nested message it materializes into promocode.redemptions; its own Money field routes to the shared common.moneys, one schema level down from the parent.
CREATE TABLE "promocode"."redemptions" (
    -- Unique identifier for the record.
    "id"  CHAR(26)  NOT NULL  PRIMARY KEY,
    -- Customer who redeemed the code (resource name).
    "customer"  VARCHAR(255)  NOT NULL,
    -- When the code was redeemed.
    "redeemed_time"  TIMESTAMPTZ  NOT NULL,
    -- Foreign key to PromoCode.
    "promo_code_id"  CHAR(26)  NOT NULL,
    -- Foreign key to Money.
    "amount_applied_id"  CHAR(26)  NOT NULL,
    CONSTRAINT "fk_redemptions_promo_code_id" FOREIGN KEY ("promo_code_id") REFERENCES "promocode"."promo_codes"("id") ON DELETE CASCADE,
    CONSTRAINT "fk_redemptions_amount_applied_id" FOREIGN KEY ("amount_applied_id") REFERENCES "common"."moneys"("id") ON DELETE CASCADE
);
CREATE INDEX "idx_redemptions_promo_code_id" ON "promocode"."redemptions" ("promo_code_id");
CREATE INDEX "idx_redemptions_amount_applied_id" ON "promocode"."redemptions" ("amount_applied_id");


-- Column and table documentation, persisted to the catalog.
COMMENT ON TABLE "promocode"."promo_codes" IS 'PromoCode is a redeemable discount with a has-many set of redemptions.';
COMMENT ON COLUMN "promocode"."promo_codes"."id" IS 'Unique identifier for the record.';
COMMENT ON COLUMN "promocode"."promo_codes"."name" IS 'Resource name; the AIP identifier.';
COMMENT ON COLUMN "promocode"."promo_codes"."amount_off_id" IS 'Foreign key to Money.';
COMMENT ON TABLE "promocode"."redemptions" IS 'Redemption is one use of a promo code. As a repeated nested message it materializes into promocode.redemptions; its own Money field routes to the shared common.moneys, one schema level down from the parent.';
COMMENT ON COLUMN "promocode"."redemptions"."id" IS 'Unique identifier for the record.';
COMMENT ON COLUMN "promocode"."redemptions"."customer" IS 'Customer who redeemed the code (resource name).';
COMMENT ON COLUMN "promocode"."redemptions"."redeemed_time" IS 'When the code was redeemed.';
COMMENT ON COLUMN "promocode"."redemptions"."promo_code_id" IS 'Foreign key to PromoCode.';
COMMENT ON COLUMN "promocode"."redemptions"."amount_applied_id" IS 'Foreign key to Money.';
