-- Code generated by protoc-gen-store. DO NOT EDIT.
-- versions:
-- 	protoc-gen-store (unknown)
-- 	protoc (unknown)
--
-- database: commerce
-- schemas:  shop_cart_v1, shop_order_v1
--
-- Single-file migration: every schema in one transaction. Idempotent — safe to re-apply.
-- annotations: entity.v1 (unknown), store.v1 (unknown)
-- engine:      protokit (unknown)
--
-- store — https://github.com/the-protobuf-project/store

BEGIN;

-- Schemas
CREATE SCHEMA IF NOT EXISTS "shop_cart_v1";
CREATE SCHEMA IF NOT EXISTS "shop_order_v1";

-- Enum types
-- Status enumerates cart payment states.
DO $$ BEGIN
    CREATE TYPE "shop_cart_v1"."status" AS ENUM ('PENDING', 'PAID');
EXCEPTION WHEN duplicate_object THEN null;
END $$;
-- Status enumerates order fulfillment states.
DO $$ BEGIN
    CREATE TYPE "shop_order_v1"."status" AS ENUM ('SHIPPED', 'DELIVERED');
EXCEPTION WHEN duplicate_object THEN null;
END $$;

-- Tables (foreign keys are added after every table exists, so creation order
-- never matters — even across schemas or reference cycles).

-- Money is a cart-side resource. Its simple name "Money" collides with the order-side Money once both packages merge into the "commerce" database (see store.yaml). Prisma qualifies the colliding model names (its models share one global namespace), while the schema-namespaced targets — GORM (one package per schema), SQL, and CSV — keep the bare "Money", since the schema already disambiguates them.
CREATE TABLE IF NOT EXISTS "shop_cart_v1"."moneys" (
    -- Unique identifier for the record.
    "id"  CHAR(26)  NOT NULL  PRIMARY KEY,
    -- Resource name; the AIP identifier.
    "name"  VARCHAR(255)  NOT NULL  UNIQUE,
    -- Amount in minor units.
    "amount"  BIGINT  NOT NULL,
    -- Status is a cart-side enum whose simple name collides with order.Status.
    "status"  "shop_cart_v1"."status"  NOT NULL  DEFAULT 'PENDING'
);

-- Money is the order-side resource sharing the simple name "Money" with the cart-side one. See cart.proto for how each target renders the collision.
CREATE TABLE IF NOT EXISTS "shop_order_v1"."moneys" (
    -- Unique identifier for the record.
    "id"  CHAR(26)  NOT NULL  PRIMARY KEY,
    -- Resource name; the AIP identifier.
    "name"  VARCHAR(255)  NOT NULL  UNIQUE,
    -- Amount in minor units.
    "amount"  BIGINT  NOT NULL,
    -- Status is an order-side enum whose simple name collides with cart.Status.
    "status"  "shop_order_v1"."status"  NOT NULL  DEFAULT 'SHIPPED'
);

-- Documentation
COMMENT ON TABLE "shop_cart_v1"."moneys" IS 'Money is a cart-side resource. Its simple name "Money" collides with the order-side Money once both packages merge into the "commerce" database (see store.yaml). Prisma qualifies the colliding model names (its models share one global namespace), while the schema-namespaced targets — GORM (one package per schema), SQL, and CSV — keep the bare "Money", since the schema already disambiguates them.';
COMMENT ON COLUMN "shop_cart_v1"."moneys"."id" IS 'Unique identifier for the record.';
COMMENT ON COLUMN "shop_cart_v1"."moneys"."name" IS 'Resource name; the AIP identifier.';
COMMENT ON COLUMN "shop_cart_v1"."moneys"."amount" IS 'Amount in minor units.';
COMMENT ON COLUMN "shop_cart_v1"."moneys"."status" IS 'Status is a cart-side enum whose simple name collides with order.Status.';
COMMENT ON TABLE "shop_order_v1"."moneys" IS 'Money is the order-side resource sharing the simple name "Money" with the cart-side one. See cart.proto for how each target renders the collision.';
COMMENT ON COLUMN "shop_order_v1"."moneys"."id" IS 'Unique identifier for the record.';
COMMENT ON COLUMN "shop_order_v1"."moneys"."name" IS 'Resource name; the AIP identifier.';
COMMENT ON COLUMN "shop_order_v1"."moneys"."amount" IS 'Amount in minor units.';
COMMENT ON COLUMN "shop_order_v1"."moneys"."status" IS 'Status is an order-side enum whose simple name collides with cart.Status.';

COMMIT;
