// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store (unknown)
// 	protoc (unknown)
// source: versionedpkg.proto
//
// database: v1
// schema:   resource_v1
//
// annotations: entity.v1 (unknown), store.v1 (unknown)
// engine:      protokit (unknown)
// runtime:     gorm.io/gorm
//
// store — https://github.com/the-protobuf-project/store

package resourcev1

import (
	"context"

	"example.com/test/gen/gormx"
	"gorm.io/gorm"
)

// EventStoreIface is the full data-access surface of Event: everything
// EventStore does, as an interface.
//
// It exists so a decorator — caching, tracing, retries, a test double — can be
// written in its own package against this contract, without that package needing
// to edit anything in this tree. Embed it, override the methods you care about,
// and delegate the rest:
//
//	type cachedEventStore struct {
//		EventStoreIface
//		cache Cache
//	}
//
// Construction is deliberately absent. NewEventStore returns the concrete
// *EventStore, and WithTelemetry is a chainable setter that also returns it, so
// a caller keeps the full type at the point of wiring and narrows to this
// interface at the point of use — which is the direction that stays useful when
// a decorator is added later.
type EventStoreIface interface {
	Create(ctx context.Context, m *Event) error
	List(ctx context.Context, opts gormx.ListOptions) ([]Event, error)
	Count(ctx context.Context, opts gormx.ListOptions) (int64, error)
	Update(ctx context.Context, m *Event) error
	GetByID(ctx context.Context, id string) (*Event, error)
	DeleteByID(ctx context.Context, id string) error
	GetByName(ctx context.Context, v string) (*Event, error)
	ListByWindowID(ctx context.Context, id string, opts gormx.ListOptions) ([]Event, error)
}

// EventStore provides typed CRUD access to Event records.
// Event is the resource: it drives both the repository interfaces and the gorm converters, the two targets that qualify proto types.
type EventStore struct {
	DB *gorm.DB
	// Telemetry observes every operation; nil is a no-op. Wire the generated
	// adapter: NewEventStore(db).WithTelemetry(telemetry.New(o)).
	Telemetry gormx.Telemetry
}

// Compile-time proof that EventStore implements its own interface. Without it a
// signature could drift from EventStoreIface and only break in whichever downstream
// package decorates it.
var _ EventStoreIface = (*EventStore)(nil)

// Compile-time proof that EventStore satisfies the generic gormx.Store, so the
// generic engine can drive it alongside the typed finders below.
var _ gormx.Store[Event] = (*EventStore)(nil)

// NewEventStore returns a EventStore backed by db.
func NewEventStore(db *gorm.DB) *EventStore { return &EventStore{DB: db} }

// WithTelemetry sets the store's Telemetry and returns the store for chaining.
func (s *EventStore) WithTelemetry(t gormx.Telemetry) *EventStore {
	s.Telemetry = t
	return s
}

// Create inserts m.
func (s *EventStore) Create(ctx context.Context, m *Event) error {
	return s.DB.WithContext(ctx).Create(m).Error
}

// List returns the Event records matching opts.
func (s *EventStore) List(ctx context.Context, opts gormx.ListOptions) ([]Event, error) {
	var out []Event
	if err := opts.Apply(s.DB.WithContext(ctx)).Find(&out).Error; err != nil {
		return nil, err
	}
	return out, nil
}

// Count returns the number of Event records matching opts.Where
// (pagination and ordering are ignored).
func (s *EventStore) Count(ctx context.Context, opts gormx.ListOptions) (int64, error) {
	var n int64
	db := s.DB.WithContext(ctx).Model(&Event{})
	if opts.Where != nil {
		db = db.Where(opts.Where, opts.Args...)
	}
	if err := db.Count(&n).Error; err != nil {
		return 0, err
	}
	return n, nil
}

// Update persists every field of m, which must carry its primary key.
func (s *EventStore) Update(ctx context.Context, m *Event) error {
	return s.DB.WithContext(ctx).Save(m).Error
}

// GetByID fetches the Event with the given primary key.
func (s *EventStore) GetByID(ctx context.Context, id string) (*Event, error) {
	var m Event
	if err := s.DB.WithContext(ctx).First(&m, "id = ?", id).Error; err != nil {
		return nil, err
	}
	return &m, nil
}

// DeleteByID removes the Event with the given primary key.
func (s *EventStore) DeleteByID(ctx context.Context, id string) error {
	return s.DB.WithContext(ctx).Delete(&Event{}, "id = ?", id).Error
}

// GetByName fetches the Event with the given name (a unique column).
func (s *EventStore) GetByName(ctx context.Context, v string) (*Event, error) {
	var m Event
	if err := s.DB.WithContext(ctx).First(&m, "name = ?", v).Error; err != nil {
		return nil, err
	}
	return &m, nil
}

// ListByWindowID returns the Event records whose window_id matches id, with opts applied.
func (s *EventStore) ListByWindowID(ctx context.Context, id string, opts gormx.ListOptions) ([]Event, error) {
	var out []Event
	q := opts.Apply(s.DB.WithContext(ctx).Where("window_id = ?", id))
	if err := q.Find(&out).Error; err != nil {
		return nil, err
	}
	return out, nil
}
