// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store (unknown)
// 	protoc (unknown)
// source: versionedpkg.proto
//
// database: v1
// schema:   resource_v1
//
// annotations: entity.v1 (unknown), store.v1 (unknown)
// engine:      protokit v1.2.1
//
// store — https://github.com/the-protobuf-project/store

package resourcev1

import (
	"time"
)

// State exercises the enum path, whose qualifier is resolved from the enum's own ident rather than the message's.
type State string

// State values as stored in the database.
const (
	StateActive   State = "ACTIVE"
	StateArchived State = "ARCHIVED"
)

// Event is the resource: it drives both the repository interfaces and the gorm converters, the two targets that qualify proto types.
type Event struct {
	// Unique identifier for the record.
	ID string `gorm:"column:id;primaryKey;not null" json:"id"`
	// Resource name; the AIP identifier.
	Name string `gorm:"column:name;not null;uniqueIndex" json:"name" validate:"required"`
	// Human-friendly name.
	DisplayName string `gorm:"column:display_name;not null" json:"display_name" validate:"required"`
	// Lifecycle state, qualified through the enum's own package.
	State *State `gorm:"column:state;check:chk_events_state,state IN ('ACTIVE','ARCHIVED')" json:"state,omitempty"`
	// Creation timestamp, exercising the well-known-type imports alongside.
	CreateTime time.Time `gorm:"column:create_time;type:timestamptz;not null;autoCreateTime" json:"create_time"`
	// Foreign key to Window.
	WindowID *string `gorm:"column:window_id;index:idx_events_window_id" json:"window_id,omitempty"`
	Window   *Window `gorm:"foreignKey:WindowID;constraint:OnDelete:SET NULL" json:"window,omitempty"`
}

func (*Event) TableName() string { return "resource_v1.events" }

// Window is a value object: it relationalizes to its own table, so converters render a message-typed field's qualifier too.
type Window struct {
	// Unique identifier for the record.
	ID string `gorm:"column:id;primaryKey;not null" json:"id"`
	// Window start.
	StartTime time.Time `gorm:"column:start_time;type:timestamptz;not null" json:"start_time" validate:"required"`
	// Window end.
	EndTime *time.Time `gorm:"column:end_time;type:timestamptz" json:"end_time,omitempty"`
	// Back-relation: Event records that reference this via window_id.
	Events []Event `gorm:"foreignKey:WindowID" json:"events,omitempty"`
}

func (*Window) TableName() string { return "resource_v1.windows" }
