// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store (unknown)
// 	protoc (unknown)
// source: versionedpkg.proto
//
// database: v1
// schema:   resource_v1
//
// annotations: entity.v1 (unknown), store.v1 (unknown)
// engine:      protokit v1.2.1
//
// store — https://github.com/the-protobuf-project/store

package resourcev1

import (
	"time"

	resourcev1 "example.com/test/gen"
	"google.golang.org/protobuf/types/known/timestamppb"
)

// StateFromProto maps the proto enum onto its stored form ("" for
// unspecified or unknown values, so the column is omitted / left to default).
func StateFromProto(v resourcev1.State) State {
	switch v {
	case resourcev1.State_STATE_ACTIVE:
		return StateActive
	case resourcev1.State_STATE_ARCHIVED:
		return StateArchived
	}
	return ""
}

// StateToProto maps the stored form back onto the proto enum
// (unspecified for empty or unknown values).
func StateToProto(v State) resourcev1.State {
	switch v {
	case StateActive:
		return resourcev1.State_STATE_ACTIVE
	case StateArchived:
		return resourcev1.State_STATE_ARCHIVED
	}
	return 0
}

// StatePtrFromProto is StateFromProto for nullable columns:
// unspecified maps to nil.
func StatePtrFromProto(v resourcev1.State) *State {
	if s := StateFromProto(v); s != "" {
		return &s
	}
	return nil
}

// StatePtrToProto is StateToProto for nullable columns.
func StatePtrToProto(v *State) resourcev1.State {
	if v == nil {
		return 0
	}
	return StateToProto(*v)
}

// EventToProto converts the stored row (with its belongs-to associations,
// when preloaded) to its proto message. Nil in, nil out.
func EventToProto(m *Event) *resourcev1.Event {
	if m == nil {
		return nil
	}
	out := &resourcev1.Event{}
	out.Name = m.Name
	out.DisplayName = m.DisplayName
	out.State = StatePtrToProto(m.State)
	out.CreateTime = goValToTs(m.CreateTime)
	out.Window = WindowToProto(m.Window)
	return out
}

// EventFromProto maps the proto message's data fields onto a fresh row.
// It never invents keys or relations: primary keys, resource references, and
// sub-row graph wiring stay with the caller. Nil in, nil out.
func EventFromProto(pb *resourcev1.Event) *Event {
	if pb == nil {
		return nil
	}
	m := &Event{}
	// not mapped here: window (sub-row graph)
	m.Name = pb.GetName()
	m.DisplayName = pb.GetDisplayName()
	m.State = StatePtrFromProto(pb.GetState())
	return m
}

// WindowToProto converts the stored row (with its belongs-to associations,
// when preloaded) to its proto message. Nil in, nil out.
func WindowToProto(m *Window) *resourcev1.Window {
	if m == nil {
		return nil
	}
	out := &resourcev1.Window{}
	out.StartTime = goValToTs(m.StartTime)
	out.EndTime = goToTs(m.EndTime)
	return out
}

// WindowFromProto maps the proto message's data fields onto a fresh row.
// It never invents keys or relations: primary keys, resource references, and
// sub-row graph wiring stay with the caller. Nil in, nil out.
func WindowFromProto(pb *resourcev1.Window) *Window {
	if pb == nil {
		return nil
	}
	m := &Window{}
	m.StartTime = tsToGoVal(pb.GetStartTime())
	m.EndTime = tsToGo(pb.GetEndTime())
	return m
}

// tsToGo maps a proto timestamp onto a nullable TIMESTAMPTZ value.
func tsToGo(ts *timestamppb.Timestamp) *time.Time {
	if ts == nil {
		return nil
	}
	t := ts.AsTime()
	return &t
}

// tsToGoVal maps a proto timestamp onto a NOT NULL TIMESTAMPTZ value.
func tsToGoVal(ts *timestamppb.Timestamp) time.Time {
	if ts == nil {
		return time.Time{}
	}
	return ts.AsTime()
}

// goToTs maps a nullable TIMESTAMPTZ value back onto a proto timestamp.
func goToTs(t *time.Time) *timestamppb.Timestamp {
	if t == nil || t.IsZero() {
		return nil
	}
	return timestamppb.New(*t)
}

// goValToTs maps a NOT NULL TIMESTAMPTZ value back onto a proto timestamp.
func goValToTs(t time.Time) *timestamppb.Timestamp {
	if t.IsZero() {
		return nil
	}
	return timestamppb.New(t)
}
