-- Code generated by protoc-gen-store. DO NOT EDIT.
-- versions:
-- 	protoc-gen-store (unknown)
-- 	protoc (unknown)
--
-- database: v1
-- schemas:  parentref_v1
--
-- Single-file migration: every schema in one transaction. Idempotent — safe to re-apply.
-- annotations: protokit.v1 (unknown), store.v1 (unknown)
--
-- store — https://github.com/the-protobuf-project/store

BEGIN;

-- Schemas
CREATE SCHEMA IF NOT EXISTS "parentref_v1";

-- Tables (foreign keys are added after every table exists, so creation order
-- never matters — even across schemas or reference cycles).

-- User is the parent resource.
CREATE TABLE IF NOT EXISTS "parentref_v1"."users" (
    -- Unique identifier for the record.
    "id"  CHAR(26)  NOT NULL  PRIMARY KEY,
    -- Resource name; the AIP identifier.
    "name"  VARCHAR(255)  NOT NULL  UNIQUE,
    -- display_name is shown in UIs.
    "display_name"  VARCHAR(255)  NOT NULL
);

-- Note is owned by a User. Its pattern carries a {user} parent segment with no corresponding field, so orm materializes a user_id FK → User from the pattern alone.
CREATE TABLE IF NOT EXISTS "parentref_v1"."notes" (
    -- Unique identifier for the record.
    "id"  CHAR(26)  NOT NULL  PRIMARY KEY,
    -- Resource name; the AIP identifier.
    "name"  VARCHAR(255)  NOT NULL  UNIQUE,
    -- body is the note's text.
    "body"  VARCHAR(255)  NOT NULL,
    -- Parent reference to User (from the AIP resource pattern).
    "user_id"  CHAR(26)  NOT NULL
);

-- Foreign keys
ALTER TABLE "parentref_v1"."notes" DROP CONSTRAINT IF EXISTS "fk_notes_user_id";
ALTER TABLE "parentref_v1"."notes" ADD CONSTRAINT "fk_notes_user_id" FOREIGN KEY ("user_id") REFERENCES "parentref_v1"."users"("id") ON DELETE CASCADE;

-- Indexes
CREATE INDEX IF NOT EXISTS "idx_notes_user_id" ON "parentref_v1"."notes" ("user_id");

-- Documentation
COMMENT ON TABLE "parentref_v1"."users" IS 'User is the parent resource.';
COMMENT ON COLUMN "parentref_v1"."users"."id" IS 'Unique identifier for the record.';
COMMENT ON COLUMN "parentref_v1"."users"."name" IS 'Resource name; the AIP identifier.';
COMMENT ON COLUMN "parentref_v1"."users"."display_name" IS 'display_name is shown in UIs.';
COMMENT ON TABLE "parentref_v1"."notes" IS 'Note is owned by a User. Its pattern carries a {user} parent segment with no corresponding field, so orm materializes a user_id FK → User from the pattern alone.';
COMMENT ON COLUMN "parentref_v1"."notes"."id" IS 'Unique identifier for the record.';
COMMENT ON COLUMN "parentref_v1"."notes"."name" IS 'Resource name; the AIP identifier.';
COMMENT ON COLUMN "parentref_v1"."notes"."body" IS 'body is the note''s text.';
COMMENT ON COLUMN "parentref_v1"."notes"."user_id" IS 'Parent reference to User (from the AIP resource pattern).';

COMMIT;
