// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm (unknown)
// 	protoc (unknown)
// source: billing.proto
//
// database: billing_db
// schema:   acme_billing
//
// orm — https://github.com/the-protobuf-project/orm

package acmebilling

// Invoice lands in schema "acme_billing", not "acme_billing_v1": the orm.yaml strip_version option flattens the trailing API version out of the resource-type-derived schema name.
type Invoice struct {
	// Unique identifier for the record.
	ID string `gorm:"column:id;type:char(26);primaryKey;not null" json:"id"`
	// Resource name; the AIP identifier.
	Name string `gorm:"column:name;type:varchar(255);not null;uniqueIndex" json:"name" validate:"required"`
	// Amount due, in minor units.
	Amount string `gorm:"column:amount;type:varchar(255);not null" json:"amount" validate:"required"`
}

func (*Invoice) TableName() string { return "acme_billing.invoices" }
