// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store (unknown)
// 	protoc (unknown)
// source: billing.proto
//
// database: billing_db
// schema:   acme_billing
//
// annotations: protokit.v1 (unknown), store.v1 (unknown)
//
// store — https://github.com/the-protobuf-project/store

package acmebilling

// Invoice lands in schema "acme_billing", not "acme_billing_v1": the store.yaml strip_version option flattens the trailing API version out of the resource-type-derived schema name.
type Invoice struct {
	// Unique identifier for the record.
	ID string `gorm:"column:id;primaryKey;not null" json:"id"`
	// Resource name; the AIP identifier.
	Name string `gorm:"column:name;not null;uniqueIndex" json:"name" validate:"required"`
	// Amount due, in minor units.
	Amount string `gorm:"column:amount;not null" json:"amount" validate:"required"`
}

func (*Invoice) TableName() string { return "acme_billing.invoices" }
