-- Code generated by protoc-gen-store. DO NOT EDIT.
-- versions:
-- 	protoc-gen-store (unknown)
-- 	protoc (unknown)
--
-- database: fleet
-- schemas:  fleet_tracking_device
--
-- Single-file migration: every schema in one transaction. Idempotent — safe to re-apply.
-- annotations: protokit.v1 (unknown), store.v1 (unknown)
--
-- store — https://github.com/the-protobuf-project/store

BEGIN;

-- Schemas
CREATE SCHEMA IF NOT EXISTS "fleet_tracking_device";

-- Tables (foreign keys are added after every table exists, so creation order
-- never matters — even across schemas or reference cycles).

-- Tracker is a fleet device resource. The layout config routes it to the "fleet" database, schema "fleet_tracking_device".
CREATE TABLE IF NOT EXISTS "fleet_tracking_device"."trackers" (
    -- Unique identifier for the record.
    "id"  CHAR(26)  NOT NULL  PRIMARY KEY,
    -- Resource name; the AIP identifier.
    "name"  VARCHAR(255)  NOT NULL  UNIQUE,
    -- serial is the device's hardware serial number.
    "serial"  VARCHAR(255)  NOT NULL
);

-- Documentation
COMMENT ON TABLE "fleet_tracking_device"."trackers" IS 'Tracker is a fleet device resource. The layout config routes it to the "fleet" database, schema "fleet_tracking_device".';
COMMENT ON COLUMN "fleet_tracking_device"."trackers"."id" IS 'Unique identifier for the record.';
COMMENT ON COLUMN "fleet_tracking_device"."trackers"."name" IS 'Resource name; the AIP identifier.';
COMMENT ON COLUMN "fleet_tracking_device"."trackers"."serial" IS 'serial is the device''s hardware serial number.';

COMMIT;
