// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store (unknown)
// 	protoc (unknown)
// source: telemetryv1.proto
//
// database: weather_db
// schema:   weather
//
// store — https://github.com/the-protobuf-project/store

package weather

import (
	"context"
	"time"

	"example.com/test/gen/gormx"
	"gorm.io/gorm"
)

// ReadingStoreIface is the full data-access surface of Reading: everything
// ReadingStore does, as an interface.
//
// It exists so a decorator — caching, tracing, retries, a test double — can be
// written in its own package against this contract, without that package needing
// to edit anything in this tree. Embed it, override the methods you care about,
// and delegate the rest:
//
//	type cachedReadingStore struct {
//		ReadingStoreIface
//		cache Cache
//	}
//
// Construction is deliberately absent. NewReadingStore returns the concrete
// *ReadingStore, and WithTelemetry is a chainable setter that also returns it, so
// a caller keeps the full type at the point of wiring and narrows to this
// interface at the point of use — which is the direction that stays useful when
// a decorator is added later.
type ReadingStoreIface interface {
	Create(ctx context.Context, m *Reading) error
	List(ctx context.Context, opts gormx.ListOptions) ([]Reading, error)
	Count(ctx context.Context, opts gormx.ListOptions) (int64, error)
	Update(ctx context.Context, m *Reading) error
	GetByID(ctx context.Context, id string) (*Reading, error)
	DeleteByID(ctx context.Context, id string) error
	GetByName(ctx context.Context, v string) (*Reading, error)
}

// ReadingStore provides typed CRUD access to Reading records.
// Reading exercises the telemetry emitter's default path: instrumented store methods with a default span prefix, and labeled fields carrying span attribute struct tags (one default name, one explicit override). Annotated with telemetry.v1's own (telemetry.v1.telemetry) / (telemetry.v1.telemetry_field) options — orm.v1 carries no telemetry extensions of its own.
type ReadingStore struct {
	DB *gorm.DB
	// Telemetry observes every operation; nil is a no-op. Wire the generated
	// adapter: NewReadingStore(db).WithTelemetry(telemetry.New(o)).
	Telemetry gormx.Telemetry
}

// Compile-time proof that ReadingStore implements its own interface. Without it a
// signature could drift from ReadingStoreIface and only break in whichever downstream
// package decorates it.
var _ ReadingStoreIface = (*ReadingStore)(nil)

// Compile-time proof that ReadingStore satisfies the generic gormx.Store, so the
// generic engine can drive it alongside the typed finders below.
var _ gormx.Store[Reading] = (*ReadingStore)(nil)

// NewReadingStore returns a ReadingStore backed by db.
func NewReadingStore(db *gorm.DB) *ReadingStore { return &ReadingStore{DB: db} }

// WithTelemetry sets the store's Telemetry and returns the store for chaining.
func (s *ReadingStore) WithTelemetry(t gormx.Telemetry) *ReadingStore {
	s.Telemetry = t
	return s
}

// Create inserts m.
func (s *ReadingStore) Create(ctx context.Context, m *Reading) error {
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "weather.Reading/Create", m, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).Create(m).Error
	})
	tel.RecordOp(ctx, "weather.readings", "create", time.Since(start), err)
	return err
}

// List returns the Reading records matching opts.
func (s *ReadingStore) List(ctx context.Context, opts gormx.ListOptions) ([]Reading, error) {
	var out []Reading
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "weather.Reading/List", nil, func(ctx context.Context) error {
		return opts.Apply(s.DB.WithContext(ctx)).Find(&out).Error
	})
	tel.RecordOp(ctx, "weather.readings", "list", time.Since(start), err)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Count returns the number of Reading records matching opts.Where
// (pagination and ordering are ignored).
func (s *ReadingStore) Count(ctx context.Context, opts gormx.ListOptions) (int64, error) {
	var n int64
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "weather.Reading/Count", nil, func(ctx context.Context) error {
		db := s.DB.WithContext(ctx).Model(&Reading{})
		if opts.Where != nil {
			db = db.Where(opts.Where, opts.Args...)
		}
		return db.Count(&n).Error
	})
	tel.RecordOp(ctx, "weather.readings", "count", time.Since(start), err)
	if err != nil {
		return 0, err
	}
	return n, nil
}

// Update persists every field of m, which must carry its primary key.
func (s *ReadingStore) Update(ctx context.Context, m *Reading) error {
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "weather.Reading/Update", m, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).Save(m).Error
	})
	tel.RecordOp(ctx, "weather.readings", "update", time.Since(start), err)
	return err
}

// GetByID fetches the Reading with the given primary key.
func (s *ReadingStore) GetByID(ctx context.Context, id string) (*Reading, error) {
	var m Reading
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "weather.Reading/GetByID", nil, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).First(&m, "id = ?", id).Error
	})
	tel.RecordOp(ctx, "weather.readings", "get", time.Since(start), err)
	if err != nil {
		return nil, err
	}
	return &m, nil
}

// DeleteByID removes the Reading with the given primary key.
func (s *ReadingStore) DeleteByID(ctx context.Context, id string) error {
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "weather.Reading/DeleteByID", nil, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).Delete(&Reading{}, "id = ?", id).Error
	})
	tel.RecordOp(ctx, "weather.readings", "delete", time.Since(start), err)
	return err
}

// GetByName fetches the Reading with the given name (a unique column).
func (s *ReadingStore) GetByName(ctx context.Context, v string) (*Reading, error) {
	var m Reading
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "weather.Reading/GetByName", nil, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).First(&m, "name = ?", v).Error
	})
	tel.RecordOp(ctx, "weather.readings", "get_by_name", time.Since(start), err)
	if err != nil {
		return nil, err
	}
	return &m, nil
}
