// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store (unknown)
// 	protoc (unknown)
// source: telemetryv1.proto
//
// database: weather_db
// schema:   weather
//
// annotations: entity.v1 (unknown), store.v1 (unknown)
// engine:      protokit (unknown)
// runtime:     gorm.io/gorm
//
// store — https://github.com/the-protobuf-project/store

package weather

import (
	"context"

	"example.com/test/gen/gormx"
	"gorm.io/gorm"
)

// SensorStoreIface is the full data-access surface of Sensor: everything
// SensorStore does, as an interface.
//
// It exists so a decorator — caching, tracing, retries, a test double — can be
// written in its own package against this contract, without that package needing
// to edit anything in this tree. Embed it, override the methods you care about,
// and delegate the rest:
//
//	type cachedSensorStore struct {
//		SensorStoreIface
//		cache Cache
//	}
//
// Construction is deliberately absent. NewSensorStore returns the concrete
// *SensorStore, and WithTelemetry is a chainable setter that also returns it, so
// a caller keeps the full type at the point of wiring and narrows to this
// interface at the point of use — which is the direction that stays useful when
// a decorator is added later.
type SensorStoreIface interface {
	Create(ctx context.Context, m *Sensor) error
	List(ctx context.Context, opts gormx.ListOptions) ([]Sensor, error)
	Count(ctx context.Context, opts gormx.ListOptions) (int64, error)
	Update(ctx context.Context, m *Sensor) error
	GetByID(ctx context.Context, id string) (*Sensor, error)
	DeleteByID(ctx context.Context, id string) error
	GetByName(ctx context.Context, v string) (*Sensor, error)
}

// SensorStore provides typed CRUD access to Sensor records.
// Sensor overrides the span prefix and disables its op metrics, keeping spans only.
type SensorStore struct {
	DB *gorm.DB
	// Telemetry observes every operation; nil is a no-op. Wire the generated
	// adapter: NewSensorStore(db).WithTelemetry(telemetry.New(o)).
	Telemetry gormx.Telemetry
}

// Compile-time proof that SensorStore implements its own interface. Without it a
// signature could drift from SensorStoreIface and only break in whichever downstream
// package decorates it.
var _ SensorStoreIface = (*SensorStore)(nil)

// Compile-time proof that SensorStore satisfies the generic gormx.Store, so the
// generic engine can drive it alongside the typed finders below.
var _ gormx.Store[Sensor] = (*SensorStore)(nil)

// NewSensorStore returns a SensorStore backed by db.
func NewSensorStore(db *gorm.DB) *SensorStore { return &SensorStore{DB: db} }

// WithTelemetry sets the store's Telemetry and returns the store for chaining.
func (s *SensorStore) WithTelemetry(t gormx.Telemetry) *SensorStore {
	s.Telemetry = t
	return s
}

// Create inserts m.
func (s *SensorStore) Create(ctx context.Context, m *Sensor) error {
	tel := gormx.OrNop(s.Telemetry)
	err := tel.Span(ctx, "weather.Sensor/Create", m, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).Create(m).Error
	})
	return err
}

// List returns the Sensor records matching opts.
func (s *SensorStore) List(ctx context.Context, opts gormx.ListOptions) ([]Sensor, error) {
	var out []Sensor
	tel := gormx.OrNop(s.Telemetry)
	err := tel.Span(ctx, "weather.Sensor/List", nil, func(ctx context.Context) error {
		return opts.Apply(s.DB.WithContext(ctx)).Find(&out).Error
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Count returns the number of Sensor records matching opts.Where
// (pagination and ordering are ignored).
func (s *SensorStore) Count(ctx context.Context, opts gormx.ListOptions) (int64, error) {
	var n int64
	tel := gormx.OrNop(s.Telemetry)
	err := tel.Span(ctx, "weather.Sensor/Count", nil, func(ctx context.Context) error {
		db := s.DB.WithContext(ctx).Model(&Sensor{})
		if opts.Where != nil {
			db = db.Where(opts.Where, opts.Args...)
		}
		return db.Count(&n).Error
	})
	if err != nil {
		return 0, err
	}
	return n, nil
}

// Update persists every field of m, which must carry its primary key.
func (s *SensorStore) Update(ctx context.Context, m *Sensor) error {
	tel := gormx.OrNop(s.Telemetry)
	err := tel.Span(ctx, "weather.Sensor/Update", m, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).Save(m).Error
	})
	return err
}

// GetByID fetches the Sensor with the given primary key.
func (s *SensorStore) GetByID(ctx context.Context, id string) (*Sensor, error) {
	var m Sensor
	tel := gormx.OrNop(s.Telemetry)
	err := tel.Span(ctx, "weather.Sensor/GetByID", nil, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).First(&m, "id = ?", id).Error
	})
	if err != nil {
		return nil, err
	}
	return &m, nil
}

// DeleteByID removes the Sensor with the given primary key.
func (s *SensorStore) DeleteByID(ctx context.Context, id string) error {
	tel := gormx.OrNop(s.Telemetry)
	err := tel.Span(ctx, "weather.Sensor/DeleteByID", nil, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).Delete(&Sensor{}, "id = ?", id).Error
	})
	return err
}

// GetByName fetches the Sensor with the given name (a unique column).
func (s *SensorStore) GetByName(ctx context.Context, v string) (*Sensor, error) {
	var m Sensor
	tel := gormx.OrNop(s.Telemetry)
	err := tel.Span(ctx, "weather.Sensor/GetByName", nil, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).First(&m, "name = ?", v).Error
	})
	if err != nil {
		return nil, err
	}
	return &m, nil
}
