// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store (unknown)
// 	protoc (unknown)
// source: uniqueindex.proto
//
// database: promo_db
// schema:   promo
//
// annotations: protokit.v1 (unknown), store.v1 (unknown)
// runtime:     gorm.io/gorm
//
// store — https://github.com/the-protobuf-project/store

package promo

import (
	"context"

	"example.com/test/gen/gormx"
	"gorm.io/gorm"
)

// PromoCodeStoreIface is the full data-access surface of PromoCode: everything
// PromoCodeStore does, as an interface.
//
// It exists so a decorator — caching, tracing, retries, a test double — can be
// written in its own package against this contract, without that package needing
// to edit anything in this tree. Embed it, override the methods you care about,
// and delegate the rest:
//
//	type cachedPromoCodeStore struct {
//		PromoCodeStoreIface
//		cache Cache
//	}
//
// Construction is deliberately absent. NewPromoCodeStore returns the concrete
// *PromoCodeStore, and WithTelemetry is a chainable setter that also returns it, so
// a caller keeps the full type at the point of wiring and narrows to this
// interface at the point of use — which is the direction that stays useful when
// a decorator is added later.
type PromoCodeStoreIface interface {
	Create(ctx context.Context, m *PromoCode) error
	List(ctx context.Context, opts gormx.ListOptions) ([]PromoCode, error)
	Count(ctx context.Context, opts gormx.ListOptions) (int64, error)
	Update(ctx context.Context, m *PromoCode) error
	GetByID(ctx context.Context, id string) (*PromoCode, error)
	DeleteByID(ctx context.Context, id string) error
	GetByName(ctx context.Context, v string) (*PromoCode, error)
	GetByCode(ctx context.Context, v string) (*PromoCode, error)
}

// PromoCodeStore provides typed CRUD access to PromoCode records.
// PromoCode is a redeemable promotion. The human-facing `code` is unique via a single-column unique index, so store emits GetByCode alongside GetByID and the GetByName finder for the AIP resource name.
type PromoCodeStore struct {
	DB *gorm.DB
	// Telemetry observes every operation; nil is a no-op. Wire the generated
	// adapter: NewPromoCodeStore(db).WithTelemetry(telemetry.New(o)).
	Telemetry gormx.Telemetry
}

// Compile-time proof that PromoCodeStore implements its own interface. Without it a
// signature could drift from PromoCodeStoreIface and only break in whichever downstream
// package decorates it.
var _ PromoCodeStoreIface = (*PromoCodeStore)(nil)

// Compile-time proof that PromoCodeStore satisfies the generic gormx.Store, so the
// generic engine can drive it alongside the typed finders below.
var _ gormx.Store[PromoCode] = (*PromoCodeStore)(nil)

// NewPromoCodeStore returns a PromoCodeStore backed by db.
func NewPromoCodeStore(db *gorm.DB) *PromoCodeStore { return &PromoCodeStore{DB: db} }

// WithTelemetry sets the store's Telemetry and returns the store for chaining.
func (s *PromoCodeStore) WithTelemetry(t gormx.Telemetry) *PromoCodeStore {
	s.Telemetry = t
	return s
}

// Create inserts m.
func (s *PromoCodeStore) Create(ctx context.Context, m *PromoCode) error {
	return s.DB.WithContext(ctx).Create(m).Error
}

// List returns the PromoCode records matching opts.
func (s *PromoCodeStore) List(ctx context.Context, opts gormx.ListOptions) ([]PromoCode, error) {
	var out []PromoCode
	if err := opts.Apply(s.DB.WithContext(ctx)).Find(&out).Error; err != nil {
		return nil, err
	}
	return out, nil
}

// Count returns the number of PromoCode records matching opts.Where
// (pagination and ordering are ignored).
func (s *PromoCodeStore) Count(ctx context.Context, opts gormx.ListOptions) (int64, error) {
	var n int64
	db := s.DB.WithContext(ctx).Model(&PromoCode{})
	if opts.Where != nil {
		db = db.Where(opts.Where, opts.Args...)
	}
	if err := db.Count(&n).Error; err != nil {
		return 0, err
	}
	return n, nil
}

// Update persists every field of m, which must carry its primary key.
func (s *PromoCodeStore) Update(ctx context.Context, m *PromoCode) error {
	return s.DB.WithContext(ctx).Save(m).Error
}

// GetByID fetches the PromoCode with the given primary key.
func (s *PromoCodeStore) GetByID(ctx context.Context, id string) (*PromoCode, error) {
	var m PromoCode
	if err := s.DB.WithContext(ctx).First(&m, "id = ?", id).Error; err != nil {
		return nil, err
	}
	return &m, nil
}

// DeleteByID removes the PromoCode with the given primary key.
func (s *PromoCodeStore) DeleteByID(ctx context.Context, id string) error {
	return s.DB.WithContext(ctx).Delete(&PromoCode{}, "id = ?", id).Error
}

// GetByName fetches the PromoCode with the given name (a unique column).
func (s *PromoCodeStore) GetByName(ctx context.Context, v string) (*PromoCode, error) {
	var m PromoCode
	if err := s.DB.WithContext(ctx).First(&m, "name = ?", v).Error; err != nil {
		return nil, err
	}
	return &m, nil
}

// GetByCode fetches the PromoCode with the given code (a unique column).
func (s *PromoCodeStore) GetByCode(ctx context.Context, v string) (*PromoCode, error) {
	var m PromoCode
	if err := s.DB.WithContext(ctx).First(&m, "code = ?", v).Error; err != nil {
		return nil, err
	}
	return &m, nil
}
