// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm (unknown)
// 	protoc (unknown)
// source: cart.proto
//
// database: commerce
// schema:   shop_cart_v1
//
// orm — https://github.com/the-protobuf-project/orm

package shopcartv1

// Status enumerates cart payment states.
type Status string

// Status values as stored in the database.
const (
	StatusPending Status = "PENDING"
	StatusPaid    Status = "PAID"
)

// Money is a cart-side resource. Its simple name "Money" collides with the order-side Money once both packages merge into the "commerce" database (see orm.yaml). Prisma qualifies the colliding model names (its models share one global namespace), while the schema-namespaced targets — GORM (one package per schema), SQL, and CSV — keep the bare "Money", since the schema already disambiguates them.
type Money struct {
	// Unique identifier for the record.
	ID string `gorm:"column:id;type:char(26);primaryKey;not null" json:"id"`
	// Resource name; the AIP identifier.
	Name string `gorm:"column:name;type:varchar(255);not null;uniqueIndex" json:"name" validate:"required"`
	// Amount in minor units.
	Amount int64 `gorm:"column:amount;not null" json:"amount" validate:"required"`
	// Status is a cart-side enum whose simple name collides with order.Status.
	Status Status `gorm:"column:status;not null;default:'PENDING';check:chk_moneys_status,status IN ('PENDING','PAID')" json:"status" validate:"required"`
}

func (*Money) TableName() string { return "shop_cart_v1.moneys" }
