// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm (unknown)
// 	protoc (unknown)
// source: reserved_words.proto
//
// database: reserved_db
// schema:   public
//
// orm — https://github.com/the-protobuf-project/orm

package public

// State is the account lifecycle state.
type State string

// State values as stored in the database.
const (
	// STATE_ACTIVE marks an open, usable account.
	StateActive State = "ACTIVE"
	// STATE_CLOSED marks a deactivated account.
	StateClosed State = "CLOSED"
)

// Account is forced onto the reserved table name "user" via a table override, with reserved-word columns and a composite UNIQUE index over them.
type Account struct {
	// Unique identifier for the record.
	ID string `gorm:"column:id;type:char(26);primaryKey;not null" json:"id"`
	// name: IDENTIFIER → PRIMARY KEY.
	Name string `gorm:"column:name;type:varchar(255);not null;uniqueIndex" json:"name" validate:"required"`
	// order is a reserved word; also carries a single-column index.
	Order *string `gorm:"column:order;type:varchar(255);index;uniqueIndex:idx_user_order_select,priority:1" json:"order,omitempty"`
	// select is a reserved word.
	Select *string `gorm:"column:select;type:varchar(255);uniqueIndex:idx_user_order_select,priority:2" json:"select,omitempty"`
	// state exercises a quoted, schema-qualified enum type reference.
	State *State `gorm:"column:state;check:chk_user_state,state IN ('ACTIVE','CLOSED')" json:"state,omitempty"`
}

func (*Account) TableName() string { return "public.user" }
