// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: orm/v1/annotations.proto

package ormpbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_orm_v1_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*DatasourceOptions)(nil),
		Field:         50000,
		Name:          "orm.v1.datasource",
		Tag:           "bytes,50000,opt,name=datasource",
		Filename:      "orm/v1/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*TableOptions)(nil),
		Field:         50001,
		Name:          "orm.v1.table",
		Tag:           "bytes,50001,opt,name=table",
		Filename:      "orm/v1/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*ColumnOptions)(nil),
		Field:         50002,
		Name:          "orm.v1.column",
		Tag:           "bytes,50002,opt,name=column",
		Filename:      "orm/v1/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*QueryOptions)(nil),
		Field:         50003,
		Name:          "orm.v1.query",
		Tag:           "bytes,50003,opt,name=query",
		Filename:      "orm/v1/annotations.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// datasource groups the file's messages into a database and names its schema.
	//
	// optional orm.v1.DatasourceOptions datasource = 50000;
	E_Datasource = &file_orm_v1_annotations_proto_extTypes[0]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// table overrides table-level generation: name, id strategy, timestamps, indexes.
	//
	// optional orm.v1.TableOptions table = 50001;
	E_Table = &file_orm_v1_annotations_proto_extTypes[1]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// column overrides column-level generation: name, type, sizing, FK actions.
	//
	// optional orm.v1.ColumnOptions column = 50002;
	E_Column = &file_orm_v1_annotations_proto_extTypes[2]
	// query tunes the field's generated list-query surface: AIP-160 filter,
	// AIP-132 order_by, and free-text search.
	//
	// optional orm.v1.QueryOptions query = 50003;
	E_Query = &file_orm_v1_annotations_proto_extTypes[3]
)

var File_orm_v1_annotations_proto protoreflect.FileDescriptor

const file_orm_v1_annotations_proto_rawDesc = "" +
	"\n" +
	"\x18orm/v1/annotations.proto\x12\x06orm.v1\x1a google/protobuf/descriptor.proto\x1a\x13orm/v1/column.proto\x1a\x17orm/v1/datasource.proto\x1a\x12orm/v1/query.proto\x1a\x12orm/v1/table.proto:Y\n" +
	"\n" +
	"datasource\x12\x1c.google.protobuf.FileOptions\x18І\x03 \x01(\v2\x19.orm.v1.DatasourceOptionsR\n" +
	"datasource:M\n" +
	"\x05table\x12\x1f.google.protobuf.MessageOptions\x18ц\x03 \x01(\v2\x14.orm.v1.TableOptionsR\x05table:N\n" +
	"\x06column\x12\x1d.google.protobuf.FieldOptions\x18҆\x03 \x01(\v2\x15.orm.v1.ColumnOptionsR\x06column:K\n" +
	"\x05query\x12\x1d.google.protobuf.FieldOptions\x18ӆ\x03 \x01(\v2\x14.orm.v1.QueryOptionsR\x05queryB\x98\x01\n" +
	"\n" +
	"com.orm.v1B\x10AnnotationsProtoP\x01Z?github.com/the-protobuf-project/store/plugin/pb/ormpbv1;ormpbv1\xa2\x02\x03OXX\xaa\x02\x06Orm.V1\xca\x02\x06Orm\\V1\xe2\x02\x12Orm\\V1\\GPBMetadata\xea\x02\aOrm::V1b\x06proto3"

var file_orm_v1_annotations_proto_goTypes = []any{
	(*descriptorpb.FileOptions)(nil),    // 0: google.protobuf.FileOptions
	(*descriptorpb.MessageOptions)(nil), // 1: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 2: google.protobuf.FieldOptions
	(*DatasourceOptions)(nil),           // 3: orm.v1.DatasourceOptions
	(*TableOptions)(nil),                // 4: orm.v1.TableOptions
	(*ColumnOptions)(nil),               // 5: orm.v1.ColumnOptions
	(*QueryOptions)(nil),                // 6: orm.v1.QueryOptions
}
var file_orm_v1_annotations_proto_depIdxs = []int32{
	0, // 0: orm.v1.datasource:extendee -> google.protobuf.FileOptions
	1, // 1: orm.v1.table:extendee -> google.protobuf.MessageOptions
	2, // 2: orm.v1.column:extendee -> google.protobuf.FieldOptions
	2, // 3: orm.v1.query:extendee -> google.protobuf.FieldOptions
	3, // 4: orm.v1.datasource:type_name -> orm.v1.DatasourceOptions
	4, // 5: orm.v1.table:type_name -> orm.v1.TableOptions
	5, // 6: orm.v1.column:type_name -> orm.v1.ColumnOptions
	6, // 7: orm.v1.query:type_name -> orm.v1.QueryOptions
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	4, // [4:8] is the sub-list for extension type_name
	0, // [0:4] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_orm_v1_annotations_proto_init() }
func file_orm_v1_annotations_proto_init() {
	if File_orm_v1_annotations_proto != nil {
		return
	}
	file_orm_v1_column_proto_init()
	file_orm_v1_datasource_proto_init()
	file_orm_v1_query_proto_init()
	file_orm_v1_table_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orm_v1_annotations_proto_rawDesc), len(file_orm_v1_annotations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 4,
			NumServices:   0,
		},
		GoTypes:           file_orm_v1_annotations_proto_goTypes,
		DependencyIndexes: file_orm_v1_annotations_proto_depIdxs,
		ExtensionInfos:    file_orm_v1_annotations_proto_extTypes,
	}.Build()
	File_orm_v1_annotations_proto = out.File
	file_orm_v1_annotations_proto_goTypes = nil
	file_orm_v1_annotations_proto_depIdxs = nil
}
