// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: orm/v1/cache.proto

package ormpbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CacheStore is where cached entries live.
type CacheStore int32

const (
	// Process-local memory: no infrastructure, no sharing between replicas.
	CacheStore_CACHE_STORE_UNSPECIFIED CacheStore = 0
	// Redis.
	CacheStore_CACHE_STORE_REDIS CacheStore = 1
	// Valkey, the Redis fork; wire-compatible for these purposes.
	CacheStore_CACHE_STORE_VALKEY CacheStore = 2
	// Explicitly process-local memory, stated rather than defaulted.
	CacheStore_CACHE_STORE_MEMORY CacheStore = 3
)

// Enum value maps for CacheStore.
var (
	CacheStore_name = map[int32]string{
		0: "CACHE_STORE_UNSPECIFIED",
		1: "CACHE_STORE_REDIS",
		2: "CACHE_STORE_VALKEY",
		3: "CACHE_STORE_MEMORY",
	}
	CacheStore_value = map[string]int32{
		"CACHE_STORE_UNSPECIFIED": 0,
		"CACHE_STORE_REDIS":       1,
		"CACHE_STORE_VALKEY":      2,
		"CACHE_STORE_MEMORY":      3,
	}
)

func (x CacheStore) Enum() *CacheStore {
	p := new(CacheStore)
	*p = x
	return p
}

func (x CacheStore) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CacheStore) Descriptor() protoreflect.EnumDescriptor {
	return file_orm_v1_cache_proto_enumTypes[0].Descriptor()
}

func (CacheStore) Type() protoreflect.EnumType {
	return &file_orm_v1_cache_proto_enumTypes[0]
}

func (x CacheStore) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CacheStore.Descriptor instead.
func (CacheStore) EnumDescriptor() ([]byte, []int) {
	return file_orm_v1_cache_proto_rawDescGZIP(), []int{0}
}

// CacheStrategy is how reads and writes move through the cache.
type CacheStrategy int32

const (
	// Read-through: a miss reads the database and fills the cache.
	CacheStrategy_CACHE_STRATEGY_UNSPECIFIED CacheStrategy = 0
	// Read-through, stated rather than defaulted.
	CacheStrategy_CACHE_STRATEGY_READ_THROUGH CacheStrategy = 1
	// Write-through: a write updates the database and the cache together, so a
	// subsequent read never misses on freshly-written data.
	CacheStrategy_CACHE_STRATEGY_WRITE_THROUGH CacheStrategy = 2
	// Write-behind: a write updates the cache and the database asynchronously.
	// Fastest, and the only strategy where a crash can lose an acknowledged write.
	CacheStrategy_CACHE_STRATEGY_WRITE_BEHIND CacheStrategy = 3
	// Refresh-ahead: an entry nearing its TTL is refreshed before it expires, so
	// a hot key never pays the miss.
	CacheStrategy_CACHE_STRATEGY_REFRESH_AHEAD CacheStrategy = 4
)

// Enum value maps for CacheStrategy.
var (
	CacheStrategy_name = map[int32]string{
		0: "CACHE_STRATEGY_UNSPECIFIED",
		1: "CACHE_STRATEGY_READ_THROUGH",
		2: "CACHE_STRATEGY_WRITE_THROUGH",
		3: "CACHE_STRATEGY_WRITE_BEHIND",
		4: "CACHE_STRATEGY_REFRESH_AHEAD",
	}
	CacheStrategy_value = map[string]int32{
		"CACHE_STRATEGY_UNSPECIFIED":   0,
		"CACHE_STRATEGY_READ_THROUGH":  1,
		"CACHE_STRATEGY_WRITE_THROUGH": 2,
		"CACHE_STRATEGY_WRITE_BEHIND":  3,
		"CACHE_STRATEGY_REFRESH_AHEAD": 4,
	}
)

func (x CacheStrategy) Enum() *CacheStrategy {
	p := new(CacheStrategy)
	*p = x
	return p
}

func (x CacheStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CacheStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_orm_v1_cache_proto_enumTypes[1].Descriptor()
}

func (CacheStrategy) Type() protoreflect.EnumType {
	return &file_orm_v1_cache_proto_enumTypes[1]
}

func (x CacheStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CacheStrategy.Descriptor instead.
func (CacheStrategy) EnumDescriptor() ([]byte, []int) {
	return file_orm_v1_cache_proto_rawDescGZIP(), []int{1}
}

// Invalidation is what makes a cached entry stale.
type Invalidation int32

const (
	// On write through a generated store, which is the default and is only
	// complete if every writer goes through one.
	Invalidation_INVALIDATION_UNSPECIFIED Invalidation = 0
	// On write, stated rather than defaulted.
	Invalidation_INVALIDATION_ON_WRITE Invalidation = 1
	// TTL expiry alone: entries are never evicted early, so readers tolerate
	// staleness up to the TTL. Requires ttl.
	Invalidation_INVALIDATION_TTL_ONLY Invalidation = 2
	// Broker events: a change stream evicts (or refills) entries, which is what
	// keeps a cache correct when writers bypass the generated stores. Requires
	// stream.
	Invalidation_INVALIDATION_STREAM Invalidation = 3
)

// Enum value maps for Invalidation.
var (
	Invalidation_name = map[int32]string{
		0: "INVALIDATION_UNSPECIFIED",
		1: "INVALIDATION_ON_WRITE",
		2: "INVALIDATION_TTL_ONLY",
		3: "INVALIDATION_STREAM",
	}
	Invalidation_value = map[string]int32{
		"INVALIDATION_UNSPECIFIED": 0,
		"INVALIDATION_ON_WRITE":    1,
		"INVALIDATION_TTL_ONLY":    2,
		"INVALIDATION_STREAM":      3,
	}
)

func (x Invalidation) Enum() *Invalidation {
	p := new(Invalidation)
	*p = x
	return p
}

func (x Invalidation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Invalidation) Descriptor() protoreflect.EnumDescriptor {
	return file_orm_v1_cache_proto_enumTypes[2].Descriptor()
}

func (Invalidation) Type() protoreflect.EnumType {
	return &file_orm_v1_cache_proto_enumTypes[2]
}

func (x Invalidation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Invalidation.Descriptor instead.
func (Invalidation) EnumDescriptor() ([]byte, []int) {
	return file_orm_v1_cache_proto_rawDescGZIP(), []int{2}
}

// CacheOptions declares a table's caching policy — which lookups are cached, for
// how long, where, and what makes an entry stale. It is declarative in the same
// way IndexDef is: the schema states which key sets matter, and a consumer
// decides how to serve them.
//
// Applied via:
//
//	option (orm.v1.cache) = {
//	  enabled: true
//	  ttl: {seconds: 300}
//	  store: CACHE_STORE_REDIS
//	  keys: [{columns: ["id"]}, {columns: ["tenant_id", "slug"]}]
//	  strategy: CACHE_STRATEGY_READ_THROUGH
//	  invalidation: INVALIDATION_STREAM
//	  stream: {subject: "profile.accounts.>", durable: "accounts-cache"}
//	};
//
// This is policy metadata: the generator reads it, checks it against the table,
// and surfaces it in the generated documentation. No cache client, key builder,
// or stream consumer is emitted from it yet — the annotation exists so the
// contract is pinned in the schema, where it belongs, before any runtime
// depends on it.
type CacheOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// enabled turns caching on for this table. The rest of the policy is inert
	// without it, so a table can carry a fully-specified policy that is switched
	// off in one place.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// ttl is how long an entry stays fresh. Unset means entries live until
	// something invalidates them, which is only safe with a non-TTL invalidation.
	Ttl *durationpb.Duration `protobuf:"bytes,2,opt,name=ttl,proto3" json:"ttl,omitempty"`
	// store selects where entries live. Defaults to CACHE_STORE_MEMORY, the only
	// one that needs no infrastructure.
	Store CacheStore `protobuf:"varint,3,opt,name=store,proto3,enum=orm.v1.CacheStore" json:"store,omitempty"`
	// keys are the lookups worth caching, each a column set — the primary key, a
	// unique constraint, a common composite filter. Declared the way indexes are,
	// because the question is the same one: which access patterns matter enough to
	// pay for. Empty means the primary key alone.
	Keys []*CacheKey `protobuf:"bytes,4,rep,name=keys,proto3" json:"keys,omitempty"`
	// strategy is how reads and writes move through the cache.
	Strategy CacheStrategy `protobuf:"varint,5,opt,name=strategy,proto3,enum=orm.v1.CacheStrategy" json:"strategy,omitempty"`
	// invalidation is what makes an entry stale.
	Invalidation Invalidation `protobuf:"varint,6,opt,name=invalidation,proto3,enum=orm.v1.Invalidation" json:"invalidation,omitempty"`
	// stream describes the broker subject carrying change events, required when
	// invalidation is INVALIDATION_STREAM. It is what lets a cache be filled and
	// evicted by something other than the writer — a change stream, a projection,
	// another service.
	Stream        *StreamSource `protobuf:"bytes,7,opt,name=stream,proto3" json:"stream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheOptions) Reset() {
	*x = CacheOptions{}
	mi := &file_orm_v1_cache_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheOptions) ProtoMessage() {}

func (x *CacheOptions) ProtoReflect() protoreflect.Message {
	mi := &file_orm_v1_cache_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheOptions.ProtoReflect.Descriptor instead.
func (*CacheOptions) Descriptor() ([]byte, []int) {
	return file_orm_v1_cache_proto_rawDescGZIP(), []int{0}
}

func (x *CacheOptions) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *CacheOptions) GetTtl() *durationpb.Duration {
	if x != nil {
		return x.Ttl
	}
	return nil
}

func (x *CacheOptions) GetStore() CacheStore {
	if x != nil {
		return x.Store
	}
	return CacheStore_CACHE_STORE_UNSPECIFIED
}

func (x *CacheOptions) GetKeys() []*CacheKey {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *CacheOptions) GetStrategy() CacheStrategy {
	if x != nil {
		return x.Strategy
	}
	return CacheStrategy_CACHE_STRATEGY_UNSPECIFIED
}

func (x *CacheOptions) GetInvalidation() Invalidation {
	if x != nil {
		return x.Invalidation
	}
	return Invalidation_INVALIDATION_UNSPECIFIED
}

func (x *CacheOptions) GetStream() *StreamSource {
	if x != nil {
		return x.Stream
	}
	return nil
}

// CacheKey is one cached lookup: the column set it is keyed by.
type CacheKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// columns lists field names (proto snake_case) forming the key, in order.
	Columns []string `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
	// key is an optional explicit name for the key set, used as the cache key
	// prefix. Auto-generated as cache_<table>_<cols> when empty.
	Key           string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheKey) Reset() {
	*x = CacheKey{}
	mi := &file_orm_v1_cache_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheKey) ProtoMessage() {}

func (x *CacheKey) ProtoReflect() protoreflect.Message {
	mi := &file_orm_v1_cache_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheKey.ProtoReflect.Descriptor instead.
func (*CacheKey) Descriptor() ([]byte, []int) {
	return file_orm_v1_cache_proto_rawDescGZIP(), []int{1}
}

func (x *CacheKey) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *CacheKey) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// StreamSource identifies the broker subject carrying this table's change
// events. Modeled on NATS JetStream's vocabulary; a consumer for another broker
// maps subject onto its own topic naming.
type StreamSource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// subject is the NATS subject (or topic) change events are published on.
	Subject string `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	// durable is the durable consumer name, so a restart resumes rather than
	// replaying from the beginning.
	Durable string `protobuf:"bytes,2,opt,name=durable,proto3" json:"durable,omitempty"`
	// queue_group is the queue group replicas join, so one delivery is handled
	// once across the group rather than once per replica.
	QueueGroup    string `protobuf:"bytes,3,opt,name=queue_group,json=queueGroup,proto3" json:"queue_group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamSource) Reset() {
	*x = StreamSource{}
	mi := &file_orm_v1_cache_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamSource) ProtoMessage() {}

func (x *StreamSource) ProtoReflect() protoreflect.Message {
	mi := &file_orm_v1_cache_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamSource.ProtoReflect.Descriptor instead.
func (*StreamSource) Descriptor() ([]byte, []int) {
	return file_orm_v1_cache_proto_rawDescGZIP(), []int{2}
}

func (x *StreamSource) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *StreamSource) GetDurable() string {
	if x != nil {
		return x.Durable
	}
	return ""
}

func (x *StreamSource) GetQueueGroup() string {
	if x != nil {
		return x.QueueGroup
	}
	return ""
}

var File_orm_v1_cache_proto protoreflect.FileDescriptor

const file_orm_v1_cache_proto_rawDesc = "" +
	"\n" +
	"\x12orm/v1/cache.proto\x12\x06orm.v1\x1a\x1egoogle/protobuf/duration.proto\"\xc0\x02\n" +
	"\fCacheOptions\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12+\n" +
	"\x03ttl\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x03ttl\x12(\n" +
	"\x05store\x18\x03 \x01(\x0e2\x12.orm.v1.CacheStoreR\x05store\x12$\n" +
	"\x04keys\x18\x04 \x03(\v2\x10.orm.v1.CacheKeyR\x04keys\x121\n" +
	"\bstrategy\x18\x05 \x01(\x0e2\x15.orm.v1.CacheStrategyR\bstrategy\x128\n" +
	"\finvalidation\x18\x06 \x01(\x0e2\x14.orm.v1.InvalidationR\finvalidation\x12,\n" +
	"\x06stream\x18\a \x01(\v2\x14.orm.v1.StreamSourceR\x06stream\"6\n" +
	"\bCacheKey\x12\x18\n" +
	"\acolumns\x18\x01 \x03(\tR\acolumns\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"c\n" +
	"\fStreamSource\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x18\n" +
	"\adurable\x18\x02 \x01(\tR\adurable\x12\x1f\n" +
	"\vqueue_group\x18\x03 \x01(\tR\n" +
	"queueGroup*p\n" +
	"\n" +
	"CacheStore\x12\x1b\n" +
	"\x17CACHE_STORE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11CACHE_STORE_REDIS\x10\x01\x12\x16\n" +
	"\x12CACHE_STORE_VALKEY\x10\x02\x12\x16\n" +
	"\x12CACHE_STORE_MEMORY\x10\x03*\xb5\x01\n" +
	"\rCacheStrategy\x12\x1e\n" +
	"\x1aCACHE_STRATEGY_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bCACHE_STRATEGY_READ_THROUGH\x10\x01\x12 \n" +
	"\x1cCACHE_STRATEGY_WRITE_THROUGH\x10\x02\x12\x1f\n" +
	"\x1bCACHE_STRATEGY_WRITE_BEHIND\x10\x03\x12 \n" +
	"\x1cCACHE_STRATEGY_REFRESH_AHEAD\x10\x04*{\n" +
	"\fInvalidation\x12\x1c\n" +
	"\x18INVALIDATION_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15INVALIDATION_ON_WRITE\x10\x01\x12\x19\n" +
	"\x15INVALIDATION_TTL_ONLY\x10\x02\x12\x17\n" +
	"\x13INVALIDATION_STREAM\x10\x03B\x90\x01\n" +
	"\n" +
	"com.orm.v1B\n" +
	"CacheProtoP\x01Z=github.com/the-protobuf-project/orm/plugin/pb/ormpbv1;ormpbv1\xa2\x02\x03OXX\xaa\x02\x06Orm.V1\xca\x02\x06Orm\\V1\xe2\x02\x12Orm\\V1\\GPBMetadata\xea\x02\aOrm::V1b\x06proto3"

var (
	file_orm_v1_cache_proto_rawDescOnce sync.Once
	file_orm_v1_cache_proto_rawDescData []byte
)

func file_orm_v1_cache_proto_rawDescGZIP() []byte {
	file_orm_v1_cache_proto_rawDescOnce.Do(func() {
		file_orm_v1_cache_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orm_v1_cache_proto_rawDesc), len(file_orm_v1_cache_proto_rawDesc)))
	})
	return file_orm_v1_cache_proto_rawDescData
}

var file_orm_v1_cache_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_orm_v1_cache_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_orm_v1_cache_proto_goTypes = []any{
	(CacheStore)(0),             // 0: orm.v1.CacheStore
	(CacheStrategy)(0),          // 1: orm.v1.CacheStrategy
	(Invalidation)(0),           // 2: orm.v1.Invalidation
	(*CacheOptions)(nil),        // 3: orm.v1.CacheOptions
	(*CacheKey)(nil),            // 4: orm.v1.CacheKey
	(*StreamSource)(nil),        // 5: orm.v1.StreamSource
	(*durationpb.Duration)(nil), // 6: google.protobuf.Duration
}
var file_orm_v1_cache_proto_depIdxs = []int32{
	6, // 0: orm.v1.CacheOptions.ttl:type_name -> google.protobuf.Duration
	0, // 1: orm.v1.CacheOptions.store:type_name -> orm.v1.CacheStore
	4, // 2: orm.v1.CacheOptions.keys:type_name -> orm.v1.CacheKey
	1, // 3: orm.v1.CacheOptions.strategy:type_name -> orm.v1.CacheStrategy
	2, // 4: orm.v1.CacheOptions.invalidation:type_name -> orm.v1.Invalidation
	5, // 5: orm.v1.CacheOptions.stream:type_name -> orm.v1.StreamSource
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_orm_v1_cache_proto_init() }
func file_orm_v1_cache_proto_init() {
	if File_orm_v1_cache_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orm_v1_cache_proto_rawDesc), len(file_orm_v1_cache_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_orm_v1_cache_proto_goTypes,
		DependencyIndexes: file_orm_v1_cache_proto_depIdxs,
		EnumInfos:         file_orm_v1_cache_proto_enumTypes,
		MessageInfos:      file_orm_v1_cache_proto_msgTypes,
	}.Build()
	File_orm_v1_cache_proto = out.File
	file_orm_v1_cache_proto_goTypes = nil
	file_orm_v1_cache_proto_depIdxs = nil
}
