// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: orm/v1/column.proto

package ormpbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ColumnOptions overrides column-level generation for a single field.
//
// Applied via:
//
//	string title = 2 [(orm.v1.column) = { max_length: 500 }];
type ColumnOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// column is an explicit column name.
	// Defaults to the proto field name, which is already snake_case.
	Column string `protobuf:"bytes,1,opt,name=column,proto3" json:"column,omitempty"`
	// type is an explicit database type, e.g. "VARCHAR(255)", "JSONB", "TIMESTAMPTZ".
	// Provider-specific escape hatch; prefer max_length / precision for
	// provider-neutral sizing. Overrides all inference.
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// default_value is a SQL default expression, e.g. "NOW()", "'active'", "0".
	// Written verbatim into the DEFAULT clause.
	DefaultValue string `protobuf:"bytes,3,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	// unique adds a UNIQUE constraint to this column.
	Unique bool `protobuf:"varint,4,opt,name=unique,proto3" json:"unique,omitempty"`
	// index adds a single-column index on this column.
	// Use TableOptions.indexes for composite indexes.
	Index bool `protobuf:"varint,5,opt,name=index,proto3" json:"index,omitempty"`
	// skip excludes this field from all output — no column is generated.
	Skip bool `protobuf:"varint,6,opt,name=skip,proto3" json:"skip,omitempty"`
	// max_length caps a string field: VARCHAR(max_length) instead of the
	// VARCHAR(255) default. Provider-neutral (Mongo ignores it).
	MaxLength int32 `protobuf:"varint,7,opt,name=max_length,json=maxLength,proto3" json:"max_length,omitempty"`
	// precision sizes the integral digit count of a numeric field:
	// NUMERIC(precision, scale). Applies to double/float fields.
	Precision int32 `protobuf:"varint,8,opt,name=precision,proto3" json:"precision,omitempty"`
	// scale sizes the fractional digit count of a numeric field.
	// Defaults to 0 when only precision is set.
	Scale int32 `protobuf:"varint,9,opt,name=scale,proto3" json:"scale,omitempty"`
	// on_delete sets the FK ON DELETE referential action for a field carrying
	// google.api.resource_reference. Ignored on non-reference fields.
	OnDelete ReferentialAction `protobuf:"varint,10,opt,name=on_delete,json=onDelete,proto3,enum=orm.v1.ReferentialAction" json:"on_delete,omitempty"`
	// on_update sets the FK ON UPDATE referential action for a field carrying
	// google.api.resource_reference. Ignored on non-reference fields.
	OnUpdate      ReferentialAction `protobuf:"varint,11,opt,name=on_update,json=onUpdate,proto3,enum=orm.v1.ReferentialAction" json:"on_update,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColumnOptions) Reset() {
	*x = ColumnOptions{}
	mi := &file_orm_v1_column_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColumnOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnOptions) ProtoMessage() {}

func (x *ColumnOptions) ProtoReflect() protoreflect.Message {
	mi := &file_orm_v1_column_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnOptions.ProtoReflect.Descriptor instead.
func (*ColumnOptions) Descriptor() ([]byte, []int) {
	return file_orm_v1_column_proto_rawDescGZIP(), []int{0}
}

func (x *ColumnOptions) GetColumn() string {
	if x != nil {
		return x.Column
	}
	return ""
}

func (x *ColumnOptions) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ColumnOptions) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

func (x *ColumnOptions) GetUnique() bool {
	if x != nil {
		return x.Unique
	}
	return false
}

func (x *ColumnOptions) GetIndex() bool {
	if x != nil {
		return x.Index
	}
	return false
}

func (x *ColumnOptions) GetSkip() bool {
	if x != nil {
		return x.Skip
	}
	return false
}

func (x *ColumnOptions) GetMaxLength() int32 {
	if x != nil {
		return x.MaxLength
	}
	return 0
}

func (x *ColumnOptions) GetPrecision() int32 {
	if x != nil {
		return x.Precision
	}
	return 0
}

func (x *ColumnOptions) GetScale() int32 {
	if x != nil {
		return x.Scale
	}
	return 0
}

func (x *ColumnOptions) GetOnDelete() ReferentialAction {
	if x != nil {
		return x.OnDelete
	}
	return ReferentialAction_REFERENTIAL_ACTION_UNSPECIFIED
}

func (x *ColumnOptions) GetOnUpdate() ReferentialAction {
	if x != nil {
		return x.OnUpdate
	}
	return ReferentialAction_REFERENTIAL_ACTION_UNSPECIFIED
}

var File_orm_v1_column_proto protoreflect.FileDescriptor

const file_orm_v1_column_proto_rawDesc = "" +
	"\n" +
	"\x13orm/v1/column.proto\x12\x06orm.v1\x1a\x16orm/v1/reference.proto\"\xe5\x02\n" +
	"\rColumnOptions\x12\x16\n" +
	"\x06column\x18\x01 \x01(\tR\x06column\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12#\n" +
	"\rdefault_value\x18\x03 \x01(\tR\fdefaultValue\x12\x16\n" +
	"\x06unique\x18\x04 \x01(\bR\x06unique\x12\x14\n" +
	"\x05index\x18\x05 \x01(\bR\x05index\x12\x12\n" +
	"\x04skip\x18\x06 \x01(\bR\x04skip\x12\x1d\n" +
	"\n" +
	"max_length\x18\a \x01(\x05R\tmaxLength\x12\x1c\n" +
	"\tprecision\x18\b \x01(\x05R\tprecision\x12\x14\n" +
	"\x05scale\x18\t \x01(\x05R\x05scale\x126\n" +
	"\ton_delete\x18\n" +
	" \x01(\x0e2\x19.orm.v1.ReferentialActionR\bonDelete\x126\n" +
	"\ton_update\x18\v \x01(\x0e2\x19.orm.v1.ReferentialActionR\bonUpdateB\x91\x01\n" +
	"\n" +
	"com.orm.v1B\vColumnProtoP\x01Z=github.com/the-protobuf-project/orm/plugin/pb/ormpbv1;ormpbv1\xa2\x02\x03OXX\xaa\x02\x06Orm.V1\xca\x02\x06Orm\\V1\xe2\x02\x12Orm\\V1\\GPBMetadata\xea\x02\aOrm::V1b\x06proto3"

var (
	file_orm_v1_column_proto_rawDescOnce sync.Once
	file_orm_v1_column_proto_rawDescData []byte
)

func file_orm_v1_column_proto_rawDescGZIP() []byte {
	file_orm_v1_column_proto_rawDescOnce.Do(func() {
		file_orm_v1_column_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orm_v1_column_proto_rawDesc), len(file_orm_v1_column_proto_rawDesc)))
	})
	return file_orm_v1_column_proto_rawDescData
}

var file_orm_v1_column_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_orm_v1_column_proto_goTypes = []any{
	(*ColumnOptions)(nil),  // 0: orm.v1.ColumnOptions
	(ReferentialAction)(0), // 1: orm.v1.ReferentialAction
}
var file_orm_v1_column_proto_depIdxs = []int32{
	1, // 0: orm.v1.ColumnOptions.on_delete:type_name -> orm.v1.ReferentialAction
	1, // 1: orm.v1.ColumnOptions.on_update:type_name -> orm.v1.ReferentialAction
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_orm_v1_column_proto_init() }
func file_orm_v1_column_proto_init() {
	if File_orm_v1_column_proto != nil {
		return
	}
	file_orm_v1_reference_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orm_v1_column_proto_rawDesc), len(file_orm_v1_column_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_orm_v1_column_proto_goTypes,
		DependencyIndexes: file_orm_v1_column_proto_depIdxs,
		MessageInfos:      file_orm_v1_column_proto_msgTypes,
	}.Build()
	File_orm_v1_column_proto = out.File
	file_orm_v1_column_proto_goTypes = nil
	file_orm_v1_column_proto_depIdxs = nil
}
