// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: orm/v1/constraint.proto

package ormpbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ConstraintOptions carries the validation rules that take an argument, and is
// the companion to the parameterless (orm.v1.validate) presets. The two are
// deliberately separate surfaces rather than one: a preset is stackable and
// reads as a word at the call site, which only works because it has nothing to
// configure. The moment a rule needs a bound, a pattern, or a value set, it
// needs a message.
//
// Applied via:
//
//	int32 pages = 4 [(orm.v1.constraint) = {min: 1, max: 10000}];
//	string sku = 5 [(orm.v1.constraint) = {pattern: "^[A-Z]{3}-[0-9]{4}$"}];
//	string tier = 6 [(orm.v1.constraint) = {in: ["free", "pro", "enterprise"]}];
//
// Both surfaces project the same three ways — an application check, a DDL CHECK
// constraint, and a go-playground tag — and a field may carry both:
//
//	string handle = 7 [
//	  (orm.v1.validate) = VALIDATE_SLUG,
//	  (orm.v1.constraint) = {min: 3, max: 40}
//	];
//
// Bounds are inclusive, and are optional fields so that an unset bound is
// distinguishable from a zero one — `min: 0` is a real constraint on a signed
// column. An exclusive lower bound of zero is what VALIDATE_POSITIVE is for.
type ConstraintOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// min is the inclusive lower bound, read according to the column's type:
	// the value itself for a numeric column, the character count for a string,
	// the element count for a repeated column. One pair of fields rather than
	// separate value and length bounds, because a column is only ever one of
	// those things and the author already knows which.
	Min *float64 `protobuf:"fixed64,1,opt,name=min,proto3,oneof" json:"min,omitempty"`
	// max is the inclusive upper bound, read the same way as min.
	//
	// For a string this is distinct from ColumnOptions.max_length, which sizes the
	// column type (VARCHAR(n)) and therefore already bounds it in the database.
	// Use this when the column is unsized (TEXT) or when the application should
	// reject an overlong value with a field-shaped error rather than a driver
	// error. The two must not contradict each other: a max wider than the column's
	// max_length fails generation.
	Max *float64 `protobuf:"fixed64,2,opt,name=max,proto3,oneof" json:"max,omitempty"`
	// pattern is an RE2 regular expression the value must match. It is compiled at
	// generation time, so an invalid pattern fails the build rather than every
	// write. Written in the POSIX subset both RE2 and Postgres accept, since the
	// same pattern becomes a CHECK constraint.
	Pattern string `protobuf:"bytes,3,opt,name=pattern,proto3" json:"pattern,omitempty"`
	// in is the closed set of accepted values. An enum column expresses this with
	// its own type instead; this is for a string column whose accepted values are
	// not worth an enum.
	In []string `protobuf:"bytes,4,rep,name=in,proto3" json:"in,omitempty"`
	// not_in is the set of rejected values, applied after every other rule.
	NotIn         []string `protobuf:"bytes,5,rep,name=not_in,json=notIn,proto3" json:"not_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConstraintOptions) Reset() {
	*x = ConstraintOptions{}
	mi := &file_orm_v1_constraint_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConstraintOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConstraintOptions) ProtoMessage() {}

func (x *ConstraintOptions) ProtoReflect() protoreflect.Message {
	mi := &file_orm_v1_constraint_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConstraintOptions.ProtoReflect.Descriptor instead.
func (*ConstraintOptions) Descriptor() ([]byte, []int) {
	return file_orm_v1_constraint_proto_rawDescGZIP(), []int{0}
}

func (x *ConstraintOptions) GetMin() float64 {
	if x != nil && x.Min != nil {
		return *x.Min
	}
	return 0
}

func (x *ConstraintOptions) GetMax() float64 {
	if x != nil && x.Max != nil {
		return *x.Max
	}
	return 0
}

func (x *ConstraintOptions) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *ConstraintOptions) GetIn() []string {
	if x != nil {
		return x.In
	}
	return nil
}

func (x *ConstraintOptions) GetNotIn() []string {
	if x != nil {
		return x.NotIn
	}
	return nil
}

// TableConstraint is a CHECK spanning several columns, which the field-level
// ConstraintOptions cannot express: "end_time > start_time" is a statement about
// a row, not about a column.
//
// Applied via (repeated, so a table may declare several):
//
//	option (orm.v1.table_constraint) = {
//	  name: "ends_after_start"
//	  sql:  "end_time > start_time"
//	  cel:  "this.end_time > this.start_time"
//	  message: "end_time must be after start_time"
//	};
//
// It takes an expression rather than a structured comparison because arbitrary
// cross-field logic has no portable shorthand — the same reason `indexes` takes
// column names and a DDL fragment rather than a query DSL.
type TableConstraint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name identifies the constraint. It becomes the DDL constraint name, prefixed
	// with the table (chk_<table>_<name>), so a violation names something a reader
	// can find in the schema. Required.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// sql is the CHECK body, referring to columns by their database names. It is
	// written verbatim into the constraint, so it must be valid for the target
	// database and must be immutable — a CHECK referencing now() is not, and would
	// validate differently after a table rewrite.
	Sql string `protobuf:"bytes,2,opt,name=sql,proto3" json:"sql,omitempty"`
	// cel is the optional application-side twin of sql, a CEL expression over the
	// row bound as `this`. It exists because SQL and CEL are not
	// inter-translatable in general: rather than guess, the author states both, and
	// the generator uses each where it belongs.
	//
	// Leaving it empty is a legitimate choice — the constraint is then enforced by
	// the database alone, and the application learns of a violation from the write
	// failing.
	Cel string `protobuf:"bytes,3,opt,name=cel,proto3" json:"cel,omitempty"`
	// message is the failure text the application-side check reports, phrased to
	// stand alone ("end_time must be after start_time") since it describes a row
	// rather than a single field. Defaults to the constraint name when empty.
	Message       string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableConstraint) Reset() {
	*x = TableConstraint{}
	mi := &file_orm_v1_constraint_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableConstraint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableConstraint) ProtoMessage() {}

func (x *TableConstraint) ProtoReflect() protoreflect.Message {
	mi := &file_orm_v1_constraint_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableConstraint.ProtoReflect.Descriptor instead.
func (*TableConstraint) Descriptor() ([]byte, []int) {
	return file_orm_v1_constraint_proto_rawDescGZIP(), []int{1}
}

func (x *TableConstraint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TableConstraint) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *TableConstraint) GetCel() string {
	if x != nil {
		return x.Cel
	}
	return ""
}

func (x *TableConstraint) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_orm_v1_constraint_proto protoreflect.FileDescriptor

const file_orm_v1_constraint_proto_rawDesc = "" +
	"\n" +
	"\x17orm/v1/constraint.proto\x12\x06orm.v1\"\x92\x01\n" +
	"\x11ConstraintOptions\x12\x15\n" +
	"\x03min\x18\x01 \x01(\x01H\x00R\x03min\x88\x01\x01\x12\x15\n" +
	"\x03max\x18\x02 \x01(\x01H\x01R\x03max\x88\x01\x01\x12\x18\n" +
	"\apattern\x18\x03 \x01(\tR\apattern\x12\x0e\n" +
	"\x02in\x18\x04 \x03(\tR\x02in\x12\x15\n" +
	"\x06not_in\x18\x05 \x03(\tR\x05notInB\x06\n" +
	"\x04_minB\x06\n" +
	"\x04_max\"c\n" +
	"\x0fTableConstraint\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03sql\x18\x02 \x01(\tR\x03sql\x12\x10\n" +
	"\x03cel\x18\x03 \x01(\tR\x03cel\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessageB\x95\x01\n" +
	"\n" +
	"com.orm.v1B\x0fConstraintProtoP\x01Z=github.com/the-protobuf-project/orm/plugin/pb/ormpbv1;ormpbv1\xa2\x02\x03OXX\xaa\x02\x06Orm.V1\xca\x02\x06Orm\\V1\xe2\x02\x12Orm\\V1\\GPBMetadata\xea\x02\aOrm::V1b\x06proto3"

var (
	file_orm_v1_constraint_proto_rawDescOnce sync.Once
	file_orm_v1_constraint_proto_rawDescData []byte
)

func file_orm_v1_constraint_proto_rawDescGZIP() []byte {
	file_orm_v1_constraint_proto_rawDescOnce.Do(func() {
		file_orm_v1_constraint_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orm_v1_constraint_proto_rawDesc), len(file_orm_v1_constraint_proto_rawDesc)))
	})
	return file_orm_v1_constraint_proto_rawDescData
}

var file_orm_v1_constraint_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_orm_v1_constraint_proto_goTypes = []any{
	(*ConstraintOptions)(nil), // 0: orm.v1.ConstraintOptions
	(*TableConstraint)(nil),   // 1: orm.v1.TableConstraint
}
var file_orm_v1_constraint_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_orm_v1_constraint_proto_init() }
func file_orm_v1_constraint_proto_init() {
	if File_orm_v1_constraint_proto != nil {
		return
	}
	file_orm_v1_constraint_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orm_v1_constraint_proto_rawDesc), len(file_orm_v1_constraint_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_orm_v1_constraint_proto_goTypes,
		DependencyIndexes: file_orm_v1_constraint_proto_depIdxs,
		MessageInfos:      file_orm_v1_constraint_proto_msgTypes,
	}.Build()
	File_orm_v1_constraint_proto = out.File
	file_orm_v1_constraint_proto_goTypes = nil
	file_orm_v1_constraint_proto_depIdxs = nil
}
