// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: orm/v1/validate.proto

package ormpbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Validate is a parameterless validation preset applied to a single field, in
// the style of google.api.field_behavior: a repeated enum option stacked at the
// call site rather than a nested message.
//
// Applied via:
//
//	string email = 3 [
//	  (google.api.field_behavior) = REQUIRED,
//	  (orm.v1.validate) = VALIDATE_EMAIL,
//	  (orm.v1.validate) = VALIDATE_LOWERCASE
//	];
//
// Presence and mutability are NOT part of this enum — google.api.field_behavior
// already owns them and protokit already reads them (REQUIRED / IDENTIFIER →
// NOT NULL, OUTPUT_ONLY → not application-settable, IMMUTABLE → not updatable).
// Duplicating them here would give one property two sources of truth.
//
// Every preset is parameterless by construction, which is what makes stacking
// readable. Parameterized constraints (numeric ranges, explicit regexes,
// cross-field rules) do not belong here: string sizing already lives on
// ColumnOptions (max_length / precision / scale).
//
// Each preset projects two ways where the target permits it: an application
// check on the generated store's write path, and a DDL CHECK constraint so the
// database stays correct under out-of-band writes. Presets with no faithful SQL
// form (VALIDATE_PAST / VALIDATE_FUTURE, which are evaluated against wall-clock
// time) are enforced application-side only.
type Validate int32

const (
	// No preset. Never written explicitly.
	Validate_VALIDATE_UNSPECIFIED Validate = 0
	// RFC 5322 addr-spec, in the pragmatic single-@ form every validator uses.
	Validate_VALIDATE_EMAIL Validate = 1
	// Absolute URL with a scheme and host.
	Validate_VALIDATE_URL Validate = 2
	// RFC 4122 UUID in canonical 8-4-4-4-12 hyphenated form.
	Validate_VALIDATE_UUID Validate = 3
	// Crockford base32 ULID: 26 characters, excluding I, L, O and U.
	Validate_VALIDATE_ULID Validate = 4
	// RFC 1123 hostname.
	Validate_VALIDATE_HOSTNAME Validate = 5
	// IPv4 or IPv6 address.
	Validate_VALIDATE_IP Validate = 6
	// IPv4 address in dotted-quad form.
	Validate_VALIDATE_IPV4 Validate = 7
	// IPv6 address.
	Validate_VALIDATE_IPV6 Validate = 8
	// E.164 phone number: a leading + and up to 15 digits.
	Validate_VALIDATE_E164 Validate = 9
	// URL-safe slug: lowercase alphanumerics separated by single hyphens.
	Validate_VALIDATE_SLUG Validate = 10
	// Semantic version, semver.org 2.0.0.
	Validate_VALIDATE_SEMVER Validate = 11
	// CSS hex color: # followed by 3, 6, or 8 hex digits.
	Validate_VALIDATE_HEX_COLOR Validate = 12
	// Standard base64, with or without padding.
	Validate_VALIDATE_BASE64 Validate = 13
	// Parseable JSON document. Prefer a real message or a JSONB column when the
	// shape is known; this is for genuinely opaque payloads.
	Validate_VALIDATE_JSON Validate = 14
	// Non-empty after trimming surrounding whitespace. Distinct from REQUIRED:
	// field_behavior REQUIRED rejects an absent value, this rejects "" and "   ".
	Validate_VALIDATE_NON_EMPTY Validate = 20
	// No leading or trailing whitespace.
	Validate_VALIDATE_TRIMMED Validate = 21
	// Equal to its own lowercasing.
	Validate_VALIDATE_LOWERCASE Validate = 22
	// Equal to its own uppercasing.
	Validate_VALIDATE_UPPERCASE Validate = 23
	// Printable ASCII only.
	Validate_VALIDATE_ASCII Validate = 24
	// Letters and digits only, no separators.
	Validate_VALIDATE_ALPHANUMERIC Validate = 25
	// ISO 3166-1 alpha-2 country code, e.g. "IN", "DE".
	Validate_VALIDATE_COUNTRY_CODE Validate = 30
	// ISO 4217 currency code, e.g. "INR", "EUR".
	Validate_VALIDATE_CURRENCY_CODE Validate = 31
	// BCP 47 language tag, e.g. "en-GB".
	Validate_VALIDATE_LANGUAGE_TAG Validate = 32
	// IANA time zone name, e.g. "Asia/Kolkata".
	Validate_VALIDATE_TIMEZONE Validate = 33
	// Strictly greater than zero.
	Validate_VALIDATE_POSITIVE Validate = 40
	// Greater than or equal to zero.
	Validate_VALIDATE_NON_NEGATIVE Validate = 41
	// Strictly less than zero.
	Validate_VALIDATE_NEGATIVE Validate = 42
	// Neither NaN nor infinite. Float and double fields only.
	Validate_VALIDATE_FINITE Validate = 43
	// Strictly in the past at validation time. Application-side only: a DDL CHECK
	// cannot reference wall-clock time and stay immutable across rewrites.
	Validate_VALIDATE_PAST Validate = 50
	// Strictly in the future at validation time. Application-side only, for the
	// same reason as VALIDATE_PAST.
	Validate_VALIDATE_FUTURE Validate = 51
	// No duplicate elements.
	Validate_VALIDATE_UNIQUE_ITEMS Validate = 60
	// At least one element.
	Validate_VALIDATE_NON_EMPTY_LIST Validate = 61
)

// Enum value maps for Validate.
var (
	Validate_name = map[int32]string{
		0:  "VALIDATE_UNSPECIFIED",
		1:  "VALIDATE_EMAIL",
		2:  "VALIDATE_URL",
		3:  "VALIDATE_UUID",
		4:  "VALIDATE_ULID",
		5:  "VALIDATE_HOSTNAME",
		6:  "VALIDATE_IP",
		7:  "VALIDATE_IPV4",
		8:  "VALIDATE_IPV6",
		9:  "VALIDATE_E164",
		10: "VALIDATE_SLUG",
		11: "VALIDATE_SEMVER",
		12: "VALIDATE_HEX_COLOR",
		13: "VALIDATE_BASE64",
		14: "VALIDATE_JSON",
		20: "VALIDATE_NON_EMPTY",
		21: "VALIDATE_TRIMMED",
		22: "VALIDATE_LOWERCASE",
		23: "VALIDATE_UPPERCASE",
		24: "VALIDATE_ASCII",
		25: "VALIDATE_ALPHANUMERIC",
		30: "VALIDATE_COUNTRY_CODE",
		31: "VALIDATE_CURRENCY_CODE",
		32: "VALIDATE_LANGUAGE_TAG",
		33: "VALIDATE_TIMEZONE",
		40: "VALIDATE_POSITIVE",
		41: "VALIDATE_NON_NEGATIVE",
		42: "VALIDATE_NEGATIVE",
		43: "VALIDATE_FINITE",
		50: "VALIDATE_PAST",
		51: "VALIDATE_FUTURE",
		60: "VALIDATE_UNIQUE_ITEMS",
		61: "VALIDATE_NON_EMPTY_LIST",
	}
	Validate_value = map[string]int32{
		"VALIDATE_UNSPECIFIED":    0,
		"VALIDATE_EMAIL":          1,
		"VALIDATE_URL":            2,
		"VALIDATE_UUID":           3,
		"VALIDATE_ULID":           4,
		"VALIDATE_HOSTNAME":       5,
		"VALIDATE_IP":             6,
		"VALIDATE_IPV4":           7,
		"VALIDATE_IPV6":           8,
		"VALIDATE_E164":           9,
		"VALIDATE_SLUG":           10,
		"VALIDATE_SEMVER":         11,
		"VALIDATE_HEX_COLOR":      12,
		"VALIDATE_BASE64":         13,
		"VALIDATE_JSON":           14,
		"VALIDATE_NON_EMPTY":      20,
		"VALIDATE_TRIMMED":        21,
		"VALIDATE_LOWERCASE":      22,
		"VALIDATE_UPPERCASE":      23,
		"VALIDATE_ASCII":          24,
		"VALIDATE_ALPHANUMERIC":   25,
		"VALIDATE_COUNTRY_CODE":   30,
		"VALIDATE_CURRENCY_CODE":  31,
		"VALIDATE_LANGUAGE_TAG":   32,
		"VALIDATE_TIMEZONE":       33,
		"VALIDATE_POSITIVE":       40,
		"VALIDATE_NON_NEGATIVE":   41,
		"VALIDATE_NEGATIVE":       42,
		"VALIDATE_FINITE":         43,
		"VALIDATE_PAST":           50,
		"VALIDATE_FUTURE":         51,
		"VALIDATE_UNIQUE_ITEMS":   60,
		"VALIDATE_NON_EMPTY_LIST": 61,
	}
)

func (x Validate) Enum() *Validate {
	p := new(Validate)
	*p = x
	return p
}

func (x Validate) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Validate) Descriptor() protoreflect.EnumDescriptor {
	return file_orm_v1_validate_proto_enumTypes[0].Descriptor()
}

func (Validate) Type() protoreflect.EnumType {
	return &file_orm_v1_validate_proto_enumTypes[0]
}

func (x Validate) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Validate.Descriptor instead.
func (Validate) EnumDescriptor() ([]byte, []int) {
	return file_orm_v1_validate_proto_rawDescGZIP(), []int{0}
}

var File_orm_v1_validate_proto protoreflect.FileDescriptor

const file_orm_v1_validate_proto_rawDesc = "" +
	"\n" +
	"\x15orm/v1/validate.proto\x12\x06orm.v1*\xed\x05\n" +
	"\bValidate\x12\x18\n" +
	"\x14VALIDATE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eVALIDATE_EMAIL\x10\x01\x12\x10\n" +
	"\fVALIDATE_URL\x10\x02\x12\x11\n" +
	"\rVALIDATE_UUID\x10\x03\x12\x11\n" +
	"\rVALIDATE_ULID\x10\x04\x12\x15\n" +
	"\x11VALIDATE_HOSTNAME\x10\x05\x12\x0f\n" +
	"\vVALIDATE_IP\x10\x06\x12\x11\n" +
	"\rVALIDATE_IPV4\x10\a\x12\x11\n" +
	"\rVALIDATE_IPV6\x10\b\x12\x11\n" +
	"\rVALIDATE_E164\x10\t\x12\x11\n" +
	"\rVALIDATE_SLUG\x10\n" +
	"\x12\x13\n" +
	"\x0fVALIDATE_SEMVER\x10\v\x12\x16\n" +
	"\x12VALIDATE_HEX_COLOR\x10\f\x12\x13\n" +
	"\x0fVALIDATE_BASE64\x10\r\x12\x11\n" +
	"\rVALIDATE_JSON\x10\x0e\x12\x16\n" +
	"\x12VALIDATE_NON_EMPTY\x10\x14\x12\x14\n" +
	"\x10VALIDATE_TRIMMED\x10\x15\x12\x16\n" +
	"\x12VALIDATE_LOWERCASE\x10\x16\x12\x16\n" +
	"\x12VALIDATE_UPPERCASE\x10\x17\x12\x12\n" +
	"\x0eVALIDATE_ASCII\x10\x18\x12\x19\n" +
	"\x15VALIDATE_ALPHANUMERIC\x10\x19\x12\x19\n" +
	"\x15VALIDATE_COUNTRY_CODE\x10\x1e\x12\x1a\n" +
	"\x16VALIDATE_CURRENCY_CODE\x10\x1f\x12\x19\n" +
	"\x15VALIDATE_LANGUAGE_TAG\x10 \x12\x15\n" +
	"\x11VALIDATE_TIMEZONE\x10!\x12\x15\n" +
	"\x11VALIDATE_POSITIVE\x10(\x12\x19\n" +
	"\x15VALIDATE_NON_NEGATIVE\x10)\x12\x15\n" +
	"\x11VALIDATE_NEGATIVE\x10*\x12\x13\n" +
	"\x0fVALIDATE_FINITE\x10+\x12\x11\n" +
	"\rVALIDATE_PAST\x102\x12\x13\n" +
	"\x0fVALIDATE_FUTURE\x103\x12\x19\n" +
	"\x15VALIDATE_UNIQUE_ITEMS\x10<\x12\x1b\n" +
	"\x17VALIDATE_NON_EMPTY_LIST\x10=B\x93\x01\n" +
	"\n" +
	"com.orm.v1B\rValidateProtoP\x01Z=github.com/the-protobuf-project/orm/plugin/pb/ormpbv1;ormpbv1\xa2\x02\x03OXX\xaa\x02\x06Orm.V1\xca\x02\x06Orm\\V1\xe2\x02\x12Orm\\V1\\GPBMetadata\xea\x02\aOrm::V1b\x06proto3"

var (
	file_orm_v1_validate_proto_rawDescOnce sync.Once
	file_orm_v1_validate_proto_rawDescData []byte
)

func file_orm_v1_validate_proto_rawDescGZIP() []byte {
	file_orm_v1_validate_proto_rawDescOnce.Do(func() {
		file_orm_v1_validate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orm_v1_validate_proto_rawDesc), len(file_orm_v1_validate_proto_rawDesc)))
	})
	return file_orm_v1_validate_proto_rawDescData
}

var file_orm_v1_validate_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_orm_v1_validate_proto_goTypes = []any{
	(Validate)(0), // 0: orm.v1.Validate
}
var file_orm_v1_validate_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_orm_v1_validate_proto_init() }
func file_orm_v1_validate_proto_init() {
	if File_orm_v1_validate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orm_v1_validate_proto_rawDesc), len(file_orm_v1_validate_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_orm_v1_validate_proto_goTypes,
		DependencyIndexes: file_orm_v1_validate_proto_depIdxs,
		EnumInfos:         file_orm_v1_validate_proto_enumTypes,
	}.Build()
	File_orm_v1_validate_proto = out.File
	file_orm_v1_validate_proto_goTypes = nil
	file_orm_v1_validate_proto_depIdxs = nil
}
