// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm (unknown)
// 	protoc (unknown)
// source: caching.proto
//
// database: hotel_db
// schema:   hotel
//
// orm — https://github.com/the-protobuf-project/orm

package hotel

import (
	"context"

	"example.com/test/gen/gormx"
	"gorm.io/gorm"
)

// AuditStore provides typed CRUD access to Audit records.
// Audit carries no cache policy, proving a table in a cache-enabled tree gets no Cache field and no invalidation when it declares none.
type AuditStore struct {
	DB *gorm.DB
	// Telemetry observes every operation; nil is a no-op. Wire the generated
	// adapter: NewAuditStore(db).WithTelemetry(telemetry.New(o)).
	Telemetry gormx.Telemetry
}

// Compile-time proof that AuditStore satisfies the generic gormx.Store, so the
// generic engine can drive it alongside the typed finders below.
var _ gormx.Store[Audit] = (*AuditStore)(nil)

// NewAuditStore returns a AuditStore backed by db.
func NewAuditStore(db *gorm.DB) *AuditStore { return &AuditStore{DB: db} }

// WithTelemetry sets the store's Telemetry and returns the store for chaining.
func (s *AuditStore) WithTelemetry(t gormx.Telemetry) *AuditStore {
	s.Telemetry = t
	return s
}

// Create inserts m.
func (s *AuditStore) Create(ctx context.Context, m *Audit) error {
	return s.DB.WithContext(ctx).Create(m).Error
}

// List returns the Audit records matching opts.
func (s *AuditStore) List(ctx context.Context, opts gormx.ListOptions) ([]Audit, error) {
	var out []Audit
	if err := opts.Apply(s.DB.WithContext(ctx)).Find(&out).Error; err != nil {
		return nil, err
	}
	return out, nil
}

// Count returns the number of Audit records matching opts.Where
// (pagination and ordering are ignored).
func (s *AuditStore) Count(ctx context.Context, opts gormx.ListOptions) (int64, error) {
	var n int64
	db := s.DB.WithContext(ctx).Model(&Audit{})
	if opts.Where != nil {
		db = db.Where(opts.Where, opts.Args...)
	}
	if err := db.Count(&n).Error; err != nil {
		return 0, err
	}
	return n, nil
}

// Update persists every field of m, which must carry its primary key.
func (s *AuditStore) Update(ctx context.Context, m *Audit) error {
	return s.DB.WithContext(ctx).Save(m).Error
}

// GetByID fetches the Audit with the given primary key.
func (s *AuditStore) GetByID(ctx context.Context, id string) (*Audit, error) {
	var m Audit
	if err := s.DB.WithContext(ctx).First(&m, "id = ?", id).Error; err != nil {
		return nil, err
	}
	return &m, nil
}

// DeleteByID removes the Audit with the given primary key.
func (s *AuditStore) DeleteByID(ctx context.Context, id string) error {
	return s.DB.WithContext(ctx).Delete(&Audit{}, "id = ?", id).Error
}

// GetByName fetches the Audit with the given name (a unique column).
func (s *AuditStore) GetByName(ctx context.Context, v string) (*Audit, error) {
	var m Audit
	if err := s.DB.WithContext(ctx).First(&m, "name = ?", v).Error; err != nil {
		return nil, err
	}
	return &m, nil
}
