// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store (unknown)
// 	protoc (unknown)
// source: bookstore.proto
//
// database: bookstore_db
// schema:   bookstore_v1
//
// store — https://github.com/the-protobuf-project/store

package bookstorev1

import (
	"context"

	"example.com/test/gen/gormx"
	"gorm.io/gorm"
)

// AuthorStore provides typed CRUD access to Author records.
// Author is a top-level resource. Inferred table: bookstore_v1.authors. id: ID_STRATEGY_ULID synthesizes a generated `id` PK and demotes the AIP resource name to a UNIQUE lookup column; timestamps adds created_at/updated_at.
type AuthorStore struct {
	DB *gorm.DB
	// Telemetry observes every operation; nil is a no-op. Wire the generated
	// adapter: NewAuthorStore(db).WithTelemetry(telemetry.New(o)).
	Telemetry gormx.Telemetry
}

// Compile-time proof that AuthorStore satisfies the generic gormx.Store, so the
// generic engine can drive it alongside the typed finders below.
var _ gormx.Store[Author] = (*AuthorStore)(nil)

// NewAuthorStore returns a AuthorStore backed by db.
func NewAuthorStore(db *gorm.DB) *AuthorStore { return &AuthorStore{DB: db} }

// WithTelemetry sets the store's Telemetry and returns the store for chaining.
func (s *AuthorStore) WithTelemetry(t gormx.Telemetry) *AuthorStore {
	s.Telemetry = t
	return s
}

// Create inserts m.
func (s *AuthorStore) Create(ctx context.Context, m *Author) error {
	return s.DB.WithContext(ctx).Create(m).Error
}

// List returns the Author records matching opts.
func (s *AuthorStore) List(ctx context.Context, opts gormx.ListOptions) ([]Author, error) {
	var out []Author
	if err := opts.Apply(s.DB.WithContext(ctx)).Find(&out).Error; err != nil {
		return nil, err
	}
	return out, nil
}

// Count returns the number of Author records matching opts.Where
// (pagination and ordering are ignored).
func (s *AuthorStore) Count(ctx context.Context, opts gormx.ListOptions) (int64, error) {
	var n int64
	db := s.DB.WithContext(ctx).Model(&Author{})
	if opts.Where != nil {
		db = db.Where(opts.Where, opts.Args...)
	}
	if err := db.Count(&n).Error; err != nil {
		return 0, err
	}
	return n, nil
}

// Update persists every field of m, which must carry its primary key.
func (s *AuthorStore) Update(ctx context.Context, m *Author) error {
	return s.DB.WithContext(ctx).Save(m).Error
}

// GetByID fetches the Author with the given primary key.
func (s *AuthorStore) GetByID(ctx context.Context, id string) (*Author, error) {
	var m Author
	if err := s.DB.WithContext(ctx).First(&m, "id = ?", id).Error; err != nil {
		return nil, err
	}
	return &m, nil
}

// DeleteByID removes the Author with the given primary key.
func (s *AuthorStore) DeleteByID(ctx context.Context, id string) error {
	return s.DB.WithContext(ctx).Delete(&Author{}, "id = ?", id).Error
}

// GetByName fetches the Author with the given name (a unique column).
func (s *AuthorStore) GetByName(ctx context.Context, v string) (*Author, error) {
	var m Author
	if err := s.DB.WithContext(ctx).First(&m, "name = ?", v).Error; err != nil {
		return nil, err
	}
	return &m, nil
}
