// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store (unknown)
// 	protoc (unknown)
// source: bookstore.proto
//
// database: bookstore_db
// schema:   bookstore_v1
//
// store — https://github.com/the-protobuf-project/store

package bookstorev1

import (
	"context"

	"example.com/test/gen/gormx"
	"gorm.io/gorm"
)

// BookStore provides typed CRUD access to Book records.
// Book is a resource nested under Author. Inferred table: bookstore_v1.books.
type BookStore struct {
	DB *gorm.DB
	// Telemetry observes every operation; nil is a no-op. Wire the generated
	// adapter: NewBookStore(db).WithTelemetry(telemetry.New(o)).
	Telemetry gormx.Telemetry
}

// Compile-time proof that BookStore satisfies the generic gormx.Store, so the
// generic engine can drive it alongside the typed finders below.
var _ gormx.Store[Book] = (*BookStore)(nil)

// NewBookStore returns a BookStore backed by db.
func NewBookStore(db *gorm.DB) *BookStore { return &BookStore{DB: db} }

// WithTelemetry sets the store's Telemetry and returns the store for chaining.
func (s *BookStore) WithTelemetry(t gormx.Telemetry) *BookStore {
	s.Telemetry = t
	return s
}

// Create inserts m.
func (s *BookStore) Create(ctx context.Context, m *Book) error {
	return s.DB.WithContext(ctx).Create(m).Error
}

// List returns the Book records matching opts.
func (s *BookStore) List(ctx context.Context, opts gormx.ListOptions) ([]Book, error) {
	var out []Book
	if err := opts.Apply(s.DB.WithContext(ctx)).Find(&out).Error; err != nil {
		return nil, err
	}
	return out, nil
}

// Count returns the number of Book records matching opts.Where
// (pagination and ordering are ignored).
func (s *BookStore) Count(ctx context.Context, opts gormx.ListOptions) (int64, error) {
	var n int64
	db := s.DB.WithContext(ctx).Model(&Book{})
	if opts.Where != nil {
		db = db.Where(opts.Where, opts.Args...)
	}
	if err := db.Count(&n).Error; err != nil {
		return 0, err
	}
	return n, nil
}

// Update persists every field of m, which must carry its primary key.
func (s *BookStore) Update(ctx context.Context, m *Book) error {
	return s.DB.WithContext(ctx).Save(m).Error
}

// GetByID fetches the Book with the given primary key.
func (s *BookStore) GetByID(ctx context.Context, id string) (*Book, error) {
	var m Book
	if err := s.DB.WithContext(ctx).First(&m, "id = ?", id).Error; err != nil {
		return nil, err
	}
	return &m, nil
}

// DeleteByID removes the Book with the given primary key.
func (s *BookStore) DeleteByID(ctx context.Context, id string) error {
	return s.DB.WithContext(ctx).Delete(&Book{}, "id = ?", id).Error
}

// GetByName fetches the Book with the given name (a unique column).
func (s *BookStore) GetByName(ctx context.Context, v string) (*Book, error) {
	var m Book
	if err := s.DB.WithContext(ctx).First(&m, "name = ?", v).Error; err != nil {
		return nil, err
	}
	return &m, nil
}

// GetByISBN fetches the Book with the given isbn (a unique column).
func (s *BookStore) GetByISBN(ctx context.Context, v string) (*Book, error) {
	var m Book
	if err := s.DB.WithContext(ctx).First(&m, "isbn = ?", v).Error; err != nil {
		return nil, err
	}
	return &m, nil
}

// ListByAuthorID returns the Book records whose author_id matches id, with opts applied.
func (s *BookStore) ListByAuthorID(ctx context.Context, id string, opts gormx.ListOptions) ([]Book, error) {
	var out []Book
	q := opts.Apply(s.DB.WithContext(ctx).Where("author_id = ?", id))
	if err := q.Find(&out).Error; err != nil {
		return nil, err
	}
	return out, nil
}
