// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store (unknown)
// 	protoc (unknown)
// source: bookstore.proto
//
// database: bookstore_db
// schema:   bookstore_v1
//
// store — https://github.com/the-protobuf-project/store

package bookstorev1

import (
	"time"
)

// Genre classifies a book's literary category.
type Genre string

// Genre values as stored in the database.
const (
	// Fictional works: novels, short stories.
	GenreFiction Genre = "FICTION"
	// Non-fiction works: biographies, essays, reference.
	GenreNonFiction Genre = "NON_FICTION"
	// Science fiction works.
	GenreSciFi Genre = "SCI_FI"
	// Fantasy works.
	GenreFantasy Genre = "FANTASY"
)

// Author is a top-level resource. Inferred table: bookstore_v1.authors. id: ID_STRATEGY_ULID synthesizes a generated `id` PK and demotes the AIP resource name to a UNIQUE lookup column; timestamps adds created_at/updated_at.
type Author struct {
	// Unique identifier for the record.
	ID string `gorm:"column:id;primaryKey;not null" json:"id"`
	// name is the AIP resource name; UNIQUE NOT NULL lookup key (id is the PK).
	Name string `gorm:"column:name;not null;uniqueIndex" json:"name" validate:"required"`
	// display_name is REQUIRED → NOT NULL; string → VARCHAR(255) default.
	DisplayName string `gorm:"column:display_name;not null" json:"display_name" validate:"required"`
	// bio is free-form; override the VARCHAR(255) default to unbounded TEXT, nullable.
	Bio *string `gorm:"column:bio" json:"bio,omitempty"`
	// Timestamp when the record was created.
	CreatedAt time.Time `gorm:"column:created_at;type:timestamptz;not null;autoCreateTime" json:"created_at"`
	// Timestamp when the record was last updated.
	UpdatedAt time.Time `gorm:"column:updated_at;type:timestamptz;not null;autoUpdateTime" json:"updated_at"`
	// Back-relation: Book records that reference this via author_id.
	Books []Book `gorm:"foreignKey:AuthorID" json:"books,omitempty"`
}

func (*Author) TableName() string { return "bookstore_v1.authors" }

// Book is a resource nested under Author. Inferred table: bookstore_v1.books.
type Book struct {
	// Unique identifier for the record.
	ID string `gorm:"column:id;primaryKey;not null" json:"id"`
	// name: IDENTIFIER → PRIMARY KEY, VARCHAR(255).
	Name string `gorm:"column:name;not null;uniqueIndex" json:"name" validate:"required"`
	// title: REQUIRED NOT NULL; max_length caps the VARCHAR provider-neutrally.
	Title string `gorm:"column:title;not null" json:"title" validate:"required"`
	// author_id references Author; orm infers the FOREIGN KEY, aligns the column type with the referenced PK (CHAR(26) ULID), and applies CASCADE.
	AuthorID string  `gorm:"column:author_id;not null;index:idx_books_author_year,priority:1" json:"author_id" validate:"required"`
	Author   *Author `gorm:"foreignKey:AuthorID;constraint:OnDelete:CASCADE" json:"author,omitempty"`
	// isbn must be globally unique; custom fixed-width type.
	ISBN *string `gorm:"column:isbn;uniqueIndex" json:"isbn,omitempty"`
	// published_year is a plain integer column; nullable.
	PublishedYear *int32 `gorm:"column:published_year;index:idx_books_author_year,priority:2" json:"published_year,omitempty"`
	// genre demonstrates proto enum → database enum generation, and — with the telemetry opt — labels every traced Create/Update span with its value (low-cardinality, so it's safe as a span attribute).
	Genre Genre `gorm:"column:genre;not null;default:'FICTION';check:chk_books_genre,genre IN ('FICTION','NON_FICTION','SCI_FI','FANTASY')" json:"genre" validate:"required"`
	// create_time is set by the database on insert.
	CreateTime time.Time `gorm:"column:create_time;type:timestamptz;not null;autoCreateTime" json:"create_time"`
}

func (*Book) TableName() string { return "bookstore_v1.books" }
