// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm (unknown)
// 	protoc (unknown)
// source: money.proto
//
// database: freebusy_db
// schema:   common
//
// orm — https://github.com/the-protobuf-project/orm

package common

// Money is an amount of money with its currency type.
type Money struct {
	// Unique identifier for the record.
	ID string `gorm:"column:id;type:char(26);primaryKey;not null" json:"id"`
	// The three-letter ISO 4217 currency code.
	CurrencyCode *string `gorm:"column:currency_code;type:varchar(255)" json:"currency_code,omitempty"`
	// Whole units of the amount.
	Units *int64 `gorm:"column:units" json:"units,omitempty"`
	// Number of nano (10^-9) units of the amount.
	Nanos *int32 `gorm:"column:nanos" json:"nanos,omitempty"`
}

func (*Money) TableName() string { return "common.moneys" }
