// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store (unknown)
// 	protoc (unknown)
//
// database: reserved_db
// schemas:  public
//
// Migration aggregator: every model in one factory Registry.
//
// store — https://github.com/the-protobuf-project/store

// Package reserveddb wires every model generated for the reserved_db database
// into one factory Registry, so an application can migrate the whole database in
// a single call. Default is preloaded with every generated model; Register adds
// your own.
package reserveddb

import (
	"example.com/test/gen/reserved_db/public"

	"gorm.io/gorm"
)

// Migrator is the subset of *gorm.DB the Migrate call needs; *gorm.DB satisfies
// it. EnsureSchemas and Instrument take a concrete *gorm.DB, since creating
// schemas and installing plugins need the full driver.
type Migrator interface {
	AutoMigrate(models ...any) error
}

// schemas lists every Postgres schema the registered models live in, so
// EnsureSchemas can create them before AutoMigrate builds schema-qualified tables.
var schemas = []string{
	"public",
}

// Registry collects GORM models so they migrate together.
type Registry struct {
	models []any
}

// New returns an empty Registry.
func New() *Registry { return &Registry{} }

// Register appends models to the registry and returns it for chaining.
func (r *Registry) Register(models ...any) *Registry {
	r.models = append(r.models, models...)
	return r
}

// Models returns every registered model, in registration order.
func (r *Registry) Models() []any { return r.models }

// Migrate runs AutoMigrate for every registered model.
func (r *Registry) Migrate(db Migrator) error {
	return db.AutoMigrate(r.models...)
}

// EnsureSchemas creates every Postgres schema the registered models live in, if
// it does not already exist. AutoMigrate does not create schemas, so call this
// before Migrate when models map to schema-qualified tables:
//
//	if err := reserveddb.Default.EnsureSchemas(db); err != nil {
//		log.Fatal(err)
//	}
//	if err := reserveddb.Default.Migrate(db); err != nil {
//		log.Fatal(err)
//	}
func (*Registry) EnsureSchemas(db *gorm.DB) error {
	for _, name := range schemas {
		if err := db.Exec(`CREATE SCHEMA IF NOT EXISTS "` + name + `"`).Error; err != nil {
			return err
		}
	}
	return nil
}

// Default holds every model generated for the reserved_db database. Attach it
// in your application's startup:
//
//	if err := reserveddb.Default.Migrate(db); err != nil {
//		log.Fatal(err)
//	}
//
// Register your own models alongside the generated ones:
//
//	reserveddb.Default.Register(&MyModel{})
var Default = New().Register(
	&public.Account{},
)
