-- Code generated by protoc-gen-store. DO NOT EDIT.
-- versions:
-- 	protoc-gen-store (unknown)
-- 	protoc (unknown)
-- source: mixed.proto
--
-- database: mixed_db
-- schema:   store
--
-- store — https://github.com/the-protobuf-project/store

CREATE SCHEMA IF NOT EXISTS "store";

-- Widget sets the table name and timestamps in both vocabularies.
CREATE TABLE "store"."widgets" (
    -- Unique identifier for the record.
    "id"  CHAR(26)  NOT NULL  PRIMARY KEY,
    -- name: IDENTIFIER → PRIMARY KEY.
    "name"  VARCHAR(255)  NOT NULL  UNIQUE,
    -- label renames the column in both vocabularies; protokit.v1 wins ("label").
    "label"  VARCHAR(255),
    -- note carries only storage options, and only in store.v1 — the migrated spelling. Its orm.v1 twin below is on a different field so both paths are exercised in one case.
    "note"  TEXT,
    -- legacy_note is still on orm.v1 storage: the compat fallback must resolve it to the same TEXT column store.v1 would have produced.
    "legacy_note"  TEXT,
    -- Timestamp when the record was created.
    "created_at"  TIMESTAMPTZ  NOT NULL  DEFAULT now(),
    -- Timestamp when the record was last updated.
    "updated_at"  TIMESTAMPTZ  NOT NULL  DEFAULT now()
);


-- Column and table documentation, persisted to the catalog.
COMMENT ON TABLE "store"."widgets" IS 'Widget sets the table name and timestamps in both vocabularies.';
COMMENT ON COLUMN "store"."widgets"."id" IS 'Unique identifier for the record.';
COMMENT ON COLUMN "store"."widgets"."name" IS 'name: IDENTIFIER → PRIMARY KEY.';
COMMENT ON COLUMN "store"."widgets"."label" IS 'label renames the column in both vocabularies; protokit.v1 wins ("label").';
COMMENT ON COLUMN "store"."widgets"."note" IS 'note carries only storage options, and only in store.v1 — the migrated spelling. Its orm.v1 twin below is on a different field so both paths are exercised in one case.';
COMMENT ON COLUMN "store"."widgets"."legacy_note" IS 'legacy_note is still on orm.v1 storage: the compat fallback must resolve it to the same TEXT column store.v1 would have produced.';
COMMENT ON COLUMN "store"."widgets"."created_at" IS 'Timestamp when the record was created.';
COMMENT ON COLUMN "store"."widgets"."updated_at" IS 'Timestamp when the record was last updated.';


-- Auto-update triggers keep updated-at columns current on every UPDATE.
CREATE OR REPLACE FUNCTION "store"."set_updated_at"() RETURNS trigger AS $$
BEGIN
    NEW."updated_at" = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "trg_widgets_updated_at" BEFORE UPDATE ON "store"."widgets"
    FOR EACH ROW EXECUTE FUNCTION "store"."set_updated_at"();
