-- Code generated by protoc-gen-store. DO NOT EDIT.
-- versions:
-- 	protoc-gen-store (unknown)
-- 	protoc (unknown)
-- source: embedded.proto
--
-- database: v1
-- schema:   embedded_v1
--
-- annotations: entity.v1 (unknown), store.v1 (unknown)
-- engine:      protokit (unknown)
--
-- store — https://github.com/the-protobuf-project/store

CREATE SCHEMA IF NOT EXISTS "embedded_v1";

-- Event exercises nested-message normalization: a singular message field becomes a belongs-to relation, a repeated message field becomes a has-many, while well-known and map fields stay scalar / JSONB.
CREATE TABLE "embedded_v1"."events" (
    -- Unique identifier for the record.
    "id"  CHAR(26)  NOT NULL  PRIMARY KEY,
    -- Resource name; the AIP identifier.
    "name"  VARCHAR(255)  NOT NULL  UNIQUE,
    -- Well-known type stays a scalar column, not a relation.
    "create_time"  TIMESTAMPTZ  NOT NULL  DEFAULT now(),
    -- Map fields stay JSONB.
    "labels"  JSONB,
    -- Foreign key to Location.
    "location_id"  VARCHAR(255)  NOT NULL,
    -- Foreign key to Location.
    "billing_id"  VARCHAR(255),
    -- Foreign key to Metadata.
    "metadata_id"  CHAR(26),
    CONSTRAINT "fk_events_location_id" FOREIGN KEY ("location_id") REFERENCES "embedded_v1"."locations"("id") ON DELETE CASCADE,
    CONSTRAINT "fk_events_billing_id" FOREIGN KEY ("billing_id") REFERENCES "embedded_v1"."locations"("id") ON DELETE SET NULL,
    CONSTRAINT "fk_events_metadata_id" FOREIGN KEY ("metadata_id") REFERENCES "embedded_v1"."metadatas"("id") ON DELETE SET NULL
);
CREATE INDEX "idx_events_location_id" ON "embedded_v1"."events" ("location_id");
CREATE INDEX "idx_events_billing_id" ON "embedded_v1"."events" ("billing_id");
CREATE INDEX "idx_events_metadata_id" ON "embedded_v1"."events" ("metadata_id");

-- Attendee carries an IDENTIFIER, so that field is its primary key.
CREATE TABLE "embedded_v1"."attendees" (
    -- Unique identifier for the record.
    "id"  CHAR(26)  NOT NULL  PRIMARY KEY,
    -- Resource name; the AIP identifier.
    "name"  VARCHAR(255)  NOT NULL  UNIQUE,
    -- Email address of the attendee.
    "email"  VARCHAR(255)  NOT NULL,
    -- Parent reference to Event (from the AIP resource pattern).
    "event_id"  CHAR(26)  NOT NULL,
    CONSTRAINT "fk_attendees_event_id" FOREIGN KEY ("event_id") REFERENCES "embedded_v1"."events"("id") ON DELETE CASCADE
);
CREATE INDEX "idx_attendees_event_id" ON "embedded_v1"."attendees" ("event_id");

-- Location is reachable from Event and so becomes its own table; its existing `id` field is promoted to the primary key.
CREATE TABLE "embedded_v1"."locations" (
    -- Unique identifier for the location, assigned by the server.
    "id"  VARCHAR(255)  NOT NULL  PRIMARY KEY,
    -- City where the location resides.
    "city"  VARCHAR(255)  NOT NULL,
    -- Venue name within the city.
    "venue"  VARCHAR(255)
);

-- Metadata is reachable only through Event.metadata and carries no resource annotation, yet it still becomes its own table (with a synthesized primary key) rather than an inlined JSONB blob.
CREATE TABLE "embedded_v1"."metadatas" (
    -- Unique identifier for the record.
    "id"  CHAR(26)  NOT NULL  PRIMARY KEY,
    -- Free-form source system label.
    "source"  VARCHAR(255),
    -- Arbitrary tags.
    "tags"  VARCHAR(255)[],
    -- Singular resource reference → belongs-to with a bare-named FK column (`owner`, no `_id`). Its auto-index must name the scalar field `ownerID`, not the `owner` relation field, or Prisma rejects the @@index.
    "owner"  CHAR(26),
    CONSTRAINT "fk_metadatas_owner" FOREIGN KEY ("owner") REFERENCES "embedded_v1"."attendees"("id")
);
CREATE INDEX "idx_metadatas_owner" ON "embedded_v1"."metadatas" ("owner");
-- tag containment (@>) cannot use a B-tree
CREATE INDEX IF NOT EXISTS "idx_metadatas_tags_gin" ON "embedded_v1"."metadatas" USING gin ("tags");

-- Join table for the many-to-many relation Event.attendees ↔ Attendee.
CREATE TABLE "embedded_v1"."event_attendees" (
    -- Unique identifier for the record.
    "id"  CHAR(26)  NOT NULL  PRIMARY KEY,
    -- Foreign key to Event.
    "event_id"  CHAR(26)  NOT NULL,
    -- Foreign key to Attendee.
    "attendee_id"  CHAR(26)  NOT NULL,
    -- Full resource name of the referenced Attendee, capturing the parent hierarchy the attendee_id id alone omits.
    "attendee_name"  TEXT  NOT NULL,
    CONSTRAINT "fk_event_attendees_event_id" FOREIGN KEY ("event_id") REFERENCES "embedded_v1"."events"("id") ON DELETE CASCADE,
    CONSTRAINT "fk_event_attendees_attendee_id" FOREIGN KEY ("attendee_id") REFERENCES "embedded_v1"."attendees"("id") ON DELETE CASCADE
);
CREATE UNIQUE INDEX "idx_event_attendees_event_id_attendee_id" ON "embedded_v1"."event_attendees" ("event_id", "attendee_id");
CREATE INDEX "idx_event_attendees_attendee_id" ON "embedded_v1"."event_attendees" ("attendee_id");


-- Column and table documentation, persisted to the catalog.
COMMENT ON TABLE "embedded_v1"."events" IS 'Event exercises nested-message normalization: a singular message field becomes a belongs-to relation, a repeated message field becomes a has-many, while well-known and map fields stay scalar / JSONB.';
COMMENT ON COLUMN "embedded_v1"."events"."id" IS 'Unique identifier for the record.';
COMMENT ON COLUMN "embedded_v1"."events"."name" IS 'Resource name; the AIP identifier.';
COMMENT ON COLUMN "embedded_v1"."events"."create_time" IS 'Well-known type stays a scalar column, not a relation.';
COMMENT ON COLUMN "embedded_v1"."events"."labels" IS 'Map fields stay JSONB.';
COMMENT ON COLUMN "embedded_v1"."events"."location_id" IS 'Foreign key to Location.';
COMMENT ON COLUMN "embedded_v1"."events"."billing_id" IS 'Foreign key to Location.';
COMMENT ON COLUMN "embedded_v1"."events"."metadata_id" IS 'Foreign key to Metadata.';
COMMENT ON TABLE "embedded_v1"."attendees" IS 'Attendee carries an IDENTIFIER, so that field is its primary key.';
COMMENT ON COLUMN "embedded_v1"."attendees"."id" IS 'Unique identifier for the record.';
COMMENT ON COLUMN "embedded_v1"."attendees"."name" IS 'Resource name; the AIP identifier.';
COMMENT ON COLUMN "embedded_v1"."attendees"."email" IS 'Email address of the attendee.';
COMMENT ON COLUMN "embedded_v1"."attendees"."event_id" IS 'Parent reference to Event (from the AIP resource pattern).';
COMMENT ON TABLE "embedded_v1"."locations" IS 'Location is reachable from Event and so becomes its own table; its existing `id` field is promoted to the primary key.';
COMMENT ON COLUMN "embedded_v1"."locations"."id" IS 'Unique identifier for the location, assigned by the server.';
COMMENT ON COLUMN "embedded_v1"."locations"."city" IS 'City where the location resides.';
COMMENT ON COLUMN "embedded_v1"."locations"."venue" IS 'Venue name within the city.';
COMMENT ON TABLE "embedded_v1"."metadatas" IS 'Metadata is reachable only through Event.metadata and carries no resource annotation, yet it still becomes its own table (with a synthesized primary key) rather than an inlined JSONB blob.';
COMMENT ON COLUMN "embedded_v1"."metadatas"."id" IS 'Unique identifier for the record.';
COMMENT ON COLUMN "embedded_v1"."metadatas"."source" IS 'Free-form source system label.';
COMMENT ON COLUMN "embedded_v1"."metadatas"."tags" IS 'Arbitrary tags.';
COMMENT ON COLUMN "embedded_v1"."metadatas"."owner" IS 'Singular resource reference → belongs-to with a bare-named FK column (`owner`, no `_id`). Its auto-index must name the scalar field `ownerID`, not the `owner` relation field, or Prisma rejects the @@index.';
COMMENT ON TABLE "embedded_v1"."event_attendees" IS 'Join table for the many-to-many relation Event.attendees ↔ Attendee.';
COMMENT ON COLUMN "embedded_v1"."event_attendees"."id" IS 'Unique identifier for the record.';
COMMENT ON COLUMN "embedded_v1"."event_attendees"."event_id" IS 'Foreign key to Event.';
COMMENT ON COLUMN "embedded_v1"."event_attendees"."attendee_id" IS 'Foreign key to Attendee.';
COMMENT ON COLUMN "embedded_v1"."event_attendees"."attendee_name" IS 'Full resource name of the referenced Attendee, capturing the parent hierarchy the attendee_id id alone omits.';
