// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
//
//	protoc-gen-store (unknown)
//	protoc (unknown)
//
// database: v1
// package:  grpcx
//
// Backend-agnostic resource descriptors: one store.Resource per proto resource.
// Register them with store.NewRegistry(Resources...) and pass any driver.
// annotations: entity.v1 (unknown), store.v1 (unknown)
// engine:      protokit (unknown)
// runtime:     github.com/the-protobuf-project/runtime-go/database/store
//
// store — https://github.com/the-protobuf-project/store
package grpcx

import (
	"example.com/test/gen"
	"github.com/the-protobuf-project/runtime-go/database/store"
	"google.golang.org/protobuf/proto"
)

// Resources are this database's runtime descriptors, one per proto resource.
//
// They carry no storage engine of their own: a descriptor says which table a
// message maps to, what each column is called and how it is typed, and which
// columns reference other resources. The driver decides what that means.
//
//	reg := store.NewRegistry(Resources...)
//	svc := adapter.New(orm.New(db), reg) // or evm.New(cfg), fabric.New(), ...
//
// Columns whose Generated, AutoCreate or AutoUpdate is set report Managed() at
// runtime: the bridge skips them and the driver supplies the value.
//
// Not described here: embedded_v1.event_attendees.
// Those tables are synthesized by the generator — outbox tables, many-to-many
// joins — rather than declared by a proto message, so there is no concrete type
// for New to construct. They are still created by the sql and gorm targets.
var Resources = []store.Resource{
	{
		// Event exercises nested-message normalization: a singular message field becomes a belongs-to relation, a repeated message field becomes a has-many, while well-known and map fields stay scalar / JSONB.
		Name:     "Event",
		Schema:   "embedded_v1",
		Table:    "events",
		PKColumn: "id",
		New:      func() proto.Message { return &gen.Event{} },
		Columns: []store.Column{
			{Name: "id", Field: "", Kind: store.KindString, SQLType: "CHAR(26)", PrimaryKey: true, NotNull: true, Generated: "ulid"},
			{Name: "name", Field: "name", Kind: store.KindString, SQLType: "VARCHAR(255)", NotNull: true, Unique: true},
			{Name: "create_time", Field: "create_time", Kind: store.KindTimestamp, SQLType: "TIMESTAMPTZ", NotNull: true, AutoCreate: true},
			{Name: "labels", Field: "labels", Kind: store.KindString, SQLType: "JSONB"},
			{Name: "location_id", Field: "", Kind: store.KindString, SQLType: "VARCHAR(255)", NotNull: true},
			{Name: "billing_id", Field: "", Kind: store.KindString, SQLType: "VARCHAR(255)"},
			{Name: "metadata_id", Field: "", Kind: store.KindString, SQLType: "CHAR(26)"},
		},
		FKs: []store.ForeignKey{
			{Column: "location_id", ReferencedName: "Location", ReferencedField: "id"},
			{Column: "billing_id", ReferencedName: "Location", ReferencedField: "id"},
			{Column: "metadata_id", ReferencedName: "Metadata", ReferencedField: "id"},
		},
	},
	{
		// Attendee carries an IDENTIFIER, so that field is its primary key.
		Name:     "Attendee",
		Schema:   "embedded_v1",
		Table:    "attendees",
		PKColumn: "id",
		New:      func() proto.Message { return &gen.Attendee{} },
		Columns: []store.Column{
			{Name: "id", Field: "", Kind: store.KindString, SQLType: "CHAR(26)", PrimaryKey: true, NotNull: true, Generated: "ulid"},
			{Name: "name", Field: "name", Kind: store.KindString, SQLType: "VARCHAR(255)", NotNull: true, Unique: true},
			{Name: "email", Field: "email", Kind: store.KindString, SQLType: "VARCHAR(255)", NotNull: true},
			{Name: "event_id", Field: "", Kind: store.KindString, SQLType: "CHAR(26)", NotNull: true},
		},
		FKs: []store.ForeignKey{
			{Column: "event_id", ReferencedName: "Event", ReferencedField: "id"},
		},
	},
	{
		// Location is reachable from Event and so becomes its own table; its existing `id` field is promoted to the primary key.
		Name:     "Location",
		Schema:   "embedded_v1",
		Table:    "locations",
		PKColumn: "id",
		New:      func() proto.Message { return &gen.Location{} },
		Columns: []store.Column{
			{Name: "id", Field: "id", Kind: store.KindString, SQLType: "VARCHAR(255)", PrimaryKey: true, NotNull: true},
			{Name: "city", Field: "city", Kind: store.KindString, SQLType: "VARCHAR(255)", NotNull: true},
			{Name: "venue", Field: "venue", Kind: store.KindString, SQLType: "VARCHAR(255)"},
		},
	},
	{
		// Metadata is reachable only through Event.metadata and carries no resource annotation, yet it still becomes its own table (with a synthesized primary key) rather than an inlined JSONB blob.
		Name:     "Metadata",
		Schema:   "embedded_v1",
		Table:    "metadatas",
		PKColumn: "id",
		New:      func() proto.Message { return &gen.Metadata{} },
		Columns: []store.Column{
			{Name: "id", Field: "", Kind: store.KindString, SQLType: "CHAR(26)", PrimaryKey: true, NotNull: true, Generated: "ulid"},
			{Name: "source", Field: "source", Kind: store.KindString, SQLType: "VARCHAR(255)"},
			{Name: "tags", Field: "tags", Kind: store.KindString, SQLType: "VARCHAR(255)[]"},
			{Name: "owner", Field: "owner", Kind: store.KindString, SQLType: "CHAR(26)"},
		},
		FKs: []store.ForeignKey{
			{Column: "owner", ReferencedName: "Attendee", ReferencedField: "id"},
		},
	},
}
