-- Code generated by protoc-gen-store. DO NOT EDIT.
-- versions:
-- 	protoc-gen-store (unknown)
-- 	protoc (unknown)
-- source: store.proto
--
-- database: users
-- schema:   calendar_app
--
-- store — https://github.com/the-protobuf-project/store

CREATE SCHEMA IF NOT EXISTS "calendar_app";

-- Event is a calendar app resource. The layout config routes it to the "users" database, schema "calendar_app".
CREATE TABLE "calendar_app"."events" (
    -- Unique identifier for the record.
    "id"  CHAR(26)  NOT NULL  PRIMARY KEY,
    -- Resource name; the AIP identifier.
    "name"  VARCHAR(255)  NOT NULL  UNIQUE,
    -- title is the event's display title.
    "title"  VARCHAR(255)  NOT NULL
);


-- Column and table documentation, persisted to the catalog.
COMMENT ON TABLE "calendar_app"."events" IS 'Event is a calendar app resource. The layout config routes it to the "users" database, schema "calendar_app".';
COMMENT ON COLUMN "calendar_app"."events"."id" IS 'Unique identifier for the record.';
COMMENT ON COLUMN "calendar_app"."events"."name" IS 'Resource name; the AIP identifier.';
COMMENT ON COLUMN "calendar_app"."events"."title" IS 'title is the event''s display title.';
