// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store (unknown)
// 	protoc (unknown)
//
// database: v1
// package:  gormx
//
// Shared GORM runtime: ListOptions, the generic Store interface, the GenericStore engine, and EnsureSchemas.
// annotations: entity.v1 (unknown), store.v1 (unknown)
// engine:      protokit (unknown)
// runtime:     gorm.io/gorm
//
// store — https://github.com/the-protobuf-project/store

// Package gormx is the shared runtime the generated GORM stores build on: the
// ListOptions every List/Count call takes, a generic Store interface every
// generated store satisfies, a GenericStore that implements it for any model,
// EnsureSchemas for schema-qualified tables, and the Telemetry seam the
// instrumented stores observe through. Keeping these in one package lets a
// single engine run CRUD for every entity instead of per-entity copies.
package gormx

import (
	"context"
	"strings"
	"time"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

// ListOptions controls pagination, ordering, and filtering for the generated
// List and Count store methods. Where accepts anything gorm.DB.Where understands
// (a struct, a map, or an SQL fragment with Args), e.g.
//
//	ListOptions{Where: "published_year = ?", Args: []any{2024}, OrderBy: "title", Limit: 20}
type ListOptions struct {
	Limit   int
	Offset  int
	OrderBy string
	Where   any
	Args    []any
}

// Apply layers the options onto a query. Count callers apply only Where (see the
// generated Count methods), since limit/offset must not change the total.
func (o ListOptions) Apply(db *gorm.DB) *gorm.DB {
	if o.Where != nil {
		db = db.Where(o.Where, o.Args...)
	}
	if o.OrderBy != "" {
		db = db.Order(o.OrderBy)
	}
	if o.Limit > 0 {
		db = db.Limit(o.Limit)
	}
	if o.Offset > 0 {
		db = db.Offset(o.Offset)
	}
	return db
}

// Store is the CRUD surface every generated store satisfies, so a single engine
// can run create/read/update/delete for every entity. M is the model type; the
// primary key is the string id orm synthesizes by default (ULID/UUID), so a
// store whose primary key is not a string simply does not implement Store.
type Store[M any] interface {
	Create(ctx context.Context, m *M) error
	GetByID(ctx context.Context, id string) (*M, error)
	List(ctx context.Context, opts ListOptions) ([]M, error)
	Count(ctx context.Context, opts ListOptions) (int64, error)
	Update(ctx context.Context, m *M) error
	DeleteByID(ctx context.Context, id string) error
}

// GenericStore is a ready-made Store[M] for any model M — the generic engine that
// needs no per-entity code. The generated per-resource stores wrap a *gorm.DB the
// same way and add typed finders (GetBy/ListBy) on top; use GenericStore when the
// plain CRUD surface is enough.
type GenericStore[M any] struct{ DB *gorm.DB }

// New returns a GenericStore[M] backed by db.
func New[M any](db *gorm.DB) *GenericStore[M] { return &GenericStore[M]{DB: db} }

// Create inserts m.
func (s *GenericStore[M]) Create(ctx context.Context, m *M) error {
	return s.DB.WithContext(ctx).Create(m).Error
}

// GetByID fetches the M with the given primary key. The primary key column is
// resolved from the model, so any single-column primary key works.
func (s *GenericStore[M]) GetByID(ctx context.Context, id string) (*M, error) {
	var m M
	if err := s.DB.WithContext(ctx).
		Where(clause.Eq{Column: clause.PrimaryColumn, Value: id}).
		First(&m).Error; err != nil {
		return nil, err
	}
	return &m, nil
}

// List returns the M records matching opts.
func (s *GenericStore[M]) List(ctx context.Context, opts ListOptions) ([]M, error) {
	var out []M
	if err := opts.Apply(s.DB.WithContext(ctx)).Find(&out).Error; err != nil {
		return nil, err
	}
	return out, nil
}

// Count returns the number of M records matching opts.Where
// (pagination and ordering are ignored).
func (s *GenericStore[M]) Count(ctx context.Context, opts ListOptions) (int64, error) {
	db := s.DB.WithContext(ctx).Model(new(M))
	if opts.Where != nil {
		db = db.Where(opts.Where, opts.Args...)
	}
	var n int64
	if err := db.Count(&n).Error; err != nil {
		return 0, err
	}
	return n, nil
}

// Update persists every field of m, which must carry its primary key.
func (s *GenericStore[M]) Update(ctx context.Context, m *M) error {
	return s.DB.WithContext(ctx).Save(m).Error
}

// DeleteByID removes the M with the given primary key.
func (s *GenericStore[M]) DeleteByID(ctx context.Context, id string) error {
	return s.DB.WithContext(ctx).
		Where(clause.Eq{Column: clause.PrimaryColumn, Value: id}).
		Delete(new(M)).Error
}

// Compile-time proof that GenericStore[M] implements Store[M].
var _ Store[struct{}] = (*GenericStore[struct{}])(nil)

// EnsureSchemas creates each named Postgres schema if it does not already exist,
// so AutoMigrate can build schema-qualified tables (a TableName like
// "promo.promo_codes" needs its "promo" schema to exist first). Call it once
// before migrating, e.g. gormx.EnsureSchemas(db, "promo", "booking").
func EnsureSchemas(db *gorm.DB, names ...string) error {
	for _, name := range names {
		if err := db.Exec("CREATE SCHEMA IF NOT EXISTS " + quoteIdent(name)).Error; err != nil {
			return err
		}
	}
	return nil
}

// quoteIdent double-quotes a Postgres identifier, escaping embedded quotes, so a
// schema name is treated as an identifier and never as SQL.
func quoteIdent(s string) string {
	return `"` + strings.ReplaceAll(s, `"`, `""`) + `"`
}

// Telemetry receives the instrumented stores' spans and per-operation metrics.
// Wire the generated telemetry adapter (telemetry.New(o)) via each
// store's WithTelemetry, or implement it yourself; a nil store field is a
// no-op (see OrNop). The interface names no SDK type, so this package — and
// every models package — compiles without the SDK when telemetry is unused.
//
// Metrics stay scoped to the database operation itself (table, op, status) by
// design — domain-level metrics (e.g. business values from the model) belong
// to the application, not the ORM; record those with your own metrics setup.
type Telemetry interface {
	// Span wraps one store operation in a trace span; data (the model on
	// writes, nil elsewhere) carries `opentelementry:"trace:..."`-tagged
	// fields the SDK lifts into span attributes.
	Span(ctx context.Context, name string, data any, fn func(context.Context) error) error
	// RecordOp records one completed operation: an ops counter + duration
	// histogram attributed by table, op, and status, plus error logging.
	RecordOp(ctx context.Context, table, op string, d time.Duration, err error)
}

// NopTelemetry observes nothing.
type NopTelemetry struct{}

// Span runs fn without tracing.
func (NopTelemetry) Span(ctx context.Context, _ string, _ any, fn func(context.Context) error) error {
	return fn(ctx)
}

// RecordOp discards the measurement.
func (NopTelemetry) RecordOp(context.Context, string, string, time.Duration, error) {}

// OrNop returns t, or NopTelemetry when t is nil — the stores' nil-safety.
func OrNop(t Telemetry) Telemetry {
	if t == nil {
		return NopTelemetry{}
	}
	return t
}

// OpMetric is the per-operation measurement the telemetry adapter records;
// the struct tags drive the SDK's metric registration (names are
// service-prefixed by the SDK at record time).
type OpMetric struct {
	Ops        int64   `opentelementry:"metric:counter:orm.store.ops"`
	DurationMS float64 `opentelementry:"metric:histogram:orm.store.duration_ms"`
}
